### ISSUE TITLE
ant noframe report extra test for ParameterizedTest

### ISSUE THREAD

**Issue by henryzhang1** [junit-team/junit5#1121]
Junit5 version: 1.0.1
Test class:
@RunWith(JUnitPlatform.class)
public class Junit5SampleUnitTests
{
    @DisplayName("Parameterized positive tests")
    @ParameterizedTest
    @ValueSource(strings = {"aba", "cbggbc"})
    public void testPositivePalindromes(String argument)
    {
        assertTrue(isPalindrome(argument));
    }
   private boolean isPalindrome(String testString)
    {...}
}
Command:
ant test

Ant config:
            <junitreport todir="${junit.report.location}">
                <fileset dir="${junit.report.xml}" includes="${junit.report.include}"/>
                <report format="noframes" styledir="${env.BUILD_SYSTEM_ROOT}/${HOMES.BUILD_SYSTEM_VERSION}/java" todir="${junit.report.location}"/>

Expected:
two tests are reported

Actual:
Three tests are reported in TESTS-TestSuites.xml:

<testsuite errors="0" failures="0" hostname="xxx" id="1003" name="Junit5SampleUnitTests" package="aaa.Junit5samples" skipped="0" tests="3" time="0.034"" timestamp="2017-10-19T22:50:24">
      
<testcase classname="Parameterized positive tests" name="[1] aba" time="0.033" />
<testcase classname="Parameterized positive tests" name="[2] cbggbc" time="0.0" />

**Comment by marcphilipp** [comment]
This happens because Ant uses JUnit 4 to execute your test which does not really support the concept of a _dynamic_ test but considers all leaves in the initial test tree as tests.

In this example the initial test tree looks like this:

```
Junit5SampleUnitTests
└─ testPositivePalindromes(String)
```

Thus, JUnit 4 considers `testPositivePalindromes(String)` a test. At runtime, there will be two invocations which will be reported as additional, _dynamic_ nodes in the test tree, i.e.

```
Junit5SampleUnitTests
└─ testPositivePalindromes(String)
   ├─ [1] aba
   └─ [2] cbggbc
```

JUnit 4 would now only consider the two new leaf nodes as tests.

The XML report isn't created by JUnit 4 but by Ant, so I'm not sure where this would have to be fixed. However, you could use the `ConsoleLauncher` to use the JUnit Platform to execute the test from Ant. That would solve the problem.
