### ISSUE TITLE
TestReporter entries are not published to maven surefire reports

### ISSUE THREAD

**Issue by reitzmichnicht** [junit-team/junit5#1161]
Using JUnit 5.0.2 it would be great if entries published to the TestReporter are also written to the TEST-*.xml files of the maven surefire reports as properties.

Needed for example to document the seed used for random values.

Kind regards,
Michael

**Comment by marcphilipp** [comment]
I'm not sure pretending report entries are system properties is a good idea. What we'd really need is a new reporting format (see #373). In the meantime, instead of ignoring them completely, I guess we could at least write them to stdout in `RunListenerAdapter`.

@reitzmichnicht Would that suit your needs?

**Comment by reitzmichnicht** [comment]
Yes writing to stdout would be a good starting point.
But keep in mind that surefire does not show stdout by default AFAIK.
