### ISSUE TITLE
TestReporter entries of a TestInstancePostProcessor extension are not written to the TestInstance output

### ISSUE THREAD

**Issue by reitzmichnicht** [junit-team/junit5#1162]
Using JUnit 5.0.2 with latest IntelliJ.

Having an extension with this code:
```
  @Override
  public void postProcessTestInstance(Object testInstance, ExtensionContext context) {
      long seed = 123L;
      context.publishReportEntry("seed", String.valueOf(seed));
  }
```
When using this extension on a test class, the report entries is not written to the stdout of the test class, but to the general stdout of the test run.
Having multiple test classes in one run it is not possible to determine which report entry belongs to which test class.

Kind regards,
Michael

**Comment by marcphilipp** [comment]
JUnit does not print report entries to stdout. Thus, this is probably an IntelliJ issue. Can you please open an issue at their bug tracker?

**Comment by marcphilipp** [comment]
I just verified that the report entry is attached to the test class in this case. That's because the ExtensionContext for a TIPP represents the test class. If you want to attach it to the test method, you could use a `BeforeEachCallback`. In my IntelliJ IDEA (2017.2.5), the report entry is shown on the test class:

<img width="1071" alt="screen shot 2017-11-15 at 19 51 26" src="https://user-images.githubusercontent.com/214207/32854279-67bbec8a-ca3e-11e7-9ef9-7fe0e445c25d.png">

```java
@ExtendWith(TestReporterDemo.MyExtension.class)
class TestReporterDemo {

	static class MyExtension implements TestInstancePostProcessor {
		@Override
		public void postProcessTestInstance(Object testInstance, ExtensionContext context) {
			long seed = 123L;
			context.publishReportEntry("seed", String.valueOf(seed));
		}
	}

	@Test
	void reportSingleValue(TestReporter testReporter) {
		testReporter.publishEntry("a key", "a value");
	}

	@Test
	void reportSeveralValues(TestReporter testReporter) {
		HashMap<String, String> values = new HashMap<>();
		values.put("user name", "dk38");
		values.put("award year", "1974");

		testReporter.publishEntry(values);
	}

}
```
