### ISSUE TITLE
Introduce file-based declarative test suite support

### ISSUE THREAD

**Issue by paul-nelson-baker** [junit-team/junit5#1243]
## Overview

I'd like to know if the equivalent exists or is in the works to match `TestNG`'s suite XML file format. I asked on Stack Overflow and was directed by @marcphilipp to open a feature request for this. Here are the details from the [original SO post](https://stackoverflow.com/q/47938209/1478636):

I've been dynamically generating TestNG XML suites in a project I'm working on. In an effort to take some initiative in migrating to JUnit 5. The TestNG specification is [very easy to find](http://testng.org/doc/documentation-main.html#testng-xml), but I cannot find the equivalent for JUnit 5.

All I can find are references that a file or URI can be specified for test discovery. Either by [command line option or URI](http://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher-options) and again under the [configuring selectors section](http://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-selectors).

Naively, I'd like to assume that it's just the `fully.qualified.package.ClassName#methodName` format because I can find this as an example in the [MethodSelector](http://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/DiscoverySelectors.html#selectMethod-java.lang.String-). The [UriSelector](http://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/DiscoverySelectors.html#selectUri-java.lang.String-) and [FileSelector](http://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/DiscoverySelectors.html#selectFile-java.io.File-) don't show what the actually expected format of the document is supposed to look like.

## Related Issues:

- #744

**Comment by sbrannen** [comment]
> The UriSelector and FileSelector don't show what the actually expected format of the document is supposed to look like.

That's because JUnit Jupiter does not in any way support those two selectors.

They only exist for _other_ test engines that want to make use of them.

**Comment by sbrannen** [comment]
> I'd like to know if the equivalent exists or is in the works to match TestNG's suite XML file format.

The short answer to that is "no". There is currently no support for suite configuration via a file.

However, the fact that you've raised this issue means that it's now "open for discussion". 😉

**Comment by sbrannen** [comment]
FYI: I've renamed this issue to reflect the scope.

**Comment by vlsi** [comment]
I have a case for suites: integration testing.
Individual tests are like "prepare configuration, upload configuration, perform test method".
However, "upload configuration" is slow (e.g. it takes minutes), so I work around that by combining the configuration from all the test classes and uploading it once.

Of course, certain configurations can't be combined. For instance, test cases for "invalid configuration should produce reasonable errors" must not be combined with valid configurations otherwise the combined configuration won't even work.

That is why I use suites to split test classes into bigger chunks so I save time on testing (configuration upload is performed just once) with reasonable sacrifice in quality (test data/configurations are mostly independent, so test interference is acceptable for me).

**Comment by mpkorstanje** [comment]
This looks like a variation of https://github.com/junit-team/junit5/issues/744 and https://github.com/junit-team/junit5/pull/2416 but rather then using annotations to create the discovery request an xml file is used instead.
