### ISSUE TITLE
junit-vintage-engine coupling to JUnit 4.12

### ISSUE THREAD

**Issue by rschmitt** [junit-team/junit5#1264]
I noticed that `org.junit.vintage:junit-vintage-engine` had its versioning scheme changed in 1562208a3111d919b5505514baac87912870f533. Since the vintage engine depends directly on JUnit 4.12 (and therefore, transitively, on Hamcrest 1.3), I'm not sure what is going to happen when JUnit 4.13 is released, or how to model these artifacts in my company's build system (which is much stricter than Maven when it comes to version conflicts). Should there perhaps be separate vintage engines for JUnit 4.12 and 4.13?

**Comment by sbrannen** [comment]
> Should there perhaps be separate vintage engines for JUnit 4.12 and 4.13?

No, that should not be necessary.

JUnit Vintage merely requires a minimum of JUnit 4.12. Subsequent releases of JUnit 4 (e.g., 4.13) _should not_ introduce changes that are incompatible with JUnit Vintage.

I say "should not" because they really shouldn't; however, if a subsequent release of JUnit 4 were to be broken in terms of compatibility (albeit highly unlikely), we would address that issue then.

I am therefore closing this issue as "declined" for the time being.

**Comment by rschmitt** [comment]
Fair enough. Thanks for the info!
