### ISSUE TITLE
Running Test suite with a @TestFactory method

### ISSUE THREAD

**Issue by aaronhonra** [junit-team/junit5#1435]
I'm running a Test Suite in JUnit 5 using TestFactory methods to run dynamic tests.  But then the result is always showing a **no name** DisplayName even though I have written a display name.  Also noticed that static tests were run but ended up using a new Junit Jupiter Test instance.  See photo below.

![image](https://user-images.githubusercontent.com/39552864/40642271-2c7638d8-634f-11e8-899e-f92efa619e54.png)

**Comment by marcphilipp** [comment]
Are you using `@RunWith(JUnitPlatform.class)`?

**Comment by aaronhonra** [comment]
yes

**Comment by sormuras** [comment]
Can you please provide the `--details tree` output from a test run using the [Console Launcher](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher)?

**Comment by sormuras** [comment]
Strange. Selecting a class via `-c` doesn't work here as expected. The "JUnit Vintage" engine should pick the suite class, iirc.

Can you try the following please?
```bash
java -jar junit-platform-console-standalone-1.2.0.jar
  --class-path ... # point to the directory the contains your compiled test classes
  --class-path ... # point to the directory the contains your compiled main classes
  --class-path ... # any external libraries
  --disable-ansi-colors
  --scan-class-path
```

**Comment by aaronhonra** [comment]
Please see output below.
![image](https://user-images.githubusercontent.com/39552864/40646550-1175eb16-635c-11e8-8e4a-d125286fa2fc.png)

**Comment by aaronhonra** [comment]
yep, Ive been using maven.   Im not sure on what you mean by the main classes and the test classes?
Im just finding the class CmWeekEnding20180525Suite  which is located at this path.
![image](https://user-images.githubusercontent.com/39552864/40647283-0c1f74c8-635e-11e8-891d-c4f2396ccf49.png)

**Comment by marcphilipp** [comment]
The `ConsoleLauncher` is using an implicit class name filter, please use `--include-classname '.*'` to allow all class names.

**Comment by sormuras** [comment]
I keep forgetting about the filter...

So, with Marcs' advise and Maven as a build tool, the command should read:

```bash
java -jar junit-platform-console-standalone-1.2.0.jar
  --class-path target\classes
  --class-path target\main-classes
  --class-path ... # any external libraries
  --disable-ansi-colors
  --include-classname ".*"
  --scan-class-path
```

Mandated, you current working directory is `cm`. Which also contains `junit-platform-console-standalone-1.2.0.jar`.

**Comment by sbrannen** [comment]
> The "JUnit Vintage" engine should pick the suite class, iirc.

Nope, that unfortunately does not work. 😞 

The Vintage Test Engine explicitly ignores classes annotated with `@RunWith(JUnitPlatform)`:

https://github.com/junit-team/junit5/blob/2dc55df1e1197fa36d3d8438b0eea568a0e24155/junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/DefensiveAllDefaultPossibilitiesBuilder.java#L107-L114

**Comment by sbrannen** [comment]
What happens if you select (via the mouse) *only* the test suite class annotated with `@RunWith(JUnitPlatform.class)` and instruct IntelliJ to run it as a test?

**Comment by sbrannen** [comment]
`junit-platform-console-standalone-1.2.0.jar` does not contain the contents of the `junit-platform-runner` artifact. 

So that's why `org.junit.platform.runner.JUnitPlatform` cannot be found.

If you wanted it to be there, you would have to add `junit-platform-runner-1.2.0.jar` to the classpath, but as I mentioned above... that won't help since the `JUnitPlatform` runner cannot be executed directly on the JUnit Platform.

**Comment by sbrannen** [comment]
In other words, I think we can forget about trying to use the `ConsoleLauncher` here.

My understanding is that you wish to annotate a test class with `@RunWith(JUnitPlatform.class)` and run it as a test suite within IntelliJ IDEA, and that you wish to see display names for your dynamic tests.

With that in mind, what happens if you annotate your test suite class with `@UseTechnicalNames` and run it by itself in IDEA?

Do you then see names for the dynamic tests?

**Comment by aaronhonra** [comment]
Issue here was running class that uses @TestFactory when using Test Suite that runs with JUnitPlatform.class
As an example, I pasted another run that only uses the test factory method that resides in (CmMeterReadDataAnalysisAlgComp_ImplTest)
In the image below, we can see that no name was displayed even though Displayname was set in the method being run.  Also notice that a hanging <no name> was also displayed.  Also the program executed only 22 of the 23 tests.

I haven't tried using technical names.  Ill use it in a bit.


![image](https://user-images.githubusercontent.com/39552864/40658307-72e88b76-637d-11e8-92f8-c4de34a36021.png)

**Comment by sbrannen** [comment]
> This is what happens when I run the test by itself without using the test suite

Good. That's what we expect.

Thanks for confirming!

So the display names are present and used when executing the tests directly on the JUnit Platform.

**Comment by sbrannen** [comment]
> I haven't tried using technical names. Ill use it in a bit.

OK. Thanks.

**Comment by aaronhonra** [comment]
This is what happens when i used technical names.
![image](https://user-images.githubusercontent.com/39552864/40667401-ab1211e0-6394-11e8-9452-a27d9fe8071a.png)

**Comment by marcphilipp** [comment]
Since JUnit 4, does not have the notion of dynamic tests, there's not much we can do to improve the situation for the `JUnitPlatform` runner. Triggered by this and other requests for first-class support of suites on the JUnit platform, I've spiked an implementation on a [branch](https://github.com/junit-team/junit5/tree/experiments/platform-suites). Please subscribe to #744 to follow our progress.
