### ISSUE TITLE
Introduce a plain-old JAR

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#146]
Do you plan to package a "plain-old JAR" version of JUnit 5?
See JUnit 4 https://github.com/junit-team/junit/wiki/Download-and-Install#plain-old-jar

Or is "junit5-api-5.0.0-xyz.jar" the designated standalone library?

**Comment by marcphilipp** [comment]
In contrast to JUnit 4, JUnit 5 has a modular structure. Every module has its own JAR. You can download the individual JARs from [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.junit%22).

In addition, there is a [ZIP distribution](http://search.maven.org/remotecontent?filepath=org/junit/junit-console/5.0.0-ALPHA/junit-console-5.0.0-ALPHA.zip) of junit-console that includes all of its dependencies in the lib folder but does not include any engines at the moment. In order to run JUnit 4 tests you'd have to add junit-4.12.jar and junit4-runner.jar to the classpath, for JUnit 5 you need to add junit5-api.jar and junit5-engine.jar.

If you use Maven or Gradle you can use the setup we provide in our [sample projects](https://github.com/junit-team/junit5-samples).

Are you looking for a single JAR that includes the contents of all the other JARs? If so, how would you use it? Would a ZIP file containing all of the individual JARs be of any use?

**Comment by sormuras** [comment]
Hassle-free usage in manually managed projects. This goes for writing and compiling test cases and running them:

**junit5-api.jar** is sufficient for writing/compiling.
**junit5-all.jar** would be your choice running your tests on console.

Didn't know about the junit-console ZIP. If it contained the JUnit 5 api+engine by default, i think it was close enough to a "plain-old" JAR distro. 
And on the long run, IDEs (and tools like Ant, etc...) will support version 5 out-of-the-box and hide the required classpath setup anyway.

**Comment by marcphilipp** [comment]
I've added `junit4-engine`, `junit-4.12`, `junit5-engine`, and `junit5-api` to the ZIP artifact. The next snapshot will already include it.

**Comment by sormuras** [comment]
Great, Marc! Thanks.

**Comment by sormuras** [comment]
Do you mind adding the `junit4-runner` JAR as well?

**Comment by nicolaiparlog** [comment]
> Do you mind adding the `junit4-runner` JAR as well?

:+1:

**Comment by marcphilipp** [comment]
Team discussion result: We will add `junit4-runner` as well but will not change the shell scripts because they are generated by Gradle and we do not want to maintain them ourselves.

**Comment by marcphilipp** [comment]
`junit4-runner.jar` is now included in the ZIP distribution.

**Comment by sbrannen** [comment]
Reopening this issue in order to remove explicit dependencies on JUnit 4 and JUnit 5 from the `ConsoleRunner` and Maven Surefire provider.

For M2, the JUnit Team will come up with a different solution to address the _Plain Old JAR_ and #258.

**Comment by sbrannen** [comment]
_in progress_

**Comment by smoyer64** [comment]
For Maven users, it would also be convenient to have a couple of BOM POMs available.  I'm not a Gradle user (so I don't know how you're deploying to Maven Central) but if you simply want the extra POMs at the top-level of the project, I'd be happy to contribute them.

**Comment by sbrannen** [comment]
@smoyer64,

We've already discussed possibly introducing BOMs. So I'll go ahead and create an issue to track that now.

**Comment by sbrannen** [comment]
Remaining tasks for M1 have been pushed to `master`, and I am therefore moving this issue to M2.

**Comment by marcphilipp** [comment]
AppVeyor wants to have separate steps for building and testing. I've changed the config so we now use

1. `gradlew --refresh-dependencies clean assemble` to build
2. `gradlew build` to test

I know that looks confusing. But when you look at the [task graph](https://docs.gradle.org/current/userguide/java_plugin.html#N15A90) of Gradle's Java plugin, that should do the trick:
![javaplugintasks](https://cloud.githubusercontent.com/assets/214207/21080680/e92d4ed8-bfb5-11e6-9d29-501a3011e98f.png)

**Comment by sbrannen** [comment]
@marcphilipp, I think you meant to post that comment on #596. 😉

**Comment by marcphilipp** [comment]
Oops, indeed. 😳

**Comment by sormuras** [comment]
As #258 and #259 are slated for M4, this issue #146 and the PR #640 could also be tagged with the M4 target.

**Comment by marcphilipp** [comment]
Good catch! I've changed the milestones for both #146 and #640.
