### ISSUE TITLE
Feature: MethodSource provider add source

### ISSUE THREAD

**Issue by RomanIovlev** [junit-team/junit5#1502]
My request related to implemented feature #1088 for `@MethodSource`.

Can we also implement case 2?

Reason: sometimes full path is too long and most important part, the method name become not obvious.

Example:

```java
@MethodSource("com.company.area.subarea.undere.some.package.services.dataProviders.ComplexDataProvider#rule1")
@MethodSource("com.company.area.subarea.undere.some.package.services.dataProviders.ComplexDataProvider#rule2")
@MethodSource("com.company.area.subarea.undere.some.package.services.dataProviders.ComplexDataProvider#rule3")
```

vs

```java
@MethodSource(value = "rule1", source = ComplexDataProvider.class)
@MethodSource(value = "rule2", source = ComplexDataProvider.class)
@MethodSource(value = "rule3", source = ComplexDataProvider.class)
```

And `Class` is more stable than `String` during refactoring.

If you agree I can do pull request.

P.S. In any case this is just an additional way and if you want you can use current approach.

**Comment by sbrannen** [comment]
Thanks for making the suggestion.

Please note, however, that the `value` attribute in `@MethodSource` is actually an array (i.e., `String[]` instead of simply `String`).

Thus, adding a `Class<?> source();` (or `Class<?>[] sources();`) attribute would result in an awkward API at best.

Since the team has already weighed the pros and cons of this and implemented the _team decision_ in conjunction with #1088, I am closing this issue as "declined".

**Comment by RomanIovlev** [comment]
@sbrannen Ok and why it is and array? Where I can find how to use it as array?

**Comment by sbrannen** [comment]
`@MethodSource` is not a `@Repeatable` annotation, but you can supply multiple values via the array in order to use multiple factory methods.
