### ISSUE TITLE
Help with maven surefire plugin configurations

### ISSUE THREAD

**Issue by ghuangups** [junit-team/junit5#1507]
Hi,

I need some help with maven surefire plugin. My original post is at here: https://github.com/junit-team/junit5/issues/1494 which was two week ago :(

However, it has been a long time and I'm not getting anywhere. Can some one please help? Is there anyone I can contact/talk to besides post an issue here? I can be reached at j.huang@cloudera.com.

Thanks in advance,
George

**Comment by smoyer64** [comment]
@ghuangups - George ... I for one totally missed your earlier issue.  Unfortunately you're posting an issue on the JUnit5 issue tracker and you're using JUnit 4 in your project.  JUnit5 is a complete rewrite that targets Java SE 8 and above and so this team probably won't be as helpful in troubleshooting the issue.

For JUnit5 discussion without the impedance of using the issue tracker, a lot of us hang out on the JUnit5 Gitter channel.  This [section of the Users Guide](https://junit.org/junit5/docs/current/user-guide/#overview-getting-help) has a link to Gitter as well as to StackOverflow.  But again, both these resources are targeted at JUnit5 rather than JUnit4.  As a side note, I had a lot of problems with groups in JUnit4 and pretty much ignored them.

**Comment by smoyer64** [comment]
@ghuangups I see that you've already put issues into the JUnit4 team's issue tracker so I guess you found the answer to question 1 above.  Switching to JUnit5 is probably a better long-term strategy - JUnit5 doesn't have ``@Category`` but instead uses ``@Tag`` (see: https://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering).

@boyarsky wrote a cool tool that can migrate a large percentage of your existing tests boiler-plate to JUnit5 (see https://github.com/boyarsky/convert-junit4-to-junit5)

**Comment by marcphilipp** [comment]
@ghuangups Posting a minimal sample project that reproduces the problem to StackOverflow is probably the fastest way to get help.
