### ISSUE TITLE
Document how to use ConsoleLauncher archive in the User Guide

### ISSUE THREAD

**Issue by nicolaiparlog** [junit-team/junit5#155]
I've been trying to get the console runner working for a while now (the one from [the ZIP](http://search.maven.org/remotecontent?filepath=org/junit/junit-console/5.0.0-ALPHA/junit-console-5.0.0-ALPHA.zip) linked in #146) but failed. I'm assuming I'm doing something wrong.

After I failed to launch the script in any sensible configuration, I looked at the code and got it running from within IntelliJ with the following parameters:

```
-p ${my_test_root_directory} -a
```

or

```
-p ${my_test_root_directory} ${name_of_some_test_class}
```

Irritatingly, the same arguments to the script lead to an empty run:

```
junit-console -p ~/code/JUnit-5-Demo/target/test-classes/ -a

Feb 13, 2016 7:46:04 AM org.junit.gen5.launcher.main.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs []
Test execution started. Number of static tests: 0
Test execution finished.
```

As I said, I'm assuming I'm doing something wrong but I have no idea what it could be.

**Comment by marcphilipp** [comment]
From the logging it looks like no TestEngines are available at runtime. Are junit5-engine.jar and junit4-engine.jar present in the lib folder and includes in the classpath in junit-console.sh/.bat?

**Comment by nicolaiparlog** [comment]
Damn it! :flushed: Well, at least I was right that I was doing something wrong. :stuck_out_tongue_winking_eye: I even checked that but mistook `junit-engine-api-5.0.0-ALPHA.jar` for `junit5-engine-5.0.0-ALPHA.jar`.

Now that that's solved I end up at a similar point [as in #146](https://github.com/junit-team/junit5/issues/146#issuecomment-183088096). Is the ZIP The Official Way to get and use the console runner? If so, I'd be happy to ...

1. document the current situation
2. slightly change the script to include all JARs in `lib`
3. add the test engines or at least recommend them in the documentation

**Comment by marcphilipp** [comment]
Yep, the ZIP is the official way to use the console runner and therefore should be documented as such. Do you have time to provide a pull request?

Regarding the script: I agree that it would be nice to include all JARs in the lib folder. However, the script is not hand-written but generated by Gradle. I very briefly looked into the options of the application plugin and couldn't find a way to enable this behaviour besides overriding the whole script. Since I do not want to maintain a shell and a batch script, I don't think that's the way to go. Maybe you can find a way to change its behaviour without replacing the whole script?

The test engines have been added (in the current snapshot) in #146.

**Comment by marcphilipp** [comment]
Team decision: Document how to use ZIP distribution in User Guide.

@nicolaiparlog Do you have time to work on this issue?

**Comment by nicolaiparlog** [comment]
Let's see how #258 comes along (good thing, I'm lazy).

**Comment by Mathreyu** [comment]
Hey there, I recently got interest in helping to this awesome project. How can I help in this issue? (I'm rather new to this so bare with me if I take a while :P)

**Comment by sbrannen** [comment]
@Mathreyu, glad to hear you're interested in helping out!

At the moment, however, I think it's probably better to wait on the outcome of #258 before we spend too much time documenting how to use the `ConsoleLauncher` since that will certainly change.

In the meantime, you are free to check out any of the other [up-for-grabs](https://github.com/junit-team/junit5/labels/up-for-grabs) issues.

**Comment by Mathreyu** [comment]
@sbrannen Thanks :D Will do.

**Comment by marcphilipp** [comment]
We have decided to get rid of the ZIP archive distribution in favor of providing a fat JAR (see #258).
