### ISSUE TITLE
@ParameterizedTest using @CsvFileSource does not allow trailing whitespace in last argument

### ISSUE THREAD

**Issue by juniorjrjl** [junit-team/junit5#1551]
JUnit version: 5.2.0

When I create a test that uses a CSV file and the last argument has whitespace to the right, the method's parameter gets a value without the whitespace.

**Comment by sbrannen** [comment]
That is the expected behavior.

Whitespace is trimmed by default.

If you want to include whitespace you need to wrap the value in double quotes.

For example:

```csv
1, Sweden
2, "United States of America "
```

If the above CSV file is used as input for a parameterized test, the second value from the second line will contain the trailing spaces: `"United States of America "`.

I am therefore closing this issue as "works as designed".

**Comment by juniorjrjl** [comment]
thank you :)

**Comment by sbrannen** [comment]
You're welcome
