### ISSUE TITLE
Introduce extension API for executing test in user-defined thread

### ISSUE THREAD

**Issue by schauder** [junit-team/junit5#157]
## Overview

I couldn't find a way to write an extension that changes the behavior of test execution.

Examples of what I would like to do are:

- let each test run 100x in 5 threads to check for race conditions
- let a test execute in the Swing EDT Thread.

Such use cases were easy to implement with JUnit 4 Rules, and I used especially the second a lot. So I think it would be bad to lose this option in JUnit Jupiter.

## Proposals

- see https://github.com/junit-team/junit5/issues/157#issuecomment-190187989

## Related Issues

- supersedes #20 
- related to #201
- related to #1248 
- duplicated by #1442

**Comment by jlink** [comment]
Your first point falls into the broader category of dynamic test creation
(see #58) and is the next bigger feature on our list.

As for test execution in a different thread, we haven't discussed that yet
- as far as I can remember. It could be handled as a special case of
asynchronous testing and I personally never felt the need to have the whole
test run in the SWT thread; wouldn't it suffice to have some asserts use
that thread?

2016-02-15 14:23 GMT+01:00 Jens Schauder <notifications@github.com>:

**Comment by schauder** [comment]
> wouldn't it suffice to have some asserts use
that thread?

Not really, because all Swing Component manipulation must be in the EDT. Anyway these are just two examples where the approach of Rules came in really handy: you get a Statement, you return a Statement, and that gets executed as a Test. 

I'd really like to have a similar abstraction right in the heart of JUnit 5. Right now Extensions seem to be either rather limited, or bound to the JUnit 5 Engine JUnit 5 Execution Context, because they depend on things being there like TestClasses / or methods, which might not exist for other engines.

**Comment by jlink** [comment]
The current design tries to balance the power of extensions, composability and the guarantees the JUnit 5 engine can give. JUnit4's statement approach was one of the things that made composition difficult. 

I'm not saying we made the best calls or that we won't change it. But I do believe there's no solution that will give us only benefits and       no drawbacks.

**Comment by bechte** [comment]
The JUnit5 engine was designed in that way, that the test execution is always guaranteed by the engine and cannot be changed. In this way, we can guarantee the execution flow and allow extension providers to build extension upon this contract.

For altering the test execution we do not yet provide a mechanism. One would be the resolver based discovery approach (see pull request #134) that would allow extension writers to contribute they own `TestDescriptor` logic to the test plan. It would require to use another annotation like `@RaceConditionTest` but actually, that would absolutely fit your needs for the race condition testing. One could also add another `TestDescriptor` for running EDT tests. If they require a very specific environment, then one might want to declare the test as `@SwingComponentTest` or whatever you name it, and let it be resolved to another specific `TestDescriptor` that handles this special case.

To me, all of your examples seem to be very specific use-cases which might not need to be composable and, therefore, are perfect candidates for `TestResolver`s.

@schauder : Please have a look and contact me if you have further questions. I am looking forward to getting your feedback. :smiley:

**Comment by schauder** [comment]
@jlink can you elaborate, how the statement approach makes composition difficult? I seem to experience the exactly opposite effect.

@bechte I read through the description of the pull request. Sounds great. I might find time tomorrow evening to actually look at the code.

**Comment by jlink** [comment]
Composing (nesting) statements only works if all statements do the exact right thing as of exception handling, ordering, calling before/after behaviour etc.; the difference between correct and incorrect can be subtle. The framework has no means to influence things from the outside. Thus it's easy to compose statements if you control all of them, but it becomes erratic as you compose unknown ones from different sources. 

One could of course introduce an extension point that takes an Executable of the test method only and returns a different Executable. My fear is that it would be abused for all kind of before/after/exception-handling stuff - just because it's so easy to do. And then we'd be in the same place as we were with JUnit4.

**Comment by schauder** [comment]
@jlink I'm probably missing something doing the "right thing" shouldn't be to difficult. The contract of statement in JUnit4 seemed to be rather simple and easy to follow. 

When filtering and ordering enter the mix I can understand your concerns, but as long as we follow a modified Mad Max principle: One statement goes in one statement goes out everything should be fine.

Filtering and ordering should be done by a separate part of the system to avoid any problems.

**Comment by jlink** [comment]
I don't think that the Mad Max principle is enough since you can do so many
(too many IMO) things with a statement that will break reasonable
assumptions about the normal behaviour.

I'm absolutely willing though, to rethink out extension mechanism. Let's
see what the others think.

2016-02-22 8:26 GMT+01:00 Jens Schauder <notifications@github.com>:

**Comment by marcphilipp** [comment]
Regarding execution in a different thread, we've discussed two alternatives this morning in a team call:

#### (1) Add a `TestExecutor` extension point

```java
interface TestExecutor extends ExtensionPoint {
    void execute(TestExtensionContext context, Executable executable);
}
```

#### (2) Add a `ExecutorProvider` extension point

```java
interface ExecutorProvider extends ExtensionPoint {
    Executor getExecutor(TestExtensionContext context);
}
interface Executor {
    void execute(Runnable runnable);
}
```

Either could be used to execute test methods in a different thread. However, in both cases `@BeforeEach` and `@AfterEach` methods and `BeforeEach`-/`AfterEachExtensionPoints` would still be executed in the "main" thread. Is that what you would want?

--- 

Regarding repeating tests, we think we should first get a grip on dynamic tests. Maybe repeating a test is just a dynamic test invocation.

**Comment by schauder** [comment]
As far as I can tell right now both variants should work for what I do with Rules.

I kind of agree with your statement about dynamic tests.

**Comment by jlink** [comment]
Running `@Before/AfterEach` (and other extension points) in a different
thread than the test itself can lead to subtle bugs concerning
synchronization of member variables and other shared state. If we want to
prevent all instance-based extension points would have to be covered by
this new one. This will make ordering of individual pieces of an extension
more difficult because there are no longer names for things like
`InstancePostProcessor` and `ExceptionHandler` etc.

Moreover, a working contract would require that returning from `execute`
must be synchronous and all exceptions thrown therein be rethrown during
exception point invocation.

2016-02-29 13:21 GMT+01:00 Jens Schauder <notifications@github.com>:

**Comment by sbrannen** [comment]
> Composing (nesting) statements only works if all statements do the exact right thing as of exception handling, ordering, calling before/after behaviour etc.; the difference between correct and incorrect can be subtle. The framework has no means to influence things from the outside. Thus it's easy to compose statements if you control all of them, but it becomes erratic as you compose unknown ones from different sources.
> 
> One could of course introduce an extension point that takes an Executable of the test method only and returns a different Executable. My fear is that it would be abused for all kind of before/after/exception-handling stuff - just because it's so easy to do. And then we'd be in the same place as we were with JUnit4.

@jlink, I couldn't have phrased it better myself! 

I share the exact same concerns and have for a long time: these are in fact the reasons that we opted _not_ to implement extensions in JUnit 5 using the _Chain of Responsibility_ pattern like JUnit 4's rules.

However, having said that, I do understand that some extensions may need to control/spawn the thread in which a test executes. To that end, something like a `TestExecutor` or `ExecutorFactory` extension should suffice.

*But...* at the very least we need to _guide_ developers to use the standard extensions and not abuse these _executor_ extensions.

**Comment by sbrannen** [comment]
Tentatively slated for 5.3 to be investigated in conjunction with #20.

**Comment by sbrannen** [comment]
FYI: I have reworded the title of this issue to make its purpose more clear to the casual observer.

**Comment by adamvoss** [comment]
> Either could be used to execute test methods in a different thread. However, in both cases @BeforeEach and @AfterEach methods and BeforeEach-/AfterEachExtensionPoints would still be executed in the "main" thread. Is that what you would want?

Would it be possible that an annotation on a test method would cause the just that method to run in the context, but an annotation of the class (fixture) itself would cause everything to execute in the context?

The case I'm looking at is basically interacting with JAAS security and wanting to [transparently] wrap tests in [`Subject.doAs`](https://docs.oracle.com/javase/10/docs/api/javax/security/auth/Subject.html#doAs(javax.security.auth.Subject,java.security.PrivilegedAction)) calls.  In this case it would be significant to be able to also be in the authenticated context for setup/teardown.

**Comment by AJNeufeld** [comment]
> However, in both cases @beforeeach and @aftereach methods and BeforeEach-/AfterEachExtensionPoints would still be executed in the "main" thread. Is that what you would want?

No, it isn't what I would want.

To "let a test execute in the Swing EDT Thread"([sic](https://en.wikipedia.org/wiki/RAS_syndrome)), you'd first have to set up the GUI for the test, then run the test, then tear down the GUI.  If you want several related tests, you'd want to factor out the set up and tear down code into separate methods, annotated with `@BeforeEach` and `@AfterEach` .  If these methods are not also run on the EDT, then since these methods are manipulating the Swing GUI, you must wrap the bodies of both of these methods in `SwingUtilities.invokeAndWait( )` wrappers, which further needs to be wrapped in a `try { ... } catch (InterruptedException | InvocationTargetException e) { ... }` block.

I suppose adding this wrapping to just these `@BeforeEach` and `@AfterEach` methods is better than having to add this wrapper to each and every `@Test` method, but to me it suggests that the `TestExecutor` should be able to influence the calls around the test as well.  An alternative might be adding `BeforeEachExecutor` and `AfterEachExecutor` extension points (as well as `BeforeAllExecutor` and `AfterAllExecutor` extension points?).

**Comment by adamvoss** [comment]
> Regarding execution in a different thread, we've discussed two alternatives this morning in a team call: `[...]`

It looks like there are actually 4 options from those for all the combinations of:

 1. `Executable` vs `Runnable`
 2. _Extension point as a provider_ vs _Extension point as the executor_

I don't currently have an opinion on which is better on the first question.

Regarding the second, I can't think any behaviors that would be possible with one but not the other.  My first thoughts are that the "extension point as the executor" would be preferable:

 - It is the simpler interaction model
 - It generates fewer questions about object ownership/use/lifetime:
     - For example, when will `getExecutor` be called and can callers cache `getExecutor` result?
     - Different extensions might make different assumptions here making it harder to compose the extension points.

**Comment by k1w1m8** [comment]
FYI, my understanding from the IDEA bug tracker is that this ticket is blocking full implementation of JUnit5 inside IDEA, and as a result, DynamicTests are impractical to use inside IDEA.

https://youtrack.jetbrains.com/issue/IDEA-193770

**Comment by awegmueller** [comment]
Is the TestExecutor/ExecutorProvider feature already on your roadmap? Are there any plans to implement it soon?

With our framework [Eclipse Scout](https://www.eclipse.org/scout/) we have very similar requirements to run tests in a framework specific _run context_ (= thread). Our current JUnit4 TestRunner wraps the original Statement with a Scout specific Statement that creates a RunContext and then executes the original Statement within a Scout thread/context. The main Thread blocks until the Scout thread has finished.

Since Scout is a client/server framework it requires Subject.doAs for authentication and uses thread locals to store information in a thread context. Thus it's crucial each test is executed in a Scout thread. So we'd really appreciate, if the proposal from Marc will be implemented (post from 29 Feb 2016).

Just to give you some background information: here is our current [PlatformTestRunner.java](https://github.com/eclipse/scout.rt/blob/releases/8.0.x/org.eclipse.scout.rt.platform.test/src/main/java/org/eclipse/scout/rt/testing/platform/runner/PlatformTestRunner.java), which is the base class of the ClientTestRunner and the ServerTestRunner. The important part is found in the #interceptMethodLevelStatement method, where a [SubjectStatement.java](https://github.com/eclipse/scout.rt/blob/releases/8.0.x/org.eclipse.scout.rt.platform.test/src/main/java/org/eclipse/scout/rt/testing/platform/runner/statement/SubjectStatement.java) is created. This class creates a Subject and runs the original Statement in a Scout thread (L62).

**Comment by marcphilipp** [comment]
@awegmueller Thanks for describing your use case in detail!

Your `PlatformTestRunner` currently wraps around the execution of rules, before/after methods, timeout/expected exception handling and the actual invocation of the test method.

The simplistic `TestExecutor` extension I proposed above was only intended to allow to execute the test method. We could add additional methods to the interface to allow to customize the execution of all parts, though.

```java
interface TestExecutor extends ExtensionPoint {
    void createTestInstance(ExtensionContext context, Executable executable);
    void executeBeforeAllMethod(ExtensionContext context, Executable executable);
    void executeBeforeEachMethod(ExtensionContext context, Executable executable);
    void executeExtensionCode(ExtensionContext context, Class<? extends Extension> extensionInterface, Class<? extends Extension> extensionClass, Executable executable);
    void executeTestMethod(ExtensionContext context, Executable executable);
    void executeAfterEachMethod(ExtensionContext context, Executable executable);
    void executeAfterAllMethod(ExtensionContext context, Executable executable);
}
```

Each of these could have the trivial default implementation of `executable.execute()`. Would you be able to deal with that, i.e. do what `SubjectStatement` does currently? Or would you need all of these things packed into a single `Executable`?

**Comment by marcphilipp** [comment]
Alternative design:

```java
interface UserCodeExecutor {
    default void execute(ExtensionContext context, UserCodeType userCodeType, Executable executable) throws Exception {
        executable.execute();
    }
}
enum UserCodeType {
    TEST_CLASS_CONSTRUCTOR,
    BEFORE_ALL_METHOD,
    ...
}
```

**Comment by awegmueller** [comment]
Hello Marc

Thanks a lot for the detailed analysis and your proposals! I am sorry my reply comes a bit late, but I was on holiday until today. However, we really like your first proposal (TestExecutor interface) and prefer that solution to the version that uses enums. This allows us to wrap each executable in a Scout RunContext/Subject again, as we have done it with JUnit 4. I guess this solution would also work for thread-starter @schauder who wanted to execute a test in the Swing thread.

Can you make any predictions in which JUnit release this will be implemented (if at all)?

**Comment by akozlova** [comment]
The suggested proposal would work for us as well, I like `TestExecutor` proposal more but one with enum would work as well. Any ETA when we can try it? Thanks

**Comment by marcphilipp** [comment]
Slightly modified proposal to allow multiple registered `ExecutionInterceptor` extensions:

```java
interface ExecutionInterceptor extends Extension {
    void createTestInstance(ExecutionContext context, Executable executable);
    void executeBeforeAllMethod(ExecutionContext context, Executable executable);
    void executeBeforeEachMethod(ExecutionContext context, Executable executable);
    void executeExtensionMethod(ExecutionContext context, Executable executable);
    void executeTestMethod(ExecutionContext context, Executable executable);
    void executeAfterEachMethod(ExecutionContext context, Executable executable);
    void executeAfterAllMethod(ExecutionContext context, Executable executable);
}
interface ExecutionContext {
    ExtensionContext getExtensionContext();
    Optional<Object> getTarget(); // empty for static methods
    Method getMethod();
    List<Object> getParameters();
}
```

**Comment by marcphilipp** [comment]
Another iteration that allows to inspect invocation results:

```java
interface InvocationInterceptor extends Extension {

    default <T> T createTestInstance(Invocation<T> invocation) throws Throwable {
        return invocation.proceed();
    }

    default void executeBeforeAllMethod(Invocation<Void> invocation) throws Throwable {
        invocation.proceed();
    }

    default void executeBeforeEachMethod(Invocation<Void> invocation) throws Throwable {
        invocation.proceed();
    }

    default <T> T executeExtensionMethod(Invocation<T> invocation) throws Throwable {
        return invocation.proceed();
    }

    default void executeTestMethod(Invocation<Void> invocation) throws Throwable {
        invocation.proceed();
    }

    default <T> T executeTestFactoryMethod(Invocation<T> invocation) throws Throwable {
        return invocation.proceed();
    }

    default void executeTestTemplateMethod(Invocation<Void> invocation) throws Throwable {
        invocation.proceed();
    }

    default void executeAfterEachMethod(Invocation<Void> invocation) throws Throwable {
        invocation.proceed();
    }

    default void executeAfterAllMethod(Invocation<Void> invocation) throws Throwable {
        invocation.proceed();
    }

    interface Invocation<T> {
        T proceed() throws Throwable;
        ExtensionContext getExtensionContext();
        Class<?> getTargetClass();
        Optional<Object> getTarget(); // empty for static methods
        Executable getExecutable();
        List<Object> getArguments();
    }
}
```

**Comment by marcphilipp** [comment]
Updated once again to add support for intercepting dynamic tests and to increase consistency with other `Extension` subinterfaces:

```java
import java.lang.reflect.Executable;
import java.util.List;
import java.util.Optional;

interface InvocationInterceptor extends Extension {

    default <T> T createTestInstance(ReflectiveInvocation<T> invocation, ExtensionContext extensionContext) throws Throwable {
        return invocation.proceed();
    }

    default void executeBeforeAllMethod(ReflectiveInvocation<Void> invocation, ExtensionContext extensionContext) throws Throwable {
        invocation.proceed();
    }

    default void executeBeforeEachMethod(ReflectiveInvocation<Void> invocation, ExtensionContext extensionContext) throws Throwable {
        invocation.proceed();
    }

    default <T> T executeExtensionMethod(ReflectiveInvocation<T> invocation, ExtensionContext extensionContext) throws Throwable {
        return invocation.proceed();
    }

    default void executeTestMethod(ReflectiveInvocation<Void> invocation, ExtensionContext extensionContext) throws Throwable {
        invocation.proceed();
    }

    default <T> T executeTestFactoryMethod(ReflectiveInvocation<T> invocation, ExtensionContext extensionContext) throws Throwable {
        return invocation.proceed();
    }

    default void executeTestTemplateMethod(ReflectiveInvocation<Void> invocation, ExtensionContext extensionContext) throws Throwable {
        invocation.proceed();
    }

    default void executeDynamicTest(Invocation<Void> invocation, ExtensionContext extensionContext) throws Throwable {
        invocation.proceed();
    }

    default void executeAfterEachMethod(ReflectiveInvocation<Void> invocation, ExtensionContext extensionContext) throws Throwable {
        invocation.proceed();
    }

    default void executeAfterAllMethod(ReflectiveInvocation<Void> invocation, ExtensionContext extensionContext) throws Throwable {
        invocation.proceed();
    }

    interface Invocation<T> {
        T proceed() throws Throwable;
    }

    interface ReflectiveInvocation<T> extends Invocation<T> {
        Class<?> getTargetClass();
        Optional<Object> getTarget(); // empty for static methods
        Executable getExecutable();
        List<Object> getArguments();
    }
}
```

**Comment by sbrannen** [comment]
Starting to remind me of AspectJ's [`ProceedingJoinPoint`](https://www.eclipse.org/aspectj/doc/next/runtime-api/org/aspectj/lang/ProceedingJoinPoint.html), with `proceed`, `getArgs`, `getSignature`, `getTarget`, etc. 😉

**Comment by marcphilipp** [comment]
WIP: https://github.com/junit-team/junit5/compare/issues/157-invocation-interceptor
