### ISSUE TITLE
junit-json-params

### ISSUE THREAD

**Issue by joshka** [junit-team/junit5#1571]
## Overview

I was thinking about the CsvSource a while back and how JSON is sometimes a more convenient / expressive format to write data in, particularly when dealing with the input and output of web based APIs. So I created a small library, [junit-json-params](https://github.com/joshka/junit-json-params), which achieves this.

I'm wondering whether this is something that would be considered for being added to the JUnit project? If not, commenting here mainly for a little visibility on the library (and a call out for ideas to make this better).

**Comment by sbrannen** [comment]
Hi @joshka,

The team has also considered support for JSON with parameterized tests in the past.

The main reason we have not implemented any such support is that it would pull in one or more dependencies on third-party artifacts, and that's something that violates one of the core principles of JUnit.

The CSV support naturally pulls in a third-party library for parsing the CSV format; however, by _shadowing_ that dependency into JUnit, we are able to make that support transparent to end users.

With the JSON support you have implemented, it would not be possible to make the dependency on the third-party JSON library transparent since your extension supports injection of those third-party types into user code.

With that in mind, I agree with @nicolaiparlog that _JUnit Pioneer_ would be better suited for hosting such an extension.

In addition, to increase visibility for your extension, please add a link to it in the [Third Party Extensions](https://github.com/junit-team/junit5/wiki/Third-party-Extensions) wiki page.

Also, if you tweet about it and mention the `@junitteam`, we'd be happy to retweet that.

**Comment by sbrannen** [comment]
For anyone interested in support for mapping from JSON onto custom domain objects, you might find this (outdated) extension useful:

https://github.com/hpgrahsl/junit5-paramtests-json

**Comment by sormuras** [comment]
I agree with Sam and added the "3rd-party: pioneer" label.

**Comment by sbrannen** [comment]
**Team Decision**:

In light of the above, we are closing this issue.

**Comment by sbrannen** [comment]
> For discoverability, both those are worth adding to the README and User Guide for some greater visibility. 

Feel free to create an issue to track it or submit a PR.

> Is there a mailing list for JUnit5, or has that died away?

No. We don't have a mailing list.

But we do have Stack Overflow and Gitter.

- https://stackoverflow.com/questions/tagged/junit5
- https://gitter.im/junit-team/junit5
