### ISSUE TITLE
AssertAll#assertAll() is not threadsafe

### ISSUE THREAD

**Issue by flowerrrr** [junit-team/junit5#1591]
When using `AssertAll.assertAll()` with parallelStreams the concurrent adding of Throwables to the list of failures might lead to unexpected null-elements in the list of failures resulting in a NullPointerException in the constructor of MultipleFailuresError.

Solution: Use synchronized list.

`        List<Throwable> failures = Collections.synchronizedList(new ArrayList<>());
`

**Comment by flowerrrr** [comment]
@jbduncan : In my case i'd like to execute the stream in parallel for performance reasons.

**Comment by jbduncan** [comment]
Ah okay, thanks for explaining @flowerrrr. However, that leaves me with a few questions:

1. Are you at liberty to explain to us why you're trying to improve the performance this way, or otherwise what your use case is?
2. I wonder, wouldn't using a synchronized list cause the potential performance benefit of using a parallel stream to disappear due to the locking involved?
3. AFAICT, if you pass in a parallel stream of executables, then the order of those executables would be non-deterministic. Would this non-determinism be okay for you? Or an I missing something here?

**Comment by flowerrrr** [comment]
@jbduncan: 
1. Test was written before the new parallel test support of junit 5 was released. So i thought using AssertAll gives me a handy way to run my tests in parallel.
2. The performance impact is virtually zero as only in case of an assertion error an element is added to the synchronized list of failures. 
3. Non-deterministic is ok.

If an API supports streams it should also work if used with parallel streams - or, if for some reason it does not support parallel streams, it should be stated in the documentation of the API.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
@flowerrrr I pushed a fix to `master. Please try out the latest 5.4-SNAPSHOT (using [Sonatype's snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/)).
