### ISSUE TITLE
ConsoleRunner uses wrong indentation for failed grouped test

### ISSUE THREAD

**Issue by rherrmann** [junit-team/junit5#160]
If a test like this fails
```java
@Test
public void testNames() throws Exception {
  Person person = new Person();
  
  assertAll( "names", () -> {
    assertEquals( "John", person.getFirstName() );
    assertEquals( "Doe", person.getLastName() );
  } );
}
```

... the ConsoleRunner uses the wrong indentation like shown below. It seems that the `expected` line is indented with a single tab whereas the line above uses spaces.
```
Finished:    testNames [junit5:com.codeaffine.junit5.GroupAssertionsTest#testNames()]
             => Exception: names (1 failure)
	expected: <John> but was: <something else>
```

**Comment by lutovich** [comment]
Hello, I'd love to help with this issue. A bit unsure about the proper solution, though.
Message with `\n\r` comes from `org.opentest4j.MultipleFailuresError#getMessage()` which is in a separate repo. It is possible to fix indentation in junit-console using some `#replaceAll()` magic like [here](https://github.com/lutovich/junit5/commit/6d413a7b97f7a7893d5cfa1a729963a528e761ee).

Is this an ok solution? If so I'll cleanup the code and make a PR, otherwise happy to implement a suggested solution.

**Comment by marcphilipp** [comment]
Since other error messages might also contain line breaks, I think it's an ok solution.

@junit-team/junit-lambda Any objections?

**Comment by mmerdes** [comment]
No objections

Cheers,
Matthias

Marc Philipp <notifications@github.com> schrieb am Mo., 18. Apr. 2016 um
22:49:

**Comment by sbrannen** [comment]
No objections.

**Comment by sbrannen** [comment]
> If so I'll cleanup the code and make a PR

Go for it!

**Comment by marcphilipp** [comment]
+1

**Comment by lutovich** [comment]
Thanks for the feedback. Submitted a PR.
