### ISSUE TITLE
Use Deptective to ensure module-internal constraints

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1720]
Move cyclic dependency checks from very late in the game integration tests to early compile time checks using https://github.com/moditect/deptective

**Comment by marcphilipp** [comment]
While deptective looks interesting, it seems one needs to list every package along with all of its allowed dependencies. Maintaining such a file manually seems tedious. I guess we could generate it somehow... 🤔

**Comment by sormuras** [comment]
True. It should easier to maintain than https://github.com/junit-team/junit5/blob/master/platform-tooling-support-tests/src/test/java/platform/tooling/support/tests/PackageCyclesDetectionTests.java is.

**Comment by gunnarmorling** [comment]
Thanks a lot or taking the initiative to explore the usage of Deptective!

> Maintaining such a file manually seems tedious.

Yes, so one of the next things we're planning to work on is to provide more abstract means of describing the "components" of your architecture than individual packages. That'd mean less effort for configuring Deptective, provided you can identify such components in your architecture, i.e. a group of packages that you'd like to consider as one single unit.

> I guess we could generate it somehow...

You already can do this by specifying the `-Adeptective.mode=ANALYZE` [configuration option](https://github.com/moditect/deptective#configuration-options). This will create the Deptective descriptor representing your current actual package relationships. You can take this as a starting point for describing your architecture; if all your actual relationships are 100% what you'd like to have, then you'd take that descriptor as is. Otherwise, you'd adjust it, e.g. by removing unwanted relationships from it. Then, when validating your actual code against the descriptor, this unwanted relationship would fail the build, as would any new relationship you establish in the future and which is not part of the model yet. Needless to say that constantly re-creating the configuration doesn't make sense, as you'd just validated your actual architecture against itself.

Very happy to help in case you run in any issues with Deptective and also very eager to learn about your findings from applying it to this code base. Any insights gained will surely help us to advance the project.

**Comment by gunnarmorling** [comment]
>  It should easier to maintain than PackageCyclesDetectionTests.java

There's currently no support in Deptective for checking on package cycles. The idea more is to describe an intended architecture (currently in terms of packages, going forward in terms of more higher-level constructs, see above) and match the code base against that. Implicitly this would also detect cycles if you have defined your target architecture in a cycle-free way.

That being said, we may consider to add a simple "prevent cycles" check, too, as it seems to be a common demand.

**Comment by gunnarmorling** [comment]
Hey @sormuras et al., we've made some progress with cycle checking in Deptective. So if you like, you could give this a try now (by getting the latest SNAPSHOT from JitPack). Essentially, you'd have to add the following to your _pom.xml_:

```
<repositories>
    <repository>
        <id>jitpack</id>
        <name>Jitpack</name>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <fork>false</fork>
        <showWarnings>true</showWarnings>
        <compilerArgs>
            <arg>-Xplugin:Deptective</arg>
            <arg>-Adeptective.mode=ANALYZE</arg>
            <arg>-Adeptective.visualize=true</arg>
            <arg>-Adeptective.whitelisted=*ALL_EXTERNAL*</arg>
            <arg>-Adeptective.cycle_reporting_policy=ERROR</arg>
        </compilerArgs>
        <annotationProcessorPaths>
            <path>
                <groupId>com.github.moditect.deptective</groupId>
                <artifactId>deptective-javac-plugin</artifactId>
                <version>master-SNAPSHOT</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
```

This will fail the build if it spots any package cycles (on JDK 11 that is, on JDK 8 I noticed this only creates a warning for some reason, that's logged as https://github.com/moditect/deptective/issues/41). It also creates a DOT file with the package relationships and a _deptective.json_ file representing the current state of your architecture. If you wanted, you could take this (possibly removing some relationships if you think they shouldn't be there) and then validate the code base against that architecture definition. Any accidentally added relationships would fail the build in the future. If the architecture definition gets too overwhelming, you could also group multiple packages into "components" (see the Deptective README for the details), which reduces the number of nodes in the architecture and may help to keep things manageable.

I'd be very happy about any feedback you may have. If you like the idea in general and would be willing to use this for your build going forward, I could also cut a proper release and push it to Maven Central.

**Comment by sormuras** [comment]
Hi @gunnarmorling -- pardon the very late reply. I didn't have the cycles to move our existing and running cyclic dependency check to Deptective. And I don't see much time slot in the near future and tend to revisit this issue/task only if the existing checks fails to work. Therefore, I'll close this issue for now.
