### ISSUE TITLE
Introduce assertion support for object properties of a common type

### ISSUE THREAD

**Issue by ptjuanramos** [junit-team/junit5#1765]
Imagine that you have an object and you want to assert every property for String.EMPTY value. Instead of using all getters of that object, isn't it a good idea to you guys to implement a new feature for getting all getter methods by using reflection and assert them?

For example:

```java
// Object with several properties
DummyObj dummyObj = // ...

// In a method that returns String.class, assert the result with a empty string
Assertions.assertPropertiesEquals(dummyObj, String.class, "");
```

**Comment by sbrannen** [comment]
Hi @ptjuanramos,

Since we aim to maintain a minimal set of built-in assertions, I don't foresee JUnit Jupiter introducing assertions along those lines. 

Have you considered using AssertJ's `extracting(...)` support as documented on the page below?

http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#extracted-properties-assertion

**Comment by pauldingemans** [comment]
@sbrannen I propose to close this issue. It now has been open for more than a year without getting feedback from @ptjuanramos.

**Comment by sbrannen** [comment]
In line with other team decisions (see https://github.com/junit-team/junit5/issues/1920#issuecomment-499841520), we will not include the proposed assertions in JUnit Jupiter.
