### ISSUE TITLE
Discovery request resolver: apply class (name) filter by default

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1835]
The `EngineDiscoveryRequestResolver` introduced in `1.5.0-M1` should apply _class name_ and _class instance_ filter by default.

## Deliverables

- [ ] Find an appropriate way to pass filter predicate(s) when creating a `EngineDiscoveryRequestResolver` builder.

**Comment by marcphilipp** [comment]
After some internal discussion we've come to the conclusion that applying the class filter by default would add more complexity instead of simplifying things. The main reason for that is that the Jupiter engine does not apply it to nested classes so we'd have to make it configurable etc. Thus, I'm closing this issue for now.
