### ISSUE TITLE
Need a global extension that run once in test lifecycle

### ISSUE THREAD

**Issue by kamit78** [junit-team/junit5#1843]
Right now there is no extension that can be used to run once in the lifecycle of test execution like IExecutionListner in testng which can used to configure or prepare test environment 

There should be @GlobalBeforeAllCallback that runs before all and once in test lifecycle

**Comment by sormuras** [comment]
You may resort to [`TestExecutionListener`](https://junit.org/junit5/docs/current/api/org/junit/platform/launcher/TestExecutionListener.html) as described here: https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-custom

If there was such an extension in Jupiter, you only would wrap the test executed by the Jupiter engine.

**Comment by kamit78** [comment]
Thanks it is working but one other thing that I have noticed is that Launcher execute all classes in a given package instead of define in selectClass() ``

As per below snippet, it should launch test from classes matched with pattern ".*Launcher*" but it is executing test from all classes in PlayGround package


```
public class CustomLauncherExample {

    public static void main(String[] args) {

        LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
                .selectors(selectPackage("PlayGround"))
                .selectors(selectClass(".*Launcher*"))
                .build();

        Launcher launcher = LauncherFactory.create();
        SummaryGeneratingListener summaryGeneratingListener = new SummaryGeneratingListener();
        launcher.registerTestExecutionListeners(new TestExecutionListenerExample());
        launcher.registerTestExecutionListeners(summaryGeneratingListener);
        launcher.execute(request);
        System.out.println(summaryGeneratingListener.getSummary().getContainersSucceededCount());

    }
}
```

**Comment by sbrannen** [comment]
`selectClass(String)` selects a single class by its fully qualified class name, as per the documentation.

If you want to filter within the selected classes (e.g., those selected within a certain package), you have to provide a filter as demonstrated in the [User Guide](https://junit.org/junit5/docs/current/user-guide/#launcher-api-execution).

```java
LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
    .selectors(selectPackage("PlayGround"))
    .filters(includeClassNamePatterns(".*Launcher*"))
    .build();
```

Since it seems you have a solution, I am closing this issue.

**Comment by kamit78** [comment]
Hi,
It is not working as expected....
Actually it runs single class that match pattern not all classes with matched patterns.

```
LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
    .selectors(selectPackage("PlayGround"))
    .filters(includeClassNamePatterns(".*Launcher*"))
    .build();
```

**Comment by sbrannen** [comment]
It feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
