### ISSUE TITLE
Remove parentheses when generating display name with ReplaceUnderscores

### ISSUE THREAD

**Issue by juliette-derancourt** [junit-team/junit5#1875]
I don't know if this has already been discussed, but I noticed something when I discovered the display name generation (which is a cool feature btw!).

When using `ReplaceUnderscores` as a [DisplayNameGenerator](https://github.com/junit-team/junit5/blob/c4ccb87c6afd33e5a09414dd8bb26728d890a684/junit-jupiter-api/src/main/java/org/junit/jupiter/api/DisplayNameGenerator.java), we can witness the following behavior:

```java
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
class SomeTest {

    @Test
    void this_is_a_test() {
        // ...
    }

    @ParameterizedTest
    @CsvSource({"a, b"})
    void this_is_a_test_with_arguments(String a, String b) {
        // ...
    }

}
```

IDE output:

<img width="243" alt="tests" src="https://user-images.githubusercontent.com/28359762/57570951-df369480-7407-11e9-9934-0baecd21371d.PNG">

In the first case, I would suggest removing the extra parentheses in the output, as it brings nothing but noise, IMO.

In the second one I'm not sure. Personally I would remove them too, but then we would lose the information about the parameters (I don't know if we really need it though?). Maybe at least put a space between the end of the name and the opening bracket? (Sorry I'm a bit picky ahah)

Tell me what you think! I'd be happy to do it if you agree :)

**Comment by sbrannen** [comment]
Tentatively slated for 5.5 M2 for _team discussion_

**Comment by sbrannen** [comment]
> In the first case, I would suggest removing the extra parentheses in the output, as it brings nothing but noise, IMO.

In general, the idea behind it was consistency and simplicity (in terms of the implementation).

But... I suppose the empty parentheses are a bit superfluous for that use case.

> In the second one I'm not sure. Personally I would remove them too, but then we would lose the information about the parameters (I don't know if we really need it though?). Maybe at least put a space between the end of the name and the opening bracket? (Sorry I'm a bit picky ahah)

Hmmm.... I'd say we should definitely display the parameters if a display name is overloaded.

Unfortunately, a `DisplayNameGenerator` doesn't really have a way to determine if a display name is overloaded (i.e., used multiple times) within a given test class. Note: I am not talking about whether or not a test method is overloaded, because they could have different custom display names.

Thus, I am leaning toward continuing to display the parameter list.

Let's see what the rest of the team thinks.

**Comment by juliette-derancourt** [comment]
> Hmmm.... I'd say we should definitely display the parameters if a display name is overloaded.

Oh yeah you're totally right, I did not think of this case!

About that, I have a (kinda) unrelated question: why display the parameter's type and not its name? Was it a deliberate choice? Because in some cases — mostly with primitives — it doesn't really help understand the role of the parameters...

**Comment by sbrannen** [comment]
> About that, I have a (kinda) unrelated question: why display the parameter's type and not its name? Was it a deliberate choice? Because in some cases — mostly with primitives — it doesn't really help understand the role of the parameters...

It was a deliberate choice. The parameter types help to disambiguate between overloaded methods (i.e., methods with the same name). Displaying the names of the parameters would not guarantee that, since two variants of the same overloaded method could be declared with the same parameter names (for different types).

Furthermore, there is no guarantee that JUnit can access the actual parameter names at runtime. JUnit could only access them if the code is compiled with the `-parameters` compiler flag. Otherwise, names are in the format of `arg0`, `arg1`, etc. in the byte code, which is not meaningful.

**Comment by juliette-derancourt** [comment]
> It was a deliberate choice. The parameter types help to disambiguate between overloaded methods (i.e., methods with the same name). Displaying the names of the parameters would not guarantee that, since two variants of the same overloaded method could be declared with the same parameter names (for different types).

> Furthermore, there is no guarantee that JUnit can access the actual parameter names at runtime. JUnit could only access them if the code is compiled with the -parameters compiler flag. Otherwise, names are in the format of arg0, arg1, etc. in the byte code, which is not meaningful.

Hmm I see, that makes complete sense indeed. Thanks for the explanation!

So based on what you said, the only possible improvement would be:

`this_is_a_test()` => `this is a test`
`this_is_a_test_with_arguments(String a, String b)` => `this is a test with arguments (String, String)`

**Comment by sbrannen** [comment]
> So based on what you said, the only possible improvement would be:
> 
> `this_is_a_test()` => `this is a test`
> `this_is_a_test_with_arguments(String a, String b)` => `this is a test with arguments (String, String)`

Correct 👍

**Comment by marcphilipp** [comment]
I think omitting parentheses for empty argument lists in the ReplaceUnderscores display name generator as proposed above makes sense.

@juliette-derancourt Would you be interested in submitting a PR?

**Comment by juliette-derancourt** [comment]
@marcphilipp I'd be glad to!
