### ISSUE TITLE
Remove TestId class in favor of String in TestIdentifier

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#189]

**Comment by sbrannen** [comment]
The PR looks good to me. Any reason you're holding off on merging it?

**Comment by marcphilipp** [comment]
Just wanted one of you to review. ;-)

**Comment by jlink** [comment]
I had the wrong assumption that you had already merged it. My changes from
this morning are probably in conflict with your PR :-/

Go ahead with merging as soon as you can. Spreading UniqueID will otherwise
cause a lot of merging effort.

2016-03-14 13:56 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by marcphilipp** [comment]
@jlink Done!
