### ISSUE TITLE
Introduce API to select and execute individual tests in inherited nested classes

### ISSUE THREAD

**Issue by chrisvest** [junit-team/junit5#1913]
Such an API is necessary for tools to be able to run individual tests, when such tests are defined in a nested class of a (possibly abstract) super-class of the test class. See:

* https://youtrack.jetbrains.com/issue/IDEA-195373
* https://youtrack.jetbrains.com/issue/IDEA-215440

## Deliverables

I won't pretend to know how this should be done. Perhaps @akozlova has ideas.

**Comment by sbrannen** [comment]
It's already possible to execute such individual tests via their unique ID.

For example, if I right-click on the test method from the linked IDEA issue, Eclipse properly executes the test method by selecting its unique ID:

`[engine:junit-jupiter]/[class:org.example.FirstConcreteTest]/[nested-class:NestedTests]/[method:myTest()]`

In other words, that works in Eclipse and should be supported in IDEA as well.

So, I suppose what you're requesting is the ability to select such a method via a new dedicated factory method in `DiscoverySelectors` that accepts the following.

- enclosing class: `"org.example.FirstConcreteTest"` (or `org.example.FirstConcreteTest.class`)
- nested class: `"org.example.TemplateTest.NestedTests"` (or `TemplateTest.NestedTests.class`)
- method name: `"myTest"`
- method parameters: `""` (empty)

@chrisvest and @akozlova, is that what you have in mind?

**Comment by sbrannen** [comment]
I forgot to mention that I had to move `FirstConcreteTest` to its own source file to make the above selection by unique ID work in Eclipse.

I imagine that's just an issue with Eclipse and not with JUnit itself, but I honestly didn't investigate that further.

**Comment by akozlova** [comment]
How does Eclipse compose this unique id? My request was to have a dedicated discovery selector for this case indeed

**Comment by sbrannen** [comment]
> How does Eclipse compose this unique id?

Sorry. I misspoke. What I meant to say was:

If I execute the test class and then **right-click on the test method entry in the test results UI to re-run it**, Eclipse properly executes the test method by selecting its unique ID that it obtained from the `TestIdentifier`.

> My request was to have a dedicated discovery selector for this case indeed

OK. Thanks for confirming that.

**Comment by sbrannen** [comment]
> So, I suppose what you're requesting is the ability to select such a method via a new dedicated factory method in `DiscoverySelectors` that accepts the following.
> 
> - enclosing class: `"org.example.FirstConcreteTest"` (or `FirstConcreteTest.class`)
> - nested class: `"org.example.TemplateTest.NestedTests"` (or `TemplateTest.NestedTests.class`)
> - method name: `"myTest"`
> - method parameters: `""` (empty)

We would actually need to ensure that the selector supports arbitrary levels of nested test classes. So we'd probably need to accept a varags array or list for the nested classes.

**Comment by sbrannen** [comment]
Tentatively slated for the 5.6 backlog

**Comment by marcphilipp** [comment]
Related to #1954.

**Comment by marcphilipp** [comment]
## API Proposal

Add the following methods to `DiscoverySelectors` for nested classes:

- `selectNestedClass(List<String> enclosingClasses, String nestedClass)`
- `selectNestedClass(List<String> enclosingClasses, String nestedClass)`

... and for methods:

- `selectNestedMethod(List<String> enclosingClasses, String nestedClass, String methodName)`
- `selectNestedMethod(List<String> enclosingClasses, String nestedClass, String methodName, String methodParameterTypes)`
- `selectNestedMethod(List<Class<?>> enclosingClasses, Class<?> nestedClass, String methodName)`
- `selectNestedMethod(List<Class<?>> enclosingClasses, Class<?> nestedClass, String methodName, String methodParameterTypes)`
- `selectNestedMethod(List<Class<?>> enclosingClasses, Class<?> nestedClass, Method method)`

@junit-team/junit-lambda WDYT?

**Comment by jbduncan** [comment]
@marcphilipp I'm trying to understand why one would want to pass in multiple `enclosingClasses` to these methods rather than just one, and I wondered if you could clarify things for me? :thinking:

**Comment by sbrannen** [comment]
> @marcphilipp I'm trying to understand why one would want to pass in multiple `enclosingClasses` to these methods rather than just one, and I wondered if you could clarify things for me? 🤔

If an enclosing class is an inner class, that enclosing class can be inherited by multiple classes that extend the parent type of the enclosing class, meaning that there can be multiple _paths_ to leaf inner class. Consequently, we need the _full path_ to the leaf inner class in order to be able to proper disambiguate it from other sibling leaves.

**Comment by jbduncan** [comment]
@sbrannen Ahh, okay. So am I right to understand that the list of `enclosingClasses`s is just a _path_ that helps JUnit 5 understand where an inner class is located?

For example, if we had an inner class `ParentClass.ChildInnerClass.GrandchildInnerClass`, then the `enclosingClasses` would be `[ParentClass.class, ChildInnerClass.class]`, and this would tell JUnit 5 which classes to traverse to find the `GrandchildInnerClass` were interested in (rather than say a different inner class with the same name such as `Foo.Bar.GrandchildInnerClass`)...

...and to give another example, if we had a class `HelloWorldGreeter` which extends `Greeter`, then by passing an `enclosingClasses` of `[Greeter.class]`, JUnit 5 would know to search for the version of `nestedClass` inside `Greeter` rather than `HelloWorldGreeter`.

Is my understanding correct, or am I barking up the wrong tree here?

**Comment by marcphilipp** [comment]
Yes, that‘s correct. Unfortunately the term classpath is already taken. 😉

**Comment by jbduncan** [comment]
@marcphilipp Ah, of course. I can see now why you chose the name `enclosingClasses` rather than `classpath`. :wink:

**Comment by marcphilipp** [comment]
**Team Decision:** Let's go with the above API proposal.
