### ISSUE TITLE
Feature request: Allow Abstract parameter resolver

### ISSUE THREAD

**Issue by geraldo-netto** [junit-team/junit5#1943]
Dear Friends,

May I suggest to allow the parameter resolver class to be abstract?

Here is my scenario:
I have a single parameter resolver for the whole project (200+ integration tests)
But a few days ago, I was required to add a 'follow redirect' parameter on jersey
but just for one very specific class of integration tests

The thing is that parameter resolver is shared among all integration test classes
and because parameter resolver is not 'aware' of integration test classes it is been reflected on, I cannot control the behaviour without playing with additional parameter resolvers instead of making a single abstract parameter resolver that I can extend and customise the behaviour

I have tried to make my parameter resolver abstract to prove this idea
But because JUnit uses reflection, I've got InstanciationException

So, my current/quick workaround was to copy and paste the original parameter resolver
to another class with the customisations I need and change the @ExtendsWith() to point to this specific parameter resolver of this specific set of integration tests that are requiring it

Thank You Very Much/Kind Regards,
Geraldo Netto

**Comment by sbrannen** [comment]
Hi @geraldo-netto,

Thanks for reaching out to us with your proposal.

Since JUnit Jupiter must use the standard reflection APIs in Java to instantiate any extension registered via `@ExtendWith`, such classes simply must be concrete (i.e., not `abstract`).

In light of that, I am closing this issue.

You can, however, introduce your own abstract base class that implements `ParameterResolver` and other extension APIs and then extend that base class for specific purposes. You will then need to register the concrete implementations via `@ExtendWith` or `@RegisterExtension`.
