### ISSUE TITLE
Publish JUnit Jupiter Assertions as a separate artifact

### ISSUE THREAD

**Issue by bhchandra** [junit-team/junit5#1955]
AssertJ and Truth are a couple of alternatives which provide fluent assertions.
Assertions provided by JUnit are part of the core `junit-jupiter-api` module.

It would be great if the Assertions are moved into a separate sub-module/module, so that they can be excluded in the dependencies, and provide a better auto complete IDE experience.

## Deliverables

- [ ] Reorganize Assertions into it's own module

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M1 for _team discussion_

**Comment by marcphilipp** [comment]
I'm afraid that would require us to change the package name as well to avoid issues with split packages.

**Comment by sbrannen** [comment]
> I'm afraid that would require us to change the package name as well to avoid issues with split packages.

Indeed, split packages basically make it a no-go. 🙁

**Comment by marcphilipp** [comment]
**Team Decision:** Since we'd have to move it to a different package and deprecate the old class, we've decided to not make it a separate artifact. As a workaround for your use case, IDEs usually allow to exclude classes from suggested imports, [e.g. in IntelliJ](https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#exclude-classes-and-packages-from-auto-import).

**Comment by sbrannen** [comment]
> [e.g. in IntelliJ](https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#exclude-classes-and-packages-from-auto-import).

In Eclipse you can filter out types via Preferences -> Java -> Appearance -> Type Filters.

**Comment by bhchandra** [comment]
Thank you for your quick response.

**Comment by nightswimmings** [comment]
I beg for supporting this feature, so there is an easy way to pick a single assertions framework...
