### ISSUE TITLE
TestExecutionResult parameter not resolved on AfterEach

### ISSUE THREAD

**Issue by knoobie** [junit-team/junit5#1966]
## Steps to reproduce

```java
class SayHelloWorldTest {
  
  @Test
  void sayHelloWorldTest() {
    System.out.println("Hello World");
  }

  @AfterEach
  public void afterEachTest(TestInfo testInfo, TestExecutionResult result) {
    System.out.println(testInfo + "  " + result);
  }
}
```

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.5
 - Build Tool/IDE: Intellij / Maven

## Result

```
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [org.junit.platform.engine.TestExecutionResult arg1] in method [public void SayHelloWorldTest.afterEachTest(org.junit.jupiter.api.TestInfo,org.junit.platform.engine.TestExecutionResult)]
```

## Expectation

- TestExecutionResult can be resolved on Methods annotated with `@AfterEach` containing the information of the last method run

**Comment by sbrannen** [comment]
`TestExecutionResult` cannot be supplied to an `@AfterEach` method since the `@AfterEach` method itself (or another `@AfterEach` method) could cause an otherwise successful test execution to fail, which would therefore require mutation of the state of the immutable `TestExecutionResult`.

If you want to find out if a particular test succeeded or failed, you need to implement the `TestWatcher` extension API.

I am therefore closing this issue.
