### ISSUE TITLE
Getting the values of parameters for ParameterizedTests in TestExecutionListener

### ISSUE THREAD

**Issue by drodriguezhdez** [junit-team/junit5#1969]
On method execution of `executionStarted(...)`, `executionFinished(...)` in the `TestExecutionListener` class, it seems it's not possible to get the value of the parameters for `ParameterizedTest`, but using `displayName` attribute in the `TestIdentifier`. 

**Feature request**: Add the capability to have `parameters` to the `TestIdentifier` class in order to obtain those values.

*Related to*: https://stackoverflow.com/questions/56319857/getting-the-values-of-parameters-for-parameterizedtests-in-testexecutionlistener

**Comment by marcphilipp** [comment]
Related to #944.

**Comment by marcphilipp** [comment]
Tentatively slated for 5.6 Backlog for _team discussion_.

**Comment by dkessel** [comment]
It would be great to have this in a future update to JUnit 5. We are just starting to integrate JUnit 5 (we have a large test codebase with lots of junit 3 and junit 4 tests). And if I understand correctly, this might in the end also fix the problem that no method names are reported at all for "old" parameterized tests executed using junit vintage.

**Comment by EinMatt** [comment]
Hello, I would like to add my fair share to this.

I do have a usecase for this that would help me personally a lot, and could also improve some other places for other people:

I am using the [Zephyr Scale Cloud API](https://support.smartbear.com/zephyr-scale-cloud/api-docs/#section/Introduction) in combination with the TestWatcher (I dunno if the TestExecutionListener Class has different abilities) to automatically upload some metadata of custom annotations to my Zephyr Scale Test Cases. 

I'm using some annotations on class level, and method level to add information regarding the test, and its automatically uploaded into my test management plattform.

e.g. this is what it looks like currently when its automatically uploaded into my test management system:
![Image](https://github.com/user-attachments/assets/f0ed4b5e-5360-4df9-91d6-f563482dfa7b)


if there was a way to get the data / input used for the parameterized tests, it would mean I could automatically show what is tested in this exact execution. 

I already resolve the "index" from the display name, meaning [1], [2] and [3], example:

![Image](https://github.com/user-attachments/assets/ebd3c85d-bd5f-43dc-b1a0-4a4da28a52d5)

here I could also get the data used, e.g. 1, 2 / 2, 3 / 3, 4

but this can lead to errors if I want to customize my display name - a display name should never be the place where I parse some stuff to get additional data. 

I already have to customize a display name because otherwise my index reading would be broken here:
![Image](https://github.com/user-attachments/assets/c04563e6-e25d-4eac-ad09-58376eeaba73)

also, for some annotations and test data sets, this will never work from the display name,

e.g. NullAndEmptySource - null is shown in the display name, but empty is just, well, empty. So I cannot resolve anything there.
![Image](https://github.com/user-attachments/assets/d951f76e-088b-43ef-b6b4-1f81eb9e8b7c)

this is what the display name looks like - there is nothing to resolve here:
![Image](https://github.com/user-attachments/assets/62be5774-0f26-4e5c-a50d-038fda8a8062)

so for me, it would be nice if there was a way to not only get the actual input data used in a seperate way (I dunno how empty strings, blank strings, certain control characters would work), but also to get the "index" of the parameterized test aswell.

**Comment by marcphilipp** [comment]
@EinMatt You can access the arguments by implementing `InvocationInterceptor` in addition to `TestWatcher` as described in https://github.com/junit-team/junit5/issues/944#issuecomment-2497070023
