### ISSUE TITLE
Introduce declarative mechanism for failing a test if it does not throw an exception

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#2023]
Annotation based Assumptions, e.g.
```
@Test
@Assumption(failOnPass=true)
```
So that we don't have to rewrite all the assumeThat's to assertThat's and perhaps more importantly so that all test frameworks (assertj, spring, etc) don't have to implement an assume for everything.

**Comment by xenoterracide** [comment]
related #2022

**Comment by sormuras** [comment]
Why not like this?

```java
@Test
void test() {
  // assumeThat's
  // assertThat's
  // herBeDragons
  Assertions.fail("You! Shall! Not! Pass!");
}
```

**Comment by sormuras** [comment]
I guess, the already existing [`TestWatcher`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/extension/TestWatcher.html#testSuccessful(org.junit.jupiter.api.extension.ExtensionContext)) API doesn't help here.

**Comment by xenoterracide** [comment]
That code is ugly, duplicative, and verbose. Also doesn't solve the problem of having every "framework" ever writing duplicate assertThat/assumeThat functionality. Yes there are workarounds though...

**Comment by sbrannen** [comment]
Since a `TestAbortedException` can be thrown by user code or any assertion framework anywhere within a test method or lifecycle method, I don't see how such an `@Assumption(failOnPass=true)` annotation could be supported without bytecode manipulation, and JUnit Jupiter does not perform bytecode manipulation.

Or did I misinterpret your proposal?

**Comment by marcphilipp** [comment]
Is this what you want?
https://github.com/junit-team/junit5/blob/5e41ebe612fd67e905f96f1dd3184a071b65be17/documentation/src/test/java/extensions/ExpectToFail.java

If not, please provide a more complete example test.

**Comment by xenoterracide** [comment]
I think so? though my understanding of what it does is based on its name... but based on that, more or less. I was thinking a toggle between soft failing (way assumptions behave now) and hard failing on pass. If that makes sense?

**Comment by Marcono1234** [comment]
An `@ExpectToFail` annotation sounds quite useful, though maybe something like `@Failing` as name would be better to prevent confusion between this annotation and JUnit4's [`ExpectedException` rule](https://github.com/junit-team/junit4/wiki/Exception-testing#expectedexception-rule)?

I would assume in multiple cases where `@Disabled` is currently used such an `@ExpectToFail` annotation would be more appropriate so you are notified when you accidentially fixed a bug.

Though I am not sure if that is actually what the original author wanted, and the title of this issue does not seem to match either. Should I create a separate issue instead?

**Comment by sbrannen** [comment]
> I would assume in multiple cases where `@Disabled` is currently used such an `@ExpectToFail` annotation would be more appropriate so you are notified when you accidentially fixed a bug.

I think that's a good argument in favor of such a new feature.

> Though I am not sure if that is actually what the original author wanted, and the title of this issue does not seem to match either. Should I create a separate issue instead?

There's no need to create a separate issue. I think this one covers the basic category of such use cases, and I'll change the title to reflect the current goal.

**Comment by sbrannen** [comment]
Note that `Assertions.assertThrows(...)` is an existing programmatic mechanism for asserting that a given code block throws an exception; whereas, the current goal of this issue is to introduce a declarative mechanism (for example, an annotation) that _asserts_ that a given test method throws an exception.

However, this new mechanism should not allow the user to specify what type of exception is expected to be thrown, since that would be equivalent to JUnit 4's `ExpectedException` rule and `@Test(expected=...)` support which is something we do not wish to have in JUnit Jupiter.

**Comment by Marcono1234** [comment]
Thanks! Just to be sure we are on the same page, the main intention is to mark a test that is failing, not to mark a test that is expected to throw an exception. Even though a failing test is effectively one which throws an exception (e.g. `AssertionError`), the intention is not to introduce an alternative to `Assertions.assertThrows`. The documentation for the new annotation should also make this clear.
Similarly, if possible, the test output should not be "Test failed" if no exception is thrown, but instead something like "Failing test has been fixed".

Here is an example usage:
```java
void calculateSum(int a, int b) {
    return a - b; // Bug
}

@Failing
@Test
void testCalculateSum() {
    assertEquals(5, calculateSum(2, 3));
}
```
So once you (accidentially) fix the bug in `calculateSum`, JUnit would fail notifying you that the failing test has been fixed.
Compared to the existing `@Disabled` annotation, that would have the advantage that tests could be enabled again as soon as they work again. When using `@Disabled` you risk having tests still disabled after the bug, being the reason for disabling the tests, has been fixed; or you accidentially write new unit tests because you are not aware of the disabled ones.

(Maybe I misunderstood the usage of the existing internal `@ExpectToFail` then though, because it appears to be the same as JUnit 4's `@Test(expected=...)` except without specifying an exception type.)
