### ISSUE TITLE
A DynamicTest should support annotations just like @Test methods

### ISSUE THREAD

**Issue by kirkpabk** [junit-team/junit5#2074]
A `DynamicTest` should support Annotations just as any other Test -- for example, `@Disabled`.

I'd expect that the Test Results should show the items Passed, Failed, and Skipped (as in Disabled).

Unless there's already a way to do this and I missed it...   Thanks all!!

**Comment by marcphilipp** [comment]
Are you referring to the `@TestFactory` method or how would you annotate a dynamic test?

**Comment by kirkpabk** [comment]
Down to the basics, annotations are modifiers to a class, method or fields, right...I've seen implementations in other languages where annotations are exposed as properties or as injectable objects that then get processed the same as any other annotation.  In my view, a Dynamic Test via @TestFactory should not be logically different than any other method decorated with a @Test.  The only difference here is how they're instantiated...how their annotations are realized...

**Comment by sormuras** [comment]
`@Test` ≠ `@TestFactory` element, a dynamic test is **not** a test method variant - it's more like a testlet. Perhaps we should express this intention and rename the annotation to `@TestletProducer`...

It's _just_ an `assertAll()` on steroids, where all assertions are treated as assertions with names. That's it. E.g., I use this tool when a `@ParameterizedTest` is not applicable or would be an overkill. See an example here: https://sormuras.github.io/blog/2018-05-14-junit5-scatter-assertions.html

It's up to the "testlet producer" to produce any kind and any number of `DynamicNode`s, depending on annotations, enviroment variables, states, stars, ... at runtime.

**Comment by sbrannen** [comment]
We have no intention of supporting annotations for individual dynamic test invocations. In addition, I believe it is simply not possible to read the annotations on lambda expressions. So that's not an option, and passing _synthetic_ annotations as method arguments seems rather clunky to me.

Dynamic tests are intended to be "dynamic" and therefore not "statically" annotated.

If you wish to abort a dynamic test mid-flight, simply throw a `TestAbortedException` directly or make use of `Assumptions`.

**Comment by sbrannen** [comment]
**Team Decision**: in light of the above https://github.com/junit-team/junit5/issues/2074#issuecomment-548768493, we are closing this issue.
