### ISSUE TITLE
Provide a way to skip test execution from an extension

### ISSUE THREAD

**Issue by loicmathieu** [junit-team/junit5#2083]
I'm working on [QuickPerf](https://github.com/quick-perf), a tool to create performance related test with JUnit.
For QuickPerf, we need to be able to launch a test on a different JVM instance, so we need to be able to fork a JVM from within an extension.

My current implementation is to fork the VM inside the extension in `interceptTestMethod` method: https://github.com/quick-perf/quickperf/blob/master/junit5/src/main/java/org/quickperf/junit5/QuickPerfTestExtension.java#L49

Doing this, the method is executed twice (once on each VM), so I would like to be able to skip the test method execution is the host VM but the `Invocation` must be proceed or I have an error.

Today I invoke twice the test methods, what I would like is to have a way to skip a test invocation.

A possible implementation would be to add a `skip` method to the `Invocation` so we can skip it's execution.

## Deliverables
Modify the `Invocation` to be able to skip it.
I can provide a PR for this.

**Comment by sbrannen** [comment]
Tentatively slated for 5.6 M2 solely for the purpose of _team discussion_

**Comment by stuartwdouglas** [comment]
I have a similar requirement for Quarkus testing, with regards to skipping @BeforeAll and @AfterAll methods. 

I can generate a Proxy of a test and use this to redirect test methods into test instance defined in a new ClassLoader, however BeforeAll and AfterAll are always invoked on the original test Class. 

If I did not have to invoke Invocation.proceed() I could just invoke these methods on my actual test directly, and then avoid invocation on the test class in the original ClassLoader.

**Comment by marcphilipp** [comment]
@loicmathieu Have you considered writing a TestEngine instead? I don't know how your execution in a separate VM works, but I could imagine supporting arbitrary Jupiter extensions.

**Comment by stuartwdouglas** [comment]
The TestEngine approach would not work for my use case, as I would want to delegate all the logic to Jupiter, and having it on the class path would result in problems (I think Arquillian attempted this and ran into similar issues).

I need a way to execute a test inside an isolated ClassLoader, and I can do almost everything by creating a proxy that extends the actual test class and forwarding all the invocations, except for @BeforeAll and @AfterAll because they are static. 

The best I can do is have an invocation on both the class in the bootstrap class loader and in the isolated class loader, which will work sometimes but not if they are doing things like listening on a port which would conflict.

If I could prevent the invocation hitting the original class then I could just directly invoke these methods on the class in my isolated ClassLoader.

**Comment by loicmathieu** [comment]
@marcphilipp it has already been suggested but I assume the work is a little more than an extension ? And all other test framework that our user used must be compatible with it ?

To fork we start a new Java Process from the extension, it is the same code that we used to fork from JUnit4. 
One of our use case is to measure the byte allocated by a test, so we need some control of how we execute it.

**Comment by marcphilipp** [comment]
Since we support multiple `InvocationInterceptors` that get chained we have to decide what to do if one of them that's not last in the list decides to skip the invocation. We could either allow that and not call the remaining interceptors or only allow the last interceptor in the chain to skip. I lean towards the first option.

**Comment by marcphilipp** [comment]
**Team Decision:** Implement the first option and add debug logging when skip was called.

**Comment by marcphilipp** [comment]
@loicmathieu Would you still like to submit a PR for this one?

**Comment by loicmathieu** [comment]
@marcphilipp it will be my pleasure :)
