### ISSUE TITLE
Console does not associate with tests reliably in parallel mode

### ISSUE THREAD

**Issue by calvertdw** [junit-team/junit5#2115]
I am enjoying the parallelism features provided by JUnit 5. While developing using test driven development, it is useful to run as many tests as possible as frequently as possible.

I have been using IntelliJ to run the entire test package of my project frequently and using the JVM options:

```
-ea
-Djunit.jupiter.execution.parallel.enabled=true
-Djunit.jupiter.execution.parallel.mode.default=concurrent
```

The issue is the console output is not readable. It gets jumbled together and spread accross many methods. It is useful to monitor the console output of various tests, especially to see what led up to a failure.

I assume the issue can only be alleviated by printing to a JUnit specific logger or providing forked process parallelism options.

JUnit 5.5.1 and IntelliJ 2019.2

Example test results:

[Test Results - us_ihmc_games_zombieDice_in_games_games-test_main1.html.txt](https://github.com/junit-team/junit5/files/3893261/Test.Results.-.us_ihmc_games_zombieDice_in_games_games-test_main1.html.txt)

![image](https://user-images.githubusercontent.com/1161586/69658764-6a911380-1042-11ea-8eb3-c2d29ab34b48.png)

**Comment by AOreshin** [comment]
I managed to work around the same problem using [Log4J2 fish tagging](https://logging.apache.org/log4j/2.x/manual/thread-context.html) and [Allure reports](https://docs.qameta.io/allure/)

This simple extension tags logs from test with specific id
```
public final class FishTaggingExtension implements BeforeEachCallback, AfterEachCallback {
    @Override
    public void beforeEach(ExtensionContext context) {
        ThreadContext.put("id", Allure.getLifecycle().getCurrentTestCase().orElseThrow());
    }

    @Override
    public void afterEach(ExtensionContext context) {
        ThreadContext.clearMap();
    }
}
```
This extension reads messages with specific tag and adds them to report
```
public final class AllureAttachmentsExtension implements AfterEachCallback {
    //Path to log file
    private static final String LOG_PATH = "logs/test.log";
    
    @Override
    public void afterEach(ExtensionContext context) throws IOException {
        String groupedLogMessages = getMessagesWithId(getContent(), getAllureTestUuid());
        Allure
                .getLifecycle()
                .addAttachment("Full log", "text/html", ".txt", groupedLogMessages.getBytes());
    }

    private String getAllureTestUuid() {
        return Allure.getLifecycle().getCurrentTestCase().orElseThrow();
    }

    private List<String> getContent() throws IOException {
        Path path = Paths.get(System.getProperty("user.dir") + LOG_PATH);
        return Files.readAllLines(path, StandardCharsets.UTF_8);
    }

    private String getMessagesWithId(List<String> content, String uuid) {
        String uuidTemplate = "[" + uuid + "] ";
        return content
                .stream()
                //Filtering messages by id
                .filter(logMessage -> logMessage.contains(uuidTemplate))
                //Removing ids from messages
                .map(logMessage -> logMessage.replaceAll("\\[" + uuid + "] ", ""))
                //Convert to string with \n delimiter
                .collect(Collectors.joining("\n"));
    }
}
```
Corresponding log4j2 config
```
@Plugin(name = "LoggingConfig", category = ConfigurationFactory.CATEGORY)
@Order(Integer.MAX_VALUE)
public final class LoggingConfig extends ConfigurationFactory {
    //Path to log file
    private static final String LOG_PATH = "logs/test.log";

    static Configuration createConfiguration(final String name, ConfigurationBuilder<BuiltConfiguration> builder) {
        builder.setConfigurationName(name);
        builder.setStatusLevel(Level.ALL);

        LayoutComponentBuilder layout = builder
                .newLayout("PatternLayout")
                .addAttribute("pattern", "[%X{id}] %m%n")
                .addAttribute("charset", "UTF-8");

        AppenderComponentBuilder fileAppender = builder
                .newAppender("fileAppender", "File")
                .addAttribute("fileName", System.getProperty("user.dir") + LOG_PATH)
                //Очищать файл перед записью
                .addAttribute("append", false)
                //Писать в файл сразу после получения сообщения
                .addAttribute("immediateFlush", true)
                .addComponent(layout);

        RootLoggerComponentBuilder rootLogger = builder
                .newRootLogger(Level.ALL);
        
        Configuration configuration = builder
                .add(fileAppender)
                .add(rootLogger)
                .build();

        //Print equivalent xml to console for debugging purposes
        try {
            builder.writeXmlConfiguration(System.out);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return configuration;
    }

    @Override
    public Configuration getConfiguration(final LoggerContext loggerContext, final ConfigurationSource source) {
        return getConfiguration(loggerContext, source.toString(), null);
    }

    @Override
    public Configuration getConfiguration(final LoggerContext loggerContext, final String name, final URI configLocation) {
        ConfigurationBuilder<BuiltConfiguration> builder = newConfigurationBuilder();
        return createConfiguration(name, builder);
    }

    @Override
    protected String[] getSupportedTypes() {
        return new String[] {"*"};
    }
}
```
All you have to do now is
1. Annotate your tests with @ ExtendWith({FishTaggingExtension.class, AllureAttachmentsExtension.class})
2. Specify logger config -Dlog4j2.configurationFactory=com.project.LoggingConfig

**Comment by marcphilipp** [comment]
Have you tried [capturing stdout/stderr](https://junit.org/junit5/docs/current/user-guide/#running-tests-capturing-output)?

Apart from that there's nothing we can do here, it's simply multiple threads using `System.out` concurrently. IntelliJ could register a listener that replaces `System.out` with a `PrintStream` that uses `ThreadLocals` to attribute output to the test that was started by the current thread. Can you please open an issue for Jetbrains? I'm closing this issue because it's not solveable here but feel free to post additional context in case I missed sth.

**Comment by calvertdw** [comment]
Where can I find the default value for `junit.platform.output.capture.maxBuffer`? What does it take as a argument? Bytes as an integer or notation like `4m` and `1g`?

**Comment by calvertdw** [comment]
This isn't an issue with IntelliJ. See the included test HTML. The console maps to that exactly as is maps to the outputs shown in IntelliJ.

I used 
```

**Comment by calvertdw** [comment]
I should probably make a better test case for this issue.

**Comment by marcphilipp** [comment]
> Where can I find the default value for `junit.platform.output.capture.maxBuffer`? What does it take as a argument? Bytes as an integer or notation like `4m` and `1g`?

https://github.com/junit-team/junit5/blob/5e41ebe612fd67e905f96f1dd3184a071b65be17/junit-platform-launcher/src/main/java/org/junit/platform/launcher/LauncherConstants.java#L72-L78

> I don't think this is an issue with IntelliJ. See the included test HTML. The console maps to that exactly as is maps to the outputs shown in IntelliJ.
> 
> I used
> 
> ```
> -ea
> -Djunit.jupiter.execution.parallel.enabled=true
> -Djunit.jupiter.execution.parallel.mode.default=concurrent
> -Djunit.platform.output.capture.stdout=true
> -Djunit.platform.output.capture.stderr=true
> ```
> 
> and the outputs are still scrambled.

Enabling capturing stdout/stderr will still forward output to the original `System.out`/`System.err` so that's to be expected. IntelliJ should in addition report the captured output as
```
timestamp = 2019-12-01T12:28:47.673959, stdout = ...
```

**Comment by hmijail** [comment]
I just tried adding the capture properties to the sample project junit5-jupiter-starter-gradle, so the test block in build.gradle ends up looking like this:
```
test {
	useJUnitPlatform()
	testLogging {
		events "passed", "skipped", "failed"
	}
	systemProperty 'junit.platform.output.capture.stdout', 'true'
	systemProperty 'junit.platform.output.capture.stderr', 'true'
}
```

Then I added some System.out.println("...") to the tests, duplicated the class and made some of the tests fail. 
The results, both HTML and XML formats, still contain all of stdout together (or rather, it's separated by class, but not by test)

I hope that I am doing something wrong, because if I comment out the systemProperty lines, the result is still exactly the same.

**Comment by sbrannen** [comment]
That sounds to me like it might be more of an issue with Gradle's JUnit Platform support.

@marcphilipp, WDYT?

**Comment by marcphilipp** [comment]
The JUnit Platform captures stdout/stderr and publishes them to registered `TestExecutionListeners` as report entries. However, since Gradle does not yet support those (see https://github.com/gradle/gradle/issues/4605), it does not yet make a difference when executing the tests from Gradle.

**Comment by Avetis009** [comment]
Hello! I am using parallel testing from JUnit5 in my Gradle project and it is very cool, but I have a problem. I want the test logs to be written to the console separately, because now when running parallel tests, the logs are written in the heap and are not readable. How can i do it?

**Comment by kriegaex** [comment]
> Enabling capturing stdout/stderr will still forward output to the original `System.out`/`System.err` so that's to be expected. IntelliJ should in addition report the captured output as

Can this be avoided somehow, if the motive for listener use is not nicer reports, but nicer system console logs (which then can also be captured on CI systems as log files)? The naive way of using it, registering an execution listener and then dumping the buffer entries (text only, no timestamps) to the system console in `reportingEntryPublished`, yields duplicate console output.

**Comment by vladttt1123** [comment]
I am still faicng the same issue when runnin tests in parallel :
I run this command: 

mvn test -Djunit.jupiter.execution.parallel.enabled=true -Djunit.jupiter.execution.parallel.mode.default=same_thread -Djunit.jupiter.execution.parallel.mode.classes.default=concurrent -Duri=http://localhost:8000/api -

and eventually  the test output is invalid, for example I have; 
96572 [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 80.925 s - in customexporttests.testset1
146589 [INFO] Tests run: 50, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 137.054 s - in admintests.testset2

While expected was: 
96572 [INFO] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 80.925 s - in randomtest.testset1
146589 [INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 137.054 s - in randomtest.testset2


This only happens when tests are run in parallel, I've come across this issue here: 
https://issues.apache.org/jira/browse/SUREFIRE-1643

BUt still there's no resolution.
If anyone managed to fix it or go around it, please comment below.

**Comment by vladttt1123** [comment]
I think I found a way to  register the test Listener in a very easy way , please see the answer to my StackOverflow issue
and I think it might help you 
https://stackoverflow.com/questions/78423490/junit-listener-is-not-triggered-when-running-tests-with-maven-command?noredirect=1#comment138259339_78423490

**Comment by daverbk** [comment]
Hey there! Just leaving a [YouTrack issue reference](https://youtrack.jetbrains.com/issue/IDEA-364536/Console-output-corrupted-when-tests-run-in-parallel) on the matter.
