### ISSUE TITLE
Duplicate annotations are swallowed by AnnotationSupport

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#2131]
Seems to be feature we wanted?

https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/AnnotationUtils.java#L217-L219

This use case triggered the question:

https://github.com/junit-pioneer/junit-pioneer/pull/133/files#diff-e173b19bdf682fe079028644b4dccc43R168-R171

## Deliverables

- [ ] Working as intended?
- [ ] Bug?

**Comment by nicolaiparlog** [comment]
Could [this exchange](https://github.com/junit-pioneer/junit-pioneer/pull/123#discussion_r356247176) be related?

**Comment by marcphilipp** [comment]
I guess we could add a 'findAll*Annotations` family of methods.

**Comment by sbrannen** [comment]
> Seems to be feature we wanted?

I don't think so. We explicitly use a `Set` so that there are no duplicates. In that sense, it works as intended.

If we (or extension authors) need to find all annotations (including duplicates), we'd have to implement something like @marcphilipp suggested. Note that the Spring Framework provides that kind of support in `AnnotatedElementUtils.findAllMergedAnnotations(...)`.
