### ISSUE TITLE
Use registered ParameterResolver(s) when invoking @MethodSource factory methods

### ISSUE THREAD

**Issue by nishantvas** [junit-team/junit5#2191]
Currently, the `MethodSource` methods are supposed to not have any parameters, however, it'll help to have parameters to be resolved in these methods if registered similar to Before/After methods.

Along with #2190, this will give access to `MethodSource` methods to possibly use `Extension.Store` and store any initialized details, which could be purged in `@AfterAll` methods

Also, in case of creating dynamic tests using details from a resolved Object, `ParameterResolver` can enhance abilities of `MethodSource` by a fair bit.

Currently, the way to achieve the same is to have a class implementing `ArgumentsProvider` and possibly manage the value of the object there, or have it in the `MethodSource` method itself statically initializing it in test class.

**Comment by marcphilipp** [comment]
@nishantvas Could you please add a concrete code example?

**Comment by nishantvas** [comment]
```
static Stream<Arguments> createElementArguments(){
    // The below function is basically a wrapped function which my ParameterResolver also calls
    MyElement elem  = MyElement.staticInitializer(); // Possibly with test specific arguments
    return Stream.of(createArguments(elem));
  }

  // This way, I can have a common place to initialize / resolve the MyElement type class
  static Stream<Arguments> createElementArgumentsFromResolver(MyElement element){
    return Stream.of(createArguments(elem));
  }

  @MethodSource("createElementArguments")
  @ParameterizedTest(name = "Do Something With Element {0} and expect {2}")
  void testArguments(
      String test,
      MyElemment element,
      int expectedCode) {
    given()
        .request()
          .body(element)
        .then()
          .expect()
          .statusCode(expectedCode)
        .request()
        .put("/path/to/put");
  }
```

@marcphilipp , I'm suggesting something like this, so that The code to resolve `MyElement` type can stay standardised or perhaps also secure by delegating via ParameterResolvers

**Comment by marcphilipp** [comment]
@nishantvas Thanks!

@sbrannen Would you mind adding an example of the `@BeforeTransaction` use case in Spring?

**Comment by sbrannen** [comment]
Reopening since this should be looked at in conjunction with #2579.

**Comment by sbrannen** [comment]
> @sbrannen Would you mind adding an example of the `@BeforeTransaction` use case in Spring?

In Spring, a `@Test` method can have a bean from the `ApplicationContext` `@Autowired` into it via the `SpringExtension` (which implements Jupiter's `ParameterResolver` extension API).

The same is true for `@BeforeEach` and `@AfterEach` methods when used with Spring's testing support.

However, Spring also supports its own `@BeforeTransaction` and `@AfterTransaction` lifecycle methods for transactional tests, and these methods cannot be _injected_ with arguments provided by a Jupiter `ParameterResolver` since Spring invokes such methods on its own.

I therefore propose that the `ExtensionContext` provide a means for invoking any user-supplied method using all registered `ParameterResolver` implementations.

With this functionality in place, `@MethodSource` factory methods could be invoked using the same mechanism.

**Comment by sbrannen** [comment]
Now that #2393 has been completed, work on this feature can begin.

**Comment by julianhyde** [comment]
In case you weren't aware, this seems to be a breaking change. See https://issues.apache.org/jira/browse/CALCITE-5356 and https://github.com/apache/calcite/pull/2958 for details.

**Comment by sbrannen** [comment]
Hi @julianhyde,

Are you certain that the error occurred while using JUnit Jupiter 5.9.1?

The reason I ask is twofold:

1. In 5.9.1., we fixed several regressions that were introduced in 5.9.0
  - #2993
  - #3001 
2. I cannot reproduce the Calcite issue with identical `static` factory methods in a test class and its superclass

If you can reproduce the Calcite issue using JUnit Jupiter 5.9.1., please [create a new issue](https://github.com/junit-team/junit5/issues/new/choose) so that we can look into it.

Thanks!

**Comment by sbrannen** [comment]
> If you can reproduce the Calcite issue using JUnit Jupiter 5.9.1., please [create a new issue](https://github.com/junit-team/junit5/issues/new/choose) so that we can look into it.

I figured out the cause and raised #3080 for the team to discuss.

**Comment by julianhyde** [comment]
Thanks for investigating, @sbrannen. FWIW, the issue is not a blocker for Calcite. We easily figured out how to change our use of junit. Just letting you know because I know you take semantic versioning seriously.
