### ISSUE TITLE
Allow @RepeatedTest to be configured with a variable number of repititions

### ISSUE THREAD

**Issue by swaranga** [junit-team/junit5#2193]
Currently you need to hardcode the number of repetitions of a @RepeatedTest in source code. However sometimes it would be desirable to compute the number of repetitions dynamically based on some external conditions (System properties, Env vars, Database etc...)

Our use case is that for our alpha, beta stages we would like to run our tests multiple times but in production stages we would only run it once or twice. This ensure that our tests and features are stable before we push them to all the production stages and regions.

Alternatively, if there is a way to do this via the extension model please let me know. I looked around but could not figure it out. Any pointers will be helpful.

**Comment by sormuras** [comment]
Sounds like [Dynamic Tests](https://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests) do fit here well, don't they?

**Comment by sbrannen** [comment]
> Alternatively, if there is a way to do this via the extension model please let me know. I looked around but could not figure it out. Any pointers will be helpful.

Well, the `@RepeatedTest` support is provided by an extension (that happens to be automatically registered). It is not baked into JUnit Jupiter.

So you can implement your own `TestTemplateInvocationContextProvider` that provides a `Stream<TestTemplateInvocationContext>` containing the number of entries you desire.

See the source code for the [`RepeatedTestExtension`](https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/RepeatedTestExtension.java) for details.

If you need full lifecycle support for your test invocations, you'll need to go this route.

Otherwise, you can use dynamic tests as @sormuras mentioned above.

**Comment by swaranga** [comment]
Thank you. I went with the custom extension way. It was fairly easy to do.

**Comment by sbrannen** [comment]
> Thank you. I went with the custom extension way. It was fairly easy to do.

You're welcome. Glad you sorted it out.
