### ISSUE TITLE
How Get result of singole childrens test from a @TestFactory (DynamicTest)?

### ISSUE THREAD

**Issue by enaud1984** [junit-team/junit5#2223]
Hi all, 

if I have a `@TestFactory` method that runs 20 sub-tests with different parameters with summary, how can I get ALL test results?

```java
   SummaryGeneratingListener listener = new SummaryGeneratingListener();
   LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
                .selectors(selectMethod(cls,m))
                .build();

        Launcher launcher = LauncherFactory.create();
        launcher.registerTestExecutionListeners(listener);
        launcher.execute(request);
        TestExecutionSummary summary = listener.getSummary();
````

I can get only Number total tests of Success and Fail test, and there is only `List<Failure> testsFail= summary.getFailures();`, but I want ALL results also Successful tests.

Is there a function that returns a MAP of <Test Identifier, Results> ??

thanks
Regards

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

Having pointed out our policy above, I'll do my best to quickly answer your question here.

As stated in the Javadoc, the `SummaryGeneratingListener` only generates a `TestExecutionSummary` which is literally just a summary. It does not track all details of the test execution.

If you want to track more details, you'll need to implement your own `TestExecutionListener`.

Although the `org.junit.platform.reporting.legacy.xml.LegacyXmlReportGeneratingListener` is very detailed, you may still find it useful for inspiration.
