### ISSUE TITLE
Where are your own test suites?

### ISSUE THREAD

**Issue by silkentrance** [junit-team/junit5#2252]
I have searched on google and in this repository, by to no avail.

Where can I find the tests to for example junit-api and so on?

TIA and thanks for the tremendous work you are doing. Be well!

**Comment by marcphilipp** [comment]
> Where can I find the tests to for example junit-api and so on?

Our test setup is a bit special since we're testing JUnit with JUnit.

- Tests for junit-jupiter-api and junit-jupiter-engine are in junit-jupiter-engine (since they need the engine to run and Eclipse doesn't like cyclic project dependencies even if they are between different source sets)
- Tests for junit-jupiter-migrationsupport, junit-jupiter-params and junit-vintage-engine are in the same project
- Tests for all platform subprojects are in platform-tests (since they are written with Jupiter which depends on the platform)
- Integration tests are in platform-tooling-support-tests

> TIA and thanks for the tremendous work you are doing. Be well!

Thanks, you too! 🙂
