### ISSUE TITLE
Tests not found by maven-failsafe-plugin or in error in a newly created Spring Boot project

### ISSUE THREAD

**Issue by f-lopes** [junit-team/junit5#2348]
JUnit 5 tests are not found by the `maven-failsafe-plugin` (JUnit `5.6.1`)  or fail to find correct annotations on newly initialized Spring Boot project test (JUnit `5.5.2`):

Using JUnit `5.6.1`:
```shell script
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ spring-boot-failsafe-maven-plugin ---
[INFO] Building jar: E:\WORK\git\spring\spring-boot-failsafe-maven-plugin\target\spring-boot-failsafe-maven-plugin-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ spring-boot-failsafe-maven-plugin ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ spring-boot-failsafe-maven-plugin ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

Using JUnit `5.5.2`:
```bash
gbootfailsafemavenplugin.SpringBootFailsafeMavenPluginApplicationIT]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.226 s <<< FAILURE! - in io.florianlopes.springbootfailsafemavenplugin.SpringBootFailsafeMavenPluginApplicationIT
[ERROR] io.florianlopes.springbootfailsafemavenplugin.SpringBootFailsafeMavenPluginApplicationIT  Time elapsed: 0.226 s  <<< ERROR!
java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SpringBootFailsafeMavenPluginApplicationIT » IllegalState Unable to find a @Sp...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ spring-boot-failsafe-maven-plugin ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

The annotation is indeed present (extract of the test class):
```java
@SpringBootTest
class SpringBootFailsafeMavenPluginApplicationIT {
    @Test
    void contextLoads() {
    }
}
```

Of course, the `maven-failsafe-plugin` is correctly configured to run `*IT` classes (as it works without the `@ContextConfiguration` annotation):

```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-failsafe-plugin</artifactId>
	<version>3.0.0-M5</version>
	<configuration>
		<includes>
			<include>**/*IT.java</include>
		</includes>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>integration-test</goal>
				<goal>verify</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

Selecting the `surefire-junit-platform` provider as suggested [here](https://stackoverflow.com/questions/29099264/maven-failsafe-plugin-doesnt-pick-up-testng-tests#comment46472667_29099264) changed nothing.

## Steps to reproduce

Here is a project to reproduce this issue: https://github.com/f-lopes/spring-boot-failsafe-maven-plugin-issue

Two commands to reproduce: 
`docker run flopes/spring-boot-failsafe-maven-plugin-issue:junit-5-6-1`
`docker run flopes/spring-boot-failsafe-maven-plugin-issue:junit-5-5-2`

## Context

Versions used:
- JUnit `5.5.2` / JUnit `5.6.1`
- Spring Boot `2.2.6`
- Maven Failsafe plugin `3.0.0-M5`

Build scans: 
- JUnit `5.5.2`: https://gradle.com/s/gwxbtdna7m6jk
- JUnit `5.6.1`: https://gradle.com/s/lfq2uyod6noge

## Deliverables
Example project: https://github.com/f-lopes/spring-boot-failsafe-maven-plugin-issue

**UPDATE:** 

I have run some tests in debug mode and found that the `maven-failsafe-plugin` test scanner did find my test class. However, when passing it to the JUnit provider, it fails to be found/executed.

**Comment by khmarbaise** [comment]
There are several points which are mixed here.
* To test the spring boot application integration test (get it working) it needed to look like this:
```java
@SpringBootTest(classes = SpringBootFailsafeMavenPluginApplication.class)
class SpringBootFailsafeMavenPluginApplicationIT {

    @Test
    void contextLoads() {
    }
}
```
  * The given class `SpringBootFailsafeMavenPluginApplication.class` is given here. If you take a look into running the test within your IDE you will see that the `SpringBootFailsafeMavenPluginApplication.class` will automatically given to run the test which shows a correctly running test. If you run the same test on console (Maven build) it will fail cause it's not defined in the IT.
  * So to get a correct working test in the first step you have to add the `classes` configuration in your test.

**JUnit Jupiter in Maven**
 * The version of JUnit Jupiter which is inherited/used from Spring Boot (or more accurate `spring-boot-dependencies`).
 * Spring Boot version 2.2.6.RELEASE contains a definition to JUnit Jupiter 5.5.2

**Using a different version of JUnit Jupiter in Maven**
* If you simply try to replace only partial parts of the dependencies to Junit Jupiter (which are given via `spring-boot-dependencies`) via adding dependencies to your `pom.xml` like the following (as given in your example repository):
```xml
<dependency>
	<groupId>org.junit.jupiter</groupId>
	<artifactId>junit-jupiter-api</artifactId>
	<version>${junit-jupiter.version}</version>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.junit.jupiter</groupId>
	<artifactId>junit-jupiter-engine</artifactId>
	<version>${junit-jupiter.version}</version>
	<scope>test</scope>
</dependency>
```
* This means your are replacing only two dependencies in the whole list of JUnit Jupiter. This will result in wrong results.

**Correct way to use a different version of JUnit Jupiter than  defined in Spring Boot (Maven)**
* The only correct working way is to go via the following way. You have to import the BOM of JUnit Jupiter before
Spring Boot BOM otherwise it will not work. If you accidentally do the import of JUnit Jupiter after spring boot this will not work.
```xml
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.junit</groupId>
			<artifactId>junit-bom</artifactId>
			<version>${junit-jupiter.version}</version>
			<type>pom</type>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-dependencies</artifactId>
			<version>${spring-boot-dependencies.version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
```
* Secondly you can simply add the following dependency in your pom like this:
```xml
<dependency>
	<groupId>org.junit.jupiter</groupId>
	<artifactId>junit-jupiter</artifactId>
	<scope>test</scope>
</dependency>
```
 * This contains deps to `junit-jupiter-api`, `junit-jupiter-params` and `junit-jupiter-engine`.
* This will result in a working IT in your Maven build.

**Hint about the usage of maven-failsafe-plugin**
* The configuration for the maven-failsafe-plugin can be simplified like the following:
```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-failsafe-plugin</artifactId>
	<version>3.0.0-M5</version>
	<executions>
		<execution>
			<goals>
				<goal>integration-test</goal>
				<goal>verify</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```
* There is no need to define supplemental configuration like the following:
```xml
<configuration>
	<includes>
		<include>**/*IT.java</include>
	</includes>
</configuration>
```
 * which is already the default of the plugin.

**Comment by sbrannen** [comment]
@khmarbaise, thanks for investigating this and providing an answer.

In light of that, I am closing this issue.

In addition, please note the following policy for such questions in this issue tracker.

> Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

**Comment by f-lopes** [comment]
Thank you for taking the time to detail all these points.

1. I agree with you regarding the `classes` parameter of the `@SpringBootTest` annotation. This was my initial thought but I was a bit surprised that it was not included by default in a fresh Spring Boot project (initiated via the initializr) and I thought it would work using the default configuration.
Indeed, the IDE gives the correct class.

2. JUnit version replacement: I take not of this, thanks.

3. Usage of maven-failsafe-plugin: I wanted to show the exact configuration of the project that had this issue. I take note though, thanks.

I apologize for the inconvenience. I only permitted myself to open this issue because of a similar one (#2317).

Anyway, many thanks!
