### ISSUE TITLE
XyzTest or XyzTests?

### ISSUE THREAD

**Issue by pandoras-toolbox** [junit-team/junit5#2428]
I noticed that the JUnit 5 own test classes are named like XyzTests using the plural. But in the JUnit 5 examples the singular is used, like XyzTest. And that was until now the common convention to name them with the singular.

Do you now recommend to use the plural? Logically it makes more sense to do that. On the other hand, class names have the convention to be a singular noun.

Technically both naming conventions work of course. But which one do you suggest to use?

**Comment by sormuras** [comment]
> But in the JUnit 5 examples the singular is used, [...]

Which examples are you referring to?

- https://github.com/junit-team/junit5-samples
- https://github.com/junit-team/junit5/tree/main/documentation/src/test/java (User Guide)
- or others?

**Comment by sbrannen** [comment]
The team decided to use `*Tests` as the naming convention for test classes, because they contain "tests" (plural). The class itself is not a "test".

Regarding the class name filters used in the JUnit Platform, the default pattern matches against classes whose names either begin with `Test` or end with `Test` or `Tests` (in any package).

Recent versions of Maven also support the `*Tests` convention.

I personally suggest the use of `*Tests`; however, I cannot speak for the personal preferences of all of my team members, and in the end... it's a matter of personal/team preference.

**Comment by sbrannen** [comment]
Closing this issue since it's a _question_ (rather than a feature request or bug report), and I've answered it above.
