### ISSUE TITLE
Provide a platform hook for agents

### ISSUE THREAD

**Issue by leonard84** [junit-team/junit5#2429]
While discussing [Sarek](https://github.com/SarekTest/Sarek/) with @kriegaex we discovered the need to initialize the Sarek agent was soon as possible. Right now, it uses a Jupiter/Spock extension to load, but as the Platform can execute multiple engines it would be possible for other engines to run earlier and load classes, that then couldn't be "unfinalized" by the agent.

A platform level hook that would run as early as possible would be the best solution, so that users wouldn't have to manually call the java executable with javaagent arguments.

## Deliverables

- [ ] ServiceLoader interface to initialize Agents, could be as simple as `interface AgentLoader { void install(); }` this should be calles as early as possible

**Comment by sbrannen** [comment]
Have you considered using an auto-registered `TestExecutionListener`?

BlockHound seems to fair very well with [that approach](https://github.com/reactor/BlockHound/blob/master/junit-platform/src/main/java/reactor/blockhound/junit/platform/BlockHoundTestExecutionListener.java). Note the use of `@AutoService(TestExecutionListener.class)` there, and read the Javadoc.

**Comment by kriegaex** [comment]
I performed a quick & dirty try in a combined Spock + JUnit Maven project and at first glance it seems to works. I do admit though, that I find it quite hacky to register a test execution listener and therein initialise Sarek from a static type initialiser block. I did it similarly do BlockHound like this:

File `META-INF/services/org.junit.platform.launcher.TestExecutionListener`:

```text
dev.sarek.SarekAttachListener
```

The listener:

```java
package dev.sarek;

import dev.sarek.attach.AgentAttacher;
import dev.sarek.attach.AgentAttacherException;
import org.junit.platform.launcher.TestExecutionListener;

public class SarekAttachListener implements TestExecutionListener {
  private final static String LOG_PREFIX = "[Sarek JUnit Platform Execution Listener] ";

  static {
    log("going to attach Sarek agent (if not attached yet)");
    try {
      AgentAttacher.install();
    }
    catch (AgentAttacherException e) {
      throw new RuntimeException(e);
    }
  }

  private static void log(String message) {
    System.out.println(LOG_PREFIX + message);
  }
}
```

I had to add these test dependencies to my sample project:

```xml
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-launcher</artifactId>
      <version>1.6.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-engine</artifactId>
      <version>1.6.2</version>
      <scope>test</scope>
    </dependency>
```

The launcher dependency is of course necessary in order to be able to import `TestExecutionListener`. Without the engine dependency I get a "class not found" error for `EngineDiscoveryListener` when starting the JUnit platform, which is rather ugly.

---

Some background about Sarek: It injects itself and its dependencies (e.g. ByteBuddy) into the bootstrap class loader because it has the capability to also mock/stub JRE bootstrap classes and/or remove their `final` modifiers during class-loading. Specifically unfinalisation only works during class-loading, the rest also works on loaded classes. I.e. the earlier the Sarek extension is registered (before e.g. JUnit loads a lot of classes), the better for Sarek's mocking/stubbing capabilities later. This is why @leonard84 asked for a global platform hook with as early as possible execution time.

**Comment by sbrannen** [comment]
> Without the engine dependency I get a "class not found" error for `EngineDiscoveryListener` when starting the JUnit platform, which is rather ugly.

`junit-platform-launcher` has a [transitive dependency on `junit-platform-engine`](https://search.maven.org/artifact/org.junit.platform/junit-platform-launcher/1.6.2/jar). So you shouldn't need to add a concrete dependency yourself. 

Are you importing the [JUnit BOM](https://search.maven.org/artifact/org.junit/junit-bom/5.6.2/pom) for unified dependency version management?

**Comment by sbrannen** [comment]
> I performed a quick & dirty try in a combined Spock + JUnit Maven project and at first glance it seems to works. 

Thanks for trying it out.

> I do admit though, that I find it quite hacky to register a test execution listener and therein initialise Sarek from a static type initialiser block.

I didn't say it was ideal. Rather, I was pointing it out as a solution that currently should work without relying on a new feature being implemented in the JUnit Platform.

**Comment by kriegaex** [comment]
> `junit-platform-launcher` has a [transitive dependency on `junit-platform-engine`](https://search.maven.org/artifact/org.junit.platform/junit-platform-launcher/1.6.2/jar). So you shouldn't need to add a concrete dependency yourself.

That is what I was thinking too, which is why I mentioned it in the first place.

> Are you importing the [JUnit BOM](https://search.maven.org/artifact/org.junit/junit-bom/5.6.2/pom) for unified dependency version management?

No, I was not. But Spock Core does. The sample project being a bit older (using Spock version 2.0-M1-groovy-2.5 which in turn imports on JUnit BOM 5.5.2 instead of 5.6.2), so using `mvn dependency:tree` I found out that I had engine 1.5.2 on my class path, not 1.6.2 as I believed. So I had a version mismatch and adding the extra dependency in the matching version made the problem go away. Like I said, I just implanted my quick & dirty try that into an old project to rapid feedback, leading to unclean (as in inconsistent) version management. Thank you for your hint, lesson learned. 😀

**Comment by kriegaex** [comment]
> I didn't say it was ideal. Rather, I was pointing it out as a solution that currently should work without relying on a new feature being implemented in the JUnit Platform.

So with a viable workaround in place, are you still considering to accept this feature request or would you rather reject it? You can imagine what we are hoping for, but I am asking because I like to read your opinion.

**Comment by sbrannen** [comment]
> Thank you for your hint, lesson learned.

👍 


> So with a viable workaround in place, are you still considering to accept this feature request or would you rather reject it?

We'll discuss that amongst the team.

Tentatively slated for 5.8 M1 for _team discussion_

**Comment by marcphilipp** [comment]
@leonard84 Will Sarek become part of Spock at some point? If so, the `static` initializer "hack" should work when done in the `TestEngine`. 🤔

**Comment by leonard84** [comment]
@marcphilipp we currently don't plan to merge the code bases, Sarek will be integrated via ServiceLoader https://github.com/spockframework/spock/issues/1220. And the problem remains that it has to run as early as possible due to the fact that it should transform classes on load, if it is done at the `TestEngine` level then another engine could have already loaded more classes.

`TestExecutionListener` might be a viable workaround, but as @kriegaex said putting it in the static initializer block feels wrong. As we are not the only ones who want to have a way to register agents it might be worthwhile to add a proper dedicated interface for that.

**Comment by marcphilipp** [comment]
The `LauncherSessionListener` introduced in #2514 is called before any `TestEngine` is initialized and should therefore be sufficient to implement this use case.

**Comment by sbrannen** [comment]
Superseded by  #2514
