### ISSUE TITLE
How to set up a build with junit 4 or junit 5

### ISSUE THREAD

**Issue by jactor-rises** [junit-team/junit5#2498]
https://github.com/navikt/bidrag-cucumber-nais

an application which runs cucumber tests.

when building, I hava two profiles:
- default: runs surefire junit 5 plugin
- cucumber: (activated with `men test -Dtest=cuce`, which should run junit4 (and therefore also cucumber tests)

this do not work... the cucumber profile do not discover junit4 tests.

I have also asked this question on stack overflow: https://stackoverflow.com/questions/65341427/how-to-set-up-cucumber-with-main-class-and-maven-build

**Comment by marcphilipp** [comment]
It sounds like that is caused by Maven Surefire's auto-detection picking its JUnit Platform provider in both cases. You can either add JUnit Vintage engine to the test classpath to have it find the Cucumber test classes or [force Surefire to use a JUnit 4 provider](https://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html) in your cucumber profile.
