### ISSUE TITLE
Characters not allowed according to XML 1.0 spec are double-escaped

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#2507]
In #2275, we have replaced characters not allowed according to the XML 1.0 spec with their character reference, e.g. `\0` becomes `&#0;`. However, that's still illegal according to [section 4.1 of the spec](https://www.w3.org/TR/REC-xml/#sec-references):

> Characters referred to using character references MUST match the production for Char.

Thus, we either filter them out completely or double-escape them like [Surefire does](https://issues.apache.org/jira/browse/SUREFIRE-456), e.g. `\0` becomes `&amp;#0;`. Since the former would omit information, I think we should do the latter.

## Deliverables

- [ ] Illegal XML characters are "double-escaped"

**Comment by bodewig** [comment]
I may have raised a false alarm here, I'm sorry. When I commented on #2275 I was looking at the intent and not the effect the change had on the generated XML.

When writing attributes you use `XMLStreamWriter.writeAttribute` which already escapes ampersands. So what gets actually written to the XML file is `&amp;#0;` - the result you suggest to achieve anyway. Since you put the rest into CDATA sections, entity references are not expanded when reading the file and you should be safe as well.

**Comment by marcphilipp** [comment]
You're right, I just double-checked. Thanks!
