### ISSUE TITLE
Introduce assertThrowsExactly() in Jupiter assertions

### ISSUE THREAD

**Issue by govi20** [junit-team/junit5#2509]
I have a method which I am testing as below:

```java
    @Test
    void testHttpErrorCodeException() {
        assertThrows(HttpResponseException.class, () -> reThrowSpecificException(500));
        assertThrows(RuntimeException.class, () -> reThrowSpecificException(404));
     }

    public void reThrowSpecificException(int httpsStatusCode) {
        if (httpsStatusCode == 500) {
            throw new HttpResponseException();
        } else {
            throw new RuntimeException();
        }
    }
```

Now if someone modifies the code as below, I feel the second assertion should fail.

```java
    private void reThrowSpecificException(int httpsStatusCode) {
        throw new HttpResponseException();
    }
```
But the second assertion is not failing as the JUnit checks it using `instanceof`. Seems we can add an `assertThrowsExactly(Class<T> expectedType, Executable executable)` to assert on the particular type of exception.

**Comment by sbrannen** [comment]
Tentatively slated for 5.8 M1 for _team discussion_

**Comment by Michael1993** [comment]
As a "workaround", you could extend your assertion like this:
```java
Class<?> klass = assertThrows(RuntimeException.class, () -> reThrowSpecificException(404)).getClass();
assertTrue(klass.equals(RuntimeException.class));
```
because `assertThrows` returns the exception thrown.

It looks redundant but it gets the job done (until `assertThrowsExactly` gets added?).

(I'd also suggest AssertJ as an alternative option, but the issue seems to be focused on JUnit's own assertions.)

**Comment by govi20** [comment]
@Michael1993 I am already using this workaround in my code [ https://github.com/junit-team/junit5/issues/2505#issuecomment-751446470 ], it is nice to have this assertion though as Assertj `assertThatThrownBy(..).isInstanceOf(..)` won't be useful either.

**Comment by Michael1993** [comment]
Sorry, what version of AssertJ are you using? AssertJ offers `assertThatThrownBy(..).isExactlyInstanceOf(..)`.

**Comment by marcphilipp** [comment]
**Team decision:** Introduce `assertThrowsExactly`.

**Comment by sbrannen** [comment]
@terziele, normally when an issue is already assigned to someone (see the upper right corner of this issue), we don't submit a PR for the issue without first asking permission since the assignee may have already begun work on the issue.

In light of the fact that you have already submitted a thorough PR (#2543), I am removing @mmerdes as the assignee.

@mmerdes, I hope this is OK with you and that you have not already started working on it.

**Comment by iautushka** [comment]
@sbrannen Oh, I'm so sorry. I didn't notice that. I'll be more watchful next time.

**Comment by sbrannen** [comment]
Superseded by PR #2543
