### ISSUE TITLE
Improve failure message for assertNull() when toString() results in "null"

### ISSUE THREAD

**Issue by SebbaIndustries** [junit-team/junit5#2523]
## Steps to reproduce

I didn't find any same issues so I hope this isn't a duplicate.

I get `null != null` when running this test.

```java
public class GsonLoreSerializationTest {

    private Gson gson = new Gson();

    private List<String> lore;

    @Test
    public void serializeLore() {
        String nullLore = gson.toJson(lore);
        // null != null??
        Assertions.assertNull(nullLore);

        lore = new ArrayList<>();
        String emptyLore = gson.toJson(lore);
        Assertions.assertEquals(emptyLore, "[]");

        lore.add("Test String");
        String normalLore = gson.toJson(lore);
        Assertions.assertEquals(normalLore, "[\"Test String\"]");
    }

}
```

```
expected: <null> but was: <null>
Expected :null
Actual   :null
<Click to see difference>

GsonLoreSerializationTest > serializeLore() FAILED
    org.opentest4j.AssertionFailedError at GsonLoreSerializationTest.java:19
1 test completed, 1 failed
```
Full stack trace: https://pastebin.com/B0LFx5HF

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.7.0
 - Build Tool/IDE: Gradle 6.7 with IntelliJ IDEA Ultimate 2020.3

## Deliverables

N/A

**Comment by SebbaIndustries** [comment]
Never mind, it was serialized as `"null"` and not `null` sorry for this issue, this was a mistake on my end.

**Comment by sbrannen** [comment]
I'm glad you figured it out.

However, I think you have raised a valid point. The failure message is indeed very confusing.

To avoid such confusion for failures with `assertEquals(...)`, we use `org.junit.jupiter.api.AssertionUtils.formatValues(Object, Object)` which delegates to `org.junit.jupiter.api.AssertionUtils.formatClassAndValue(Object, String)` if the string representations of the expected and actual values are identical.

In the example you have provided, the expected string representation is hard coded to `null` in `org.junit.jupiter.api.AssertNull.failNotNull(Object, String)`.

In order to produce a meaningful failure message for use cases like the one in this issue's description, we could modify `AssertNull.failNotNull(Object, String)` so that it also delegates to `org.junit.jupiter.api.AssertionUtils.formatValues(Object, Object)`.

If we make that change, we would likely want to make similar changes to `assertTrue()`, `assertFalse()`, and any other assertion methods that hard code the expected string representation.

I am therefore re-opening this issue for further discussion.

@junit-team/junit-lambda Thoughts?

**Comment by marcphilipp** [comment]
**Team decision:** Use `formatValues()` for creating the assertion message for `assertNull` (and check if other assertions have a similar issue).
