### ISSUE TITLE
Document implementation of assertEquals() and assertNotEquals() regarding equals()

### ISSUE THREAD

**Issue by juherr** [junit-team/junit5#2567]
I made some tests for the TestNG issue https://github.com/cbeust/testng/issues/2490 and found the same issue on `Assertions.assertNotEquals`.

## Steps to reproduce

https://github.com/cbeust/testng/issues/2490#issuecomment-798894748

## Context

 - Used versions (Jupiter): 5.7
 - Build Tool/IDE: N/A

**Comment by sbrannen** [comment]
Tentatively slated for 5.8 M2 for _team discussion_

**Comment by marcphilipp** [comment]
**Team decision:** Clarify the implementation in the Javadoc of `assertEquals` and `assertNotEquals` similar to `Objects.equal` from the JDK.

**Comment by Marcono1234** [comment]
The point of that TestNG issue was that people misuse the assertion methods to check their `equals` implementations ([example for such misuse](https://lgtm.com/query/6157623132776546027/)). Personally I think it would therefore be better to explicitly state that this is not what the assertion methods are intended for; only documenting the implementation of `assertEquals`, ... might not necessarily prevent people from misusing them, especially when the implications of the implementation are not obvious.

I think it would therefore be better to add something similar to the following to the `Assertions` class documentation instead of describing the implementation details of the assertion methods:
> **Important:** Assertion methods comparing two values for equality, such as `assertEquals`, are *only* intended to test equality for an (un-)expected and an actual result value. They are not designed for testing whether a class correctly implements `equals(Object)`. For example `assertEquals` might return fast when provided with the same object as expected and actual value without calling `equals(Object)` at all.  
Such tests trying to verify the `equals(Object)` implementation should instead be written explicitly and `assertTrue` or `assertFalse` should be used to verify the result, e.g.: `assertTrue(var.equals(var))`, `assertFalse(var.equals(null))`.

What do you think?

**Comment by jbduncan** [comment]
I'm not on the JUnit team, but I agree with @Marcono1234's suggestion!

The Truth team have some similar wording in their [`assertThat(...).isEqualTo(...)`](https://truth.dev/api/1.1.2/com/google/common/truth/Subject.html#isEqualTo(java.lang.Object)) doc, so there's precedence for including this sort of information.

**Comment by marcphilipp** [comment]
@Marcono1234 Sounds good to me! Would you be interested in submitting a PR with that?

**Comment by Marcono1234** [comment]
@marcphilipp, sorry for the delay, I have created #2632 now.

**Comment by bjmi** [comment]
Shouldn't the last assertion be `assertFalse(actual.equals(null))` as one usually is interested in a well-behaved _actual_?
https://github.com/junit-team/junit5/blob/bd7d03f517dfca3730fbd123c5fd4d4b70930129/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java#L50-L51

(This is can be related to #3120.)

**Comment by sbrannen** [comment]
> Shouldn't the last assertion be `assertFalse(actual.equals(null))` as one usually is interested in a well-behaved _actual_?

I wouldn't call it the "last assertion". The "etc." implies that one could continue with that pattern to add `assertFalse(actual.equals(null))` as a 4th assertion along with any other assertions that one deems appropriate.
