### ISSUE TITLE
Failed to see parameter values on parametrized tests

### ISSUE THREAD

**Issue by Nachtfeuer** [junit-team/junit5#2606]
What I'm looking for: displaying test parameters (the values, not the types) when looking at the list of exected tests.
![grafik](https://user-images.githubusercontent.com/11331611/116780562-dbc9c700-aa7d-11eb-9aa3-d6f1e53389e3.png)

 * Using Windows 10
 * Using Netbeans in version 12.2
 * Using Java 11.0.11
 * Using Maven in Version 3.6.3
 * Using Junit 5 in version 5.8.0-M1 (api, engine and params as dependencies)
 * Using Surefire in version 3.0.0-M5 (no configuration part in pom.xml)

## Steps to reproduce

If you change the the "6" to a "5" in the test results you get following
maven output (same also to my Netbeans IDE in the Junit Results Window):

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running magic.system.spline.matcher.ListMatcherTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.064 s <<< FAILURE! - in magic.system.spline.matcher.ListMatcherTest
magic.system.spline.matcher.ListMatcherTest.testDemo(List, boolean)[2]  Time elapsed: 0.003 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at magic.system.spline.matcher.ListMatcherTest.testDemo(ListMatcherTest.java:110)
```

I invested now 2 hours without success to find out how I could manage to see the
parameter values instead of the types (The types I can see in the method itself
being completely useless in the output). From another issue somebody told you
should have a look at following link: https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#Surefire_Extensions_and_Reports_Configuration_for_.40DisplayName

When I'm using this it does not change the effect but the normal method are not
shown anymore. Instead you see "null". 

So official documentation looks so simple but somehow I seem to miss an essential point.
Btw. adding @DisplayName does not change anything (at least for me).
The Named.of were also just a try because somebody told it would help but finally
it did not make any difference.

The tests which should run fine (just simple demo code):
```
    @ParameterizedTest(name = "{index}: data={0}, expected:{1}")
    @MethodSource("provideDemoTestData")
    public void testDemo(final List<Integer> listData, final boolean bExpectedToFail) {
        if (bExpectedToFail) {
            assertFalse(listData.stream().allMatch(entry -> entry % 2 == 0));
        } else {
            assertTrue(listData.stream().allMatch(entry -> entry % 2 == 0));
        }
    }

    private static Stream<Arguments> provideDemoTestData() {
        return Stream.of(
                Arguments.of(
                        Named.of("data", List.of(1, 3, 5)),
                        Named.of("expected to fail", true)),
                Arguments.of(
                        Named.of("data", List.of(2, 4, 6)),
                        Named.of("expected to fail", false))
        );
```

**Comment by Michael1993** [comment]
I'd like to help, but the best I can do is offer some alternatives:
### Would you consider using a different assertion framework (e.g.: AssertJ)?
This would help you assert the actual data, for example: `assertThat(listData).allMatch(i -> i % 2 == 0);` would tell you _exactly_ what went wrong:
```java
java.lang.AssertionError: 
Expecting all elements of:
  [1, 3, 5]
to match given predicate but these elements did not:
  [1, 3, 5]
```
### Would you consider using a different IDE (e.g.: IntelliJ or Eclipse)?
I am asking because it seems that NetBeans does not support JUnit 5 out-of-the-box, and especially not `@DisplayName`. For -reference:
- https://github.com/junit-team/junit5/issues/1314 (DisplayName not working)
- https://issues.apache.org/jira/browse/NETBEANS-4485
However IntelliJ supports the custom DisplayNames quite well:
![image](https://user-images.githubusercontent.com/4085611/117434062-7ddd2980-af2c-11eb-8277-9666f5ec7e29.png)

### Would you consider reading this data from the XML report?
Surefire _does_ report the data you are looking for - just not on the console. You can find the arguments info in `target/surefire-reports`. It looks like this:
```xml
<testcase name="1: data=[1, 3, 5], expected:true" classname="This is the name of the file" time="0.04">
    <failure type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at io.github.michael1993.test.ReproducingTests.testDemo(ReproducingTests.java:21)
]]></failure>
</testcase>
```
Please note that I added the extra `<configuration>` you linked, otherwise it did not show up.

I also tried writing a custom `ConsoleOutputReporter` for surefire but ran out of time/could not make it work.

**Comment by Nachtfeuer** [comment]
I switched over from Netbeans to Intellij and it works much better. Anyway I still have
following issues (not blocking but could be better):
*  the "null" issue remains. I have to use DisplayName on the test class to avoid this.
* Looking at Jenkins for the tests I see for one class with multiple parametrize tests that the name of the method is not used; that means that the #1 (and so on) appears multiple times. In Intellij that is avoid by showing a tree. The Jenkins issue reflect of course the surefire XML. I would have expected that the DisplayName on the method and the definition of the parmaterized annotation are merged. Maybe I do something wrong here.

**Comment by marcphilipp** [comment]
Both of these sound like issues in Maven Surefire. Please raise the topic with them. I'm currently working on a new reporting format that supports the same tree structure as IntelliJ in #373. That will eventually resolve issues like this one (once it's adopted by the relevant reporting tools).
