### ISSUE TITLE
Document that test engines should use a unique namespace for their properties

### ISSUE THREAD

**Issue by juliette-derancourt** [junit-team/junit5#2825]
As mentioned in https://github.com/junit-team/junit5/issues/2819#issuecomment-1029910273, all test engines should prefix the names of their configuration properties with their engine id.

We should document that recommendation in the test engine section of the user guide.

**Comment by sbrannen** [comment]
The prefix doesn't have to be exactly the engine's ID, but it should be unique to the engine (or the entity that develops the engine), much like package names in Java.

For example, JUnit Jupiter doesn't use `junit-jupiter` (its engine ID) as the prefix but rather `junit.jupiter`.

**Comment by sbrannen** [comment]
> We should document that recommendation in the test engine section of the user guide.

That's easier said than done.... since there is no "test engine section" in the user guide. 🤣

The _Advanced Topics_ file has the following commented-out include, but we never actually created that document.

```markdown
////
include::engines.adoc[]
////
```

I suppose I might create the missing Engines file/section with content from the _Registering a TestEngine_ section.
