### ISSUE TITLE
Add way to get test result in `@AfterEach`

### ISSUE THREAD

**Issue by GregJohnStewart** [junit-team/junit5#2842]
Reference Stack Overflow: https://stackoverflow.com/questions/71354431/junit5-get-results-from-test-in-aftereach?noredirect=1#comment126124314_71354431

It makes sense to me to have some way to get the result of the test that was run in the `@AfterEach`. Pass/Fail status would be bare minimum, but would love to be able to get the exception that was thrown.

Having some object I could have as a parameter to the `@AfterEach` to give these would be fantastic.

**Comment by sbrannen** [comment]
The test has not yet completed when an `@AfterEach` method is thrown, since another `@AfterEach` method or an extension could still cause the test to fail.

In other words, it does not make sense to provide a yet-to-be-known completion status for a test that has not yet completed.

If you wish to gain access to an exception thrown during a test, you can implement a `TestExecutionExceptionHandler` extension which is designed for that purpose. If you don't want to create one of those as a top-level class, you can implement one locally as a lambda expression using `@RegisterExtension`.

Does that meet your needs?

**Comment by GregJohnStewart** [comment]
Seems counter-intuitive, I wouldn't expect test logic to exist in an `@AfterEach`, but understand there is a tradeoff there in case of exceptions thrown during cleanup or something.

Might still argue that it is helpful to know the status thusfar, or at least if an exception was thrown.

Does that exception handler get called before or after the `@AfterEach`? It might work but hard to say for sure.

**Comment by sormuras** [comment]
What about using a `TestWatcher`?

https://junit.org/junit5/docs/current/user-guide/#extensions-test-result-processing

**Comment by GregJohnStewart** [comment]
Additionally, finding it super hard to replicate some of the functionality implemented in my `@AfterEach`, as the Object returned by `ExtensionContext.getRequiredTestInstance()` seems to not be the same as the instance used for the test...

**Comment by yangbodong22011** [comment]
This works for me: https://stackoverflow.com/a/76050531/5761134
