### ISSUE TITLE
Add reason alias to @Disabled 

### ISSUE THREAD

**Issue by iblessings** [junit-team/junit5#2843]
## Deliverables

- [ ] Can you please add the `reason` alias in addition to the `value` in the `@Disabled` annotation to improve readability. It will be much easier to read as `@Disabled(reason="Some message")`. Good work to the JUnit5 Team!!!

**Comment by sormuras** [comment]
The Java language does not support aliases in annotations.

You may however omit the `value = ` for "single-element annotations" as specified here: https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-9.7.3

Long form: `@Disabled(value = "Because...")`
Short form: `@Disabled("Because...")` 

> Good work to the JUnit5 Team!!!

Merci! 🤓

**Comment by iblessings** [comment]
Okay cool thanks will do that. Cheers!
