### ISSUE TITLE
define AfterTestExecutionCallback class in pom.xml

### ISSUE THREAD

**Issue by roydekleijn** [junit-team/junit5#2846]
Hello,

Can we define AfterTestExecutionCallback class in pom.xml using the surefire-plugin ?

Roy

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

In any case, the answer to your question is "no, you cannot register extensions in `pom.xml`.

But you can register extension using Java's `ServiceLoader` mechanism.

See [Automatic Extension Registration](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic) in the User Guide for details.

**Comment by roydekleijn** [comment]
Thanks for your answer!
