### ISSUE TITLE
Failed assumption in @BeforeEach gets suppressed by exception in @AfterEach

### ISSUE THREAD

**Issue by ZeroOne3010** [junit-team/junit5#2919]
Greetings! I tried to conditionally suspend a set of tests by adding a failing assumption into a method annotated with the `@BeforeEach` annotation, but much to my surprise the test set failed anyway. Taking a closer look revealed the it was due to an `@AfterEach` annotated method throwing an exception and suppressing the `TestAbortedException` thrown by `@BeforeEach`. 

## Steps to reproduce

Please try the following minimal test class:

```java
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.List;
import static org.junit.jupiter.api.Assertions.fail;
import static org.junit.jupiter.api.Assumptions.assumeFalse;

class AssumptionTest {

    private List<String> strings;

    @BeforeEach
    void setup() {
        assumeFalse(strings == null);
    }

    @AfterEach
    void teardown() {
        System.out.println("There were this many strings: " + strings.size());
    }

    @Test
    void test() {
        // This test correctly does not get executed but is still marked as failed due to an exception thrown in the `teardown` method.
        fail();
    }
}
```

In the end the `test` is marked as failed because the `teardown` method throws a `NullPointerException`, and the stack trace (wildly cut here) says the `TestAbortedException` is "Suppressed":

```
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "this.strings" is null
	at AssumptionTest.teardown(AssumptionTest.java:19)
	Suppressed: org.opentest4j.TestAbortedException: Assumption failed: assumption is not false
```

## Expected behavior

I would expect that in case a `@BeforeEach` method aborts, an `@AfterEach` annotated method would not be executed. After all, after _what_ would it run, when there was no test executed? It seems like it isn't currently true to its name.

Alternatively, I would expect the exceptions to be other way around: there could have been a `TestAbortedException` with a suppressed `NullPointerException`.

Third alternative would be to allow for some configurability to `@AfterEach` methods, something like `@AfterEach(runIfBeforeMethodFailsOrAborts=false)`.

The fourth option, of course, is that the current behavior is due to deliberate and careful consideration and must not be changed, in which case I just need to be educated and this issue closed. :) 

## Other considerations

If this issue causes any action to be taken in the code base, I would expect `@BeforeAll` and `@AfterAll` methods would need to be reworked to conform to whatever was decided for `@BeforeEach` and `@AfterEach`, including a situation where a `@BeforeEach` would fail and could cause an `@AfterAll` method to not get executed.

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit Jupiter API 5.8.2
 - Build Tool/IDE: IntelliJ IDEA 2022.1.1 (Ultimate Edition) Build #IU-221.5591.52, built on May 10, 2022

**Comment by sbrannen** [comment]
This is the expected behavior. See #1313 for details.

> I would expect that in case a `@BeforeEach` method aborts, an `@AfterEach` annotated method would not be executed. After all, after _what_ would it run, when there was no test executed?

In JUnit Jupiter we follow a simple rule when deciding if "after" lifecycle methods get invoked: if any "before" lifecycle method at the same level was invoked, Jupiter invokes all "after" lifecycle methods at the same level.

The rationale is that "before" lifecycle methods may set up something in the environment (for example, file system, database, etc.) that **has** to be cleaned up in a corresponding "after" lifecycle method. If a failed assertion or failed assumption in a "before" lifecycle method caused such an "after" lifecycle method not to be invoked, that would lead to improper state in the environment.

See the following for the logic:

https://github.com/junit-team/junit5/blob/a6683c457b018ede0e25b994d9d655371f934004/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestMethodTestDescriptor.java#L131-L145

https://github.com/junit-team/junit5/blob/a6683c457b018ede0e25b994d9d655371f934004/junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/ThrowableCollector.java#L88-L100

> The fourth option, of course, is that the current behavior is due to deliberate and careful consideration and must not be changed, in which case I just need to be educated and this issue closed. :)

In light of that, I am closing this issue. 😄
