### ISSUE TITLE
Execution of a third-level Nested class only executes methods of the top-level class

### ISSUE THREAD

**Issue by tru3v0r** [junit-team/junit5#2989]
When trying to launch a third-level @Nested class (a class inside a class inside the top-level class) using Maven, it only executes the children methods of that top-level class and ignores everything else.

In this case, the execution logs show only two tests executed.
The XML report contains these two testcase tags.

## Steps to reproduce

The command I used to run the test:
`mvn test -Dtest="com.baeldung.junit5.nested.TestingAStackDemo$WhenNew$afterPushing"`

The class: 
[TestingAStackDemo.java.txt](https://github.com/junit-team/junit5/files/9198692/TestingAStackDemo.java.txt)

## Context

 - Used versions: JUnit Jupiter 5.8.2
 - Build Tool: Maven 3.8.6
 - JDK:
     - java 11.0.13 2021-10-19 LTS
     - Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
     - Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)
 - IDE: IntelliJ IDEA 2021.2.4 (Ultimate Edition)
 
## Deliverables

The execution logs:
[execution_log.txt](https://github.com/junit-team/junit5/files/9198707/execution_log.txt)

The report:
[TEST-com.baeldung.junit5.nested.TestingAStackDemo.xml.txt](https://github.com/junit-team/junit5/files/9198717/TEST-com.baeldung.junit5.nested.TestingAStackDemo.xml.txt)

**Comment by sbrannen** [comment]
It sounds like Surefire might be filtering out those nested test classes based on their names.

See the [user guide](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-filter-test-class-names) for details.

What happens if you rename the nested test classes so that they have an appropriate `Test` prefix or suffix?

Related Issues:

- #1378

**Comment by tru3v0r** [comment]
I suffixed both WhenNew and AfterPushing with "Test", the behavior remains the same.

Tried both commands, still only 2 tests run:
- `mvn test -Dtest="com.baeldung.junit5.nested.TestingAStackDemo$WhenNewTest$afterPushingTest"`
- `mvn test -Dtest="com.baeldung.junit5.nested.TestingAStackDemo$WhenNew$afterPushing"`

The class file with suffixes:
[TestingAStackDemo-suffixed.java.txt](https://github.com/junit-team/junit5/files/9199028/TestingAStackDemo-suffixed.java.txt)

I forgot to say that running the top-level class via IntelliJ works:
![image](https://user-images.githubusercontent.com/80819010/181252089-8050aa5b-4227-43bf-8d0f-272ed95e385c.png)

**Comment by sbrannen** [comment]
What happens if you override Surefire's exclude rules as [documented here](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-filter-test-class-names)?

**Comment by tru3v0r** [comment]
I added the exclusion snippet to my project pom file, it still runs both methods but no sign of nested class (I suffixed the top-level class as well and tried prefixing instead as well)

**Comment by sbrannen** [comment]
> I added the exclusion snippet to my project pom file, it still runs both methods but no sign of nested class (I suffixed the top-level class as well and tried prefixing instead as well)

Thanks for experimenting.

Please provide a minimal sample project that we can download and run if you'd like us to investigate further (for example a GitHub repo).

**Comment by tru3v0r** [comment]
My pleasure.

You can find the whole code here: https://github.com/tru3v0r/junit5-annotations

**Comment by khmarbaise** [comment]
I've taken a look into your referenced project.

1. Why do you use maven-plugin-api as a dependency? This is not correct.
2. Why do you use maven-surefire-plugin as a dependency? This is not correct.
3. You are using an very old maven-surefire-plugin version which does not support JUnit Jupiter. The first release which supports JUnit Jupiter is 2.22.2. But I strongly recommend to use the most recent 3.0.0-M7 instead.
4. You should not define platform-surefire-provider on your own for surefire (apart from using different versions) . Let maven-surefire-plugin do it work on it's own.
5. You should remove JUnit 4 because the code only uses an `assertTrue` once. 

It's easier to use junit jupiter via BOM like this:

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>5.8.2</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
That removes the need to define a property for all needed dependencies. You can simply add the dependencies of JUnit Jupiter like this:
```xml
  <dependencies>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
    </dependency>
  </dependencies>
```

I have created a pull request for your project @tru3v0r and cleaned up several things... 

After the cleanup you can run/select your tests via:
```
mvn clean test -Dtest='com.baeldung.junit5.nested.TestingAStackDemoTest$WhenNewTest$AfterPushingTest'
```
The following:
```
mvn test -Dtest="com.baeldung.junit5.nested.TestingAStackDemo$WhenNew$afterPushing
```
can not run tests because the name `WhenNew` does not exist only `WhenNewTest` (nested class).

Furthermore be carefull about using the right quoting character because on some platforms (lilke linux, mac) the double quotes combined with `$` could procude strange results (interpolation of environment variables)..

```
mvn clean test -Dtest='com.baeldung.junit5.nested.TestingAStackDemoTest$WhenNewTest'
mvn clean test -Dtest='com.baeldung.junit5.nested.TestingAStackDemoTest'
```
If I use your example: `mvn clean test -Dtest='com.baeldung.junit5.nested.TestingAStackDemo$WhenNew$afterPushing'`

I will get an error message:
```
[INFO] --- maven-surefire-plugin:3.0.0-M7:test (default-test) @ junit5-annotations ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.830 s
[INFO] Finished at: 2022-07-27T17:14:30+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project junit5-annotations: No tests matching pattern "com.baeldung.junit5.nested.TestingAStackDemo$WhenNew$afterPushing" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
```

**Comment by tru3v0r** [comment]
Hi and thank you for your help.
I merged your PR to my main branch but I still get a ClassNotFoundException when trying to execute maven commands : 
```
There was an error in the forked process
java.lang.ClassNotFoundException: org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
```

**Comment by khmarbaise** [comment]
What exactly have you tried to execute ? Please post the full command you've tried to execute... ?

**Comment by klay11K** [comment]
@tru3v0r Hi, has this problem been solved yet? I am having the same problem and hope I can get your help.
