### ISSUE TITLE
Brief Question About JUnit Internal Interface

### ISSUE THREAD

**Issue by alinebrito** [junit-team/junit5#305]
Dear JUnit developers,

I am a master student at UFMG, Brazil. Currently, I am researching the use of internal interfaces by client projects. I mean, public interfaces for use only by internal modules (e.g., org.junit.internal.runners.statements.Fail).

In my research, I found 145 internal interfaces in JUnit (see the list at: [Internal Interfaces JUnit](https://www.dropbox.com/s/1n9azd2hyqxqd42/)). By mining data provided by the [Boa Language and Infrastructure](http://boa.cs.iastate.edu/), I also found 778 client projects that are using these internal interfaces. Therefore, these internal interfaces are usual in other projects.

1. Did you know that internal interfaces are used by clients?
2. From the presented interfaces, there is some interface that is a candidate to be promoted to the public one?

**Comment by smoyer64** [comment]
Boa tarde @alinebrito 

I'm not part of the JUnit 5 team, but they've published information about their API usage at http://junit.org/junit5/docs/current/user-guide/#api-evolution.  I *am* an extension developer and hope that I'm providing useful feedback as the APIs are finalized.  Right now, most of the APIs are marked experimental.  And there are plenty that are internal only - if you're using a JUnit 5 API that's from a package other than junit5-api, you're making a call that you shouldn't be.

I think your research is interesting as this is a very common problem (even to the point of people still using com.sun packages).  Hopefully separating the API and implementation will result in less coupling to the internal API - which in turn allows dramatic changes to the implementation without the client projects breaking.

Can't wait to hear what additional details the JUnit 5 team provides.

**Comment by alinebrito** [comment]
Hi @smoyer64 ,

Thanks for the answer! Your feedbak is very useful for our research. We are analyzing the internal interfaces of the JDK also, we found 5K projects using sun interfaces.

**Comment by jbduncan** [comment]
Hi @alinebrito.

I don't think @smoyer64 has explicitly pointed this out, but it looks to me that all the JUnit 5 classes in your .xlsx file are in a package with the name `internal`, which means they should be annotated with `@API(Internal)`, and in turn meaning they're internal to JUnit 5 and not part of its public API.

I'm not part of the JUnit 5 team either, so you'll have to wait for confirmation and/or more details from the them directly about this. :smile:

**Comment by alinebrito** [comment]
Hi @jbduncan 

Thank you for your feedback!

That's right, all interfaces in the list  have `internal` package.  I mean, we researched only clients that use JUnit interfaces  (`junit.*` and `org.junit.*`)  with the `internal` package.

**Comment by marcphilipp** [comment]
I didn't have time to go through the list, yet. However, I took a quick glance and there are no JUnit 5 classes on that list. There are some JUnit 4 classes and some classes thatlook like they belong to the Eclipse plugin that is not maintained by us.

**Comment by alinebrito** [comment]
Hi @marcphilipp 

I think there's noise in my query, thanks for the feedback!  I removed the `junit.extensions.eclipse.*` prefix (this is the new list: [Internal Interfaces JUnit] (https://www.dropbox.com/s/m711xw7b4j8r626/)). I found  117 internal interfaces and  774 client projects that are using these internal interfaces.  I used the `junit.*` prefix to clients on older versions (e,g,. junit.framework.TestCase).

**Comment by smoyer64** [comment]
Hi @alinebrito 

Here's some more noise in your query:

JUnit <=3 used junit.*
JUnit 4 uses org.junit.*
JUnit 5 uses org.junit.gen5.*

Note that this is likely to changes ... there's a long, ongoing discussion in #286.

**Comment by alinebrito** [comment]
Hi @smoyer64 

Thank you for your help! That's right, the result has all customers. I mean, all the projects that used interfaces with these prefixes (`junit.*`, `org.junit.*`) and `*.internal.*` package. I did not research the use of classes with `@API(Internal)`, yet.

**Comment by marcphilipp** [comment]
> Did you know that internal interfaces are used by clients?

Yes, we are aware that many of the originally internal interfaces are used by clients. It's one of the reasons why we're using a different approach of annotating APIs instead of using package names for JUnit 5.

> From the presented interfaces, there is some interface that is a candidate to be promoted to the public one?

The following classes/interfaces have already been promoted. The original files have been kept but deprecated to maintain backwards compatibility.

- org.junit.internal.AssumptionViolatedException -> org.junit.AssumptionViolatedException
- org.junit.internal.matchers.TypeSafeMatcher -> org.hamcrest.TypeSafeMatcher
- org.junit.internal.runners.JUnit4ClassRunner -> org.junit.runners.BlockJUnit4ClassRunner
- org.junit.internal.matchers.StringContains.containsString -> org.hamcrest.CoreMatchers.containsString
- org.junit.internal.runners.InitializationError -> org.junit.runners.model.InitializationError

**Comment by alinebrito** [comment]
Hi @marcphilipp 

Thank you for help! This information is very useful for my research.

**Comment by smoyer64** [comment]
I hadn't really thought it through before but this thread brings up an interesting question.  What can Java library developers do to make sure internal APIs aren't used by developers?  And a related question is whether it's worth it.

One tact would be to make it difficult on the developer to access the APIs ... randomly obfuscating the internal classes for each release would effectively make the cost too high (due to the amount of rework that would be required to keep up).  Client development would also take much longer, even with source code available, since you'd have to actually find the classes and methods you wanted to use.

Another tact is to hide the classes like the [Lombok Project](https://github.com/rzwitserloot/lombok) does.  Using a custom ClassLoader to "unpack" classes you don't want clients to know about seems a bit extreme to me.

With the adoption of @API, I think there are a couple better solutions.  In theory, we can do something to warn the developer ... or even break their code during the build.  Would a custom javaagent help?  Can we define the API checking via a /META-INF/services definition?  Even a scanner that warned when someone was using an internal API would be better than nothing.

**Comment by sbrannen** [comment]
@smoyer64,

Java Module support coming with Java 9 will make it possible to address some of those issues; however, that's only useful if everything is running as a _module_.

In any case, we already have issues to address these topics:

- #144 
- #216
