### ISSUE TITLE
Invert equality check?

### ISSUE THREAD

**Issue by shmosel** [junit-team/junit5#3120]
When comparing abstractions (e.g. Map) via `assertEquals(expected, actual)`, it's more likely that `actual` is a custom class. If there's a bug in the `equals()` implementation, it could be caught by calling `actual.equals(expected)` instead of the inverse.

For example, here's an implementation of Map.Entry that violates the `equals()` contract:
```java
class EmptyEntry<K, V> implements Map.Entry<K, V> {
    @Override public K getKey() { return null; }
    @Override public V getValue() { return null; }
    @Override public V setValue(V value) { return null; }
}
```
This assertion passes:
```java
assertEquals(new AbstractMap.SimpleEntry<>(null, null), new EmptyEntry<>());
```
This assertion fails:
```java
assertEquals(new EmptyEntry<>(), new AbstractMap.SimpleEntry<>(null, null));
```
Shouldn't it work the other way?

**Comment by marcphilipp** [comment]
> it's more likely that `actual` is a custom class.

I'm not convinced that's generally the case.

I guess `assertEquals()` could check both `actual.equals(expected)` and `expected.equals(actual)` but that's unnecessary in most cases.

How about a new assertion that does so instead, e.g. `assertEqualsSymmetrically()`?

**Comment by jbduncan** [comment]
@shmosel Please correct me if I'm wrong, but it sounds like you're after an assertion that checks that `EmptyEntry.equals()` has been implemented correctly.

If so, then I think having an assertion that works similarly to [`EqualsTester`](https://javadoc.io/doc/com.google.guava/guava-testlib/latest/com/google/common/testing/EqualsTester.html) from [guava-testlib](https://search.maven.org/artifact/com.google.guava/guava-testlib/31.1-jre/jar), or [EqualsVerifier](https://jqno.nl/equalsverifier/) would be a better option. This would allow all edge cases of a good `equals()` implementation to be tested properly, like ensuring that `equals(null) == false`.

**Comment by shmosel** [comment]
Realizing what needs to be checked is half the battle. I actually wrote a test like this and forgot it was necessary to implement `equals()`. Wouldn't it be better if we could catch a mistake like that for free?

**Comment by jbduncan** [comment]
@shmosel Indeed! Though my gut feeling is incorporating this check into e.g. every call to `assertEquals` would allow down large test suites too much, but I'll leave that to the JUnit maintainers to decide and profile. :)

**Comment by marcphilipp** [comment]
**Team decision:** The goal of `assertEquals()` in Jupiter is general-purpose, analogous to `Objects.equals()`. If you wish to check both directions, you can invoke `assertEquals(a, b)` and `assertEquals(b, a)` (same as with `Objects.equals`) and extract that into your own assertion method for reuse.

The same applies to verification of the contract of `equals()` and `hashCode()`. As mentioned in https://github.com/junit-team/junit5/issues/3120#issuecomment-1368217635 there are dedicated libraries that already address that use case.

**Comment by bjmi** [comment]
Is there a reason why JUnit 5 uses _expected_ for equality assertions and not _actual_ as other unit testing frameworks and assertion libraries do? TestNG even do a _symmetric_ equality check.
Is it because the predecessor JUnit 4 did it that way or is there a persuasive rationale for this?
Otherwise please reconsider it also for JUnit 5 although it would break some odd tests.
- JUnit 5 (5.9.3)
[`expected.equals(actual)`](https://github.com/junit-team/junit5/blob/bd7d03f517dfca3730fbd123c5fd4d4b70930129/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertionUtils.java#L110)

- TestNG (7.8.0)
Both [`expected.equals(actual)`](https://github.com/testng-team/testng/blob/c7e289b84bf8d4b0ad575bd19156cefc8bfa3125/testng-asserts/src/main/java/org/testng/Assert.java#L180) and [`actual.equals(expected)`](https://github.com/testng-team/testng/blob/c7e289b84bf8d4b0ad575bd19156cefc8bfa3125/testng-asserts/src/main/java/org/testng/Assert.java#L180)

- Google Truth (1.1.4)
[`actual.equals(expected)`](https://github.com/google/truth/blob/def16b1d5ffc226fe0564a9b2edd50fd0aa52a25/core/src/main/java/com/google/common/truth/Subject.java#L242)

- AssertJ (3.24.2)
[`actual.equals(expected)`](https://github.com/assertj/assertj/blob/8bc21a44244c1b9897c0ed5711bfd44c31abd223/assertj-core/src/main/java/org/assertj/core/internal/StandardComparisonStrategy.java#L108)

- Kotlin Test (1.8.22)
[`actual == expected`](https://github.com/JetBrains/kotlin/blob/e6633d3d9214402fcf3585ae8c24213a4761cc8b/libraries/kotlin.test/common/src/main/kotlin/kotlin/test/Assertions.kt#L671) (Note: `==` operator calls _equals()_ in Kotlin)

**Comment by sbrannen** [comment]
> Is it because the predecessor JUnit 4 did it that way or is there a persuasive rationale behind this?

Yes, that's exactly the reason.

When we first introduced `assertEquals` in JUnit Jupiter, I copied and modified the existing logic from JUnit 4.

There was no rationale other than keeping it similar to JUnit 4.
