### ISSUE TITLE
Add possibility to disable all tests in a class except for one

### ISSUE THREAD

**Issue by mp911de** [junit-team/junit5#346]
Maybe you know this feature from Sound mixers (`Solo`) or Spock (`@IgnoreRest`) which mutes everything (within the context) else except the one thing you want to inspect. That's quite handy for inspecting tests so you don't need to add `@Ignore`/`@Disabled` to the other tests/steps within your test class.

Some IDEs allow selective execution but in some cases it's quite hard.

**Comment by marcphilipp** [comment]
Have you tried to implement this as an extension?

**Comment by mp911de** [comment]
Haven't tried yet but I think this feature might enjoy a broader interest. It isn't essential but adds some sugar to the programming model.

**Comment by sbrannen** [comment]
Why don't you give it a try by implementing a custom annotation that is supported by an extension that implements the `ContainerExecutionCondition` and `TestExecutionCondition` APIs, akin to what [DisabledCondition](https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/DisabledCondition.java) does?

**Comment by mp911de** [comment]
Mainly because I stumbled yesterday upon that one and I hadn't a chance to get wet with JUnit 5 extensions.

**Comment by sbrannen** [comment]
Well, there's no time like the present!

By the way, my previous question was actually intended to be a rhetorical question. In other words, it was more of a suggestion than a question. 😉

**Comment by smoyer64** [comment]
This use-case intrigued me so I threw a DisableRestExtension together ... if you annotate one or more tests with @DisableRest, then only those tests (within a class) run.  It seems theoretically possible to extend this to test classes since you already have to stash a boolean in the parent's store indicating a that a class has at least one method so annotated.

This brings up an interesting question of what to do with potential errors.  I trap cases where the test developer puts @DisableRest on a method that doesn't also have @Test and throw a PreconditionViolationException.  This exception seems to be wrapped in a ConditionEvaluationException but I can't throw a ConditionEvaluationException because that class is only available while tests are being run.  And should putting @DisableRest on a method without @Test be considered an error to begin with?

**Comment by sbrannen** [comment]
@smoyer64, glad you got a prototype working.

Regarding error handling, in general, I'd ignore the use of an annotation anywhere other than where it makes sense.

**Comment by smoyer64** [comment]
Okay ... I guess the person running the tests would notice that the (supposedly) disabled tests all ran but it seems a bit counter-intuitive to me.

On another note, does the team have an IRC channel or something where you all talk?  I have a bunch of questions related to my AfterDiscoveryCallback PoC and I'd rather not hijack threads (like this one) or create new issues for philosophical and operational questions.

**Comment by sbrannen** [comment]
> Okay ... I guess the person running the tests would notice that the (supposedly) disabled tests all ran but it seems a bit counter-intuitive to me.

Well, I once saw JUnit 4's `@Ignore` on a method in a production class. The team's Ant build allowed it because they compiled production code with `junit.jar` on the classpath.

My point: people will always find a way to _do the wrong thing_. 😉 

If the community is outraged by the lack of _validation_ for such things, that can always be added later, but I prefer not to bake in too much validation unnecessarily.

**Comment by sbrannen** [comment]
> On another note, does the team have an IRC channel or something where you all talk?

We currently use a popular chat client to discuss amongst ourselves, but that is a closed channel.

If there are topics you'd like to discuss, the best option is to open a dedicated issue for the topic.

**Comment by smoyer64** [comment]
I've published the PoC @DIsableRest and it's associated extension at https://github.com/selesy/junit5-extensions.  Sorry for the lack of Javadocs (see the tests for now).

**Comment by marcphilipp** [comment]
@smoyer64 Is this a candidate for junit-pioneer?

**Comment by sbrannen** [comment]
@marcphilipp, to answer your question....

yep, it's a candidate for JUnit Pioneer. 😉 

https://github.com/junit-pioneer/junit-pioneer/issues/71

**Comment by marcphilipp** [comment]
> Some IDEs allow selective execution but in some cases it's quite hard.

@mp911de I know this issue is quite old... 😉 Do you remember concrete use cases where it was actually hard to selectively execute a single test?

**Comment by mp911de** [comment]
The issue originated in a time with little IDE support and selection of individual test methods to run was not possible. Now, with better tooling and UniqueId paths this obstacle is gone and I think we can close this ticket.

**Comment by sbrannen** [comment]
@mp911de, thanks for the prompt feedback.

Based on that and the fact that https://github.com/junit-pioneer/junit-pioneer/issues/71 covers this topic as well, I'm closing this issue.

**Comment by snicoll** [comment]
I think the milestone should be cleared on this one.

**Comment by sbrannen** [comment]
Indeed. Thanks!
