### ISSUE TITLE
Document that `DiscoverySelectorResolver` is an internal utility

### ISSUE THREAD

**Issue by holly-cummins** [junit-team/junit5#3516]
I've noticed what seems to be an inconsistency in the [javadoc for DiscoverySelectorResolver](https://junit.org/junit5/docs/5.10.0/api/org.junit.jupiter.engine/org/junit/jupiter/engine/discovery/DiscoverySelectorResolver.html). 

> [@API](https://apiguardian-team.github.io/apiguardian/docs/1.1.2/api/org/apiguardian/api/API.html)([status](https://apiguardian-team.github.io/apiguardian/docs/1.1.2/api/org/apiguardian/api/API.html#status())=[INTERNAL](https://apiguardian-team.github.io/apiguardian/docs/1.1.2/api/org/apiguardian/api/API.Status.html#INTERNAL),
     [since](https://apiguardian-team.github.io/apiguardian/docs/1.1.2/api/org/apiguardian/api/API.html#since())="5.0")
public class DiscoverySelectorResolver
> ...
>
> This class is the only public entry point into the discovery package.

Is it internal, and only to be used by JUnit libraries, or is it a public entry point that other code can use?

**Comment by sbrannen** [comment]
> Is it internal, and only to be used by JUnit libraries, 

Yes, that is the intention.

It is only `public` because `JupiterTestEngine` needs access to it.

Though, I agree: the use of the term "public" is misleading in the Javadoc.

As a side note, the `JavaElementsResolver` mentioned in the opening sentence no longer exists.

In light of that, I'll repurpose this ticket to update the Javadoc of `DiscoverySelectorResolver`.

Thanks for bringing this to our attention.
