### ISSUE TITLE
How to use OR operator in maven command for junit5 tags

### ISSUE THREAD

**Issue by johnysv** [junit-team/junit5#3531]
I am using SerenityBDD with Junit 5. I want to pick a test case which has either of one tags.

@ExtendWith(SerenityJUnit5Extension.class)
@Tag("testTagOne")
public class A extends SomeClass {

    @Test
    @Tag("testTagOne")
    public void test01() {
         System.out.println("test one");
    }

    @Test
    @Tag("testTagOne")
    public void test02() {
         System.out.println("test two");
    }
}

In junit 4 I will be passing -Dtags=@testTagOne or @testTagTwo in a maven command. How to pass in -Dgroups of junit5?

**Comment by sbrannen** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). We prefer to use the issue tracker only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

----

In addition, I'd suggest you read the official Maven Surefire documentation regarding JUnit 5 support.

**Comment by marcphilipp** [comment]
@johnysv It would be `-Dgroups=testTagOne|testTagTwo`.

Docs: https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#filtering-by-tags

**Comment by johnysv** [comment]
> @johnysv It would be `-Dgroups=testTagOne|testTagTwo`.
> 
> Docs: https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#filtering-by-tags

Thank you. It worked with -Dgroups=testTagOne,testTagTwo
