### ISSUE TITLE
assertEquals for map comparison does not report diff correctly

### ISSUE THREAD

**Issue by ikhvostenkov** [junit-team/junit5#3866]
## Steps to reproduce

Run the test below. This test fails, but this is really hard to see where the error is, as IntelliJ reports that the contents are identical (see screenshot).

```java
    @Test
    void headers() {
        assertEquals(Map.of(
                "content-length", List.of(11),
                "host", List.of("example.com")
        ), Map.of(
                "content-length", List.of("11"),
                "host", List.of("example.com")
        ));
    }
```

![image](https://github.com/junit-team/junit5/assets/861305/6a408f75-dda1-4185-a8c0-127ce2b3c0ee)
<img width="2557" alt="image" src="https://github.com/junit-team/junit5/assets/861305/13afcca0-ee77-44eb-bf30-f1ffca0c5bdc">

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit 5.9.2
 - Build Tool/IDE: IntelliJ IDEA 2023.3.3

## Deliverables

- [ ] ...

**Comment by daniel-matheis-vivavis** [comment]
But how would you see that assertEquals could be improved here?
The cause for "looking same" is the implementation of toString for the inequal Integer 11 and the String "11".

**Comment by sbrannen** [comment]
As alluded to by @daniel-matheis-vivavis, JUnit Jupiter's assertions invoke `toString()` on the expected and actual arguments to generate failure messages. 

If the two arguments are not equal but have identical `toString()` representations, JUnit Jupiter includes the class name and system identity hash code along with the `toString()` representation in the failure message.

In your screenshot, you can see that the class names and `toString()` representations are identical; however, the hash codes are different. From that you can infer that the objects are not equal even though they have identical `toString()` representations.

Since JUnit Jupiter does not generate customized `toString()` representations, that's why you see the output you've described.

Please note that we typically suggest the use of a more powerful assertion library when the feature set in JUnit Jupiter's assertions proves insufficient.

For this particular scenario, I suggest you use AssertJ.

Given:

```java
	@Test
	void headersAssertJ() {
		assertThat(Map.of("content-length", List.of(11), "host", List.of("example.com")))
			.isEqualTo(Map.of("content-length", List.of("11"), "host", List.of("example.com")));
	}
```

The exception message is:

```
org.opentest4j.AssertionFailedError: 
expected: {"content-length"=["11"], "host"=["example.com"]}
 but was: {"content-length"=[11], "host"=["example.com"]}
```
