### ISSUE TITLE
Build failure by missing resource

### ISSUE THREAD

**Issue by aylenaf** [junit-team/junit5#4041]
## Failure Log

```
Resource missing. [HTTP GET: https://repo.maven.apache.org/maven2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.pom]

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'junit5'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.ajoberstar.grgit:grgit-core:4.0.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.1/grgit-core-4.0.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > net.nemerosa.versioning:net.nemerosa.versioning.gradle.plugin:2.14.0 > gradle.plugin.net.nemerosa:versioning:2.14.0
```

## Context

 - Used versions (Jupiter/Vintage/Platform): org.junit.jupiter:junit-jupiter:5.7.1 and org.junit.jupiter:junit-jupiter:5.7.2
 - Build command: ./gradlew jar

**Comment by sbrannen** [comment]
@aylenaf, first and foremost, please tell us what you are trying to achieve.

Are you trying to build your own project?

Are you trying to build JUnit 5 from the sources?

Also, please note that JUnit 5.7.1 is no longer supported.

**Comment by marcphilipp** [comment]
This looks to be caused by [JCenter shutting down](https://blog.gradle.org/portal-jcenter-impact). The Gradle Plugin Portal used to redirect to JCenter when an artifact such as `grgit-core` wasn't deployed directly there. But since July it now redirects to Maven Central. The build now fails because `org.ajoberstar.grgit:grgit-core:4.1.1` isn't available from there. A fix would be to update the `net.nemerosa.versioning` plugin to 3.0.0 or later. However, since there are no plans to do another 5.7.x release, we're not maintaining the `releases/5.7.x` branch any more.
