### ISSUE TITLE
Incorrect order of print statements when using `@Suite` and `@BeforeSuite` with IntelliJ IDEA

### ISSUE THREAD

**Issue by wind57** [junit-team/junit5#4047]
I'm using `junit-bom`:

```xml
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>5.11.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
</dependencyManagement>
```

And I have two simple classes:

```java
@Suite
@SelectClasses(TestClass.class)
public class MySuite {

	public static int x = 0;

	@BeforeSuite
	static void beforeSuite() {
		x = 42;
		System.out.println("before suite");
	}

	@AfterSuite
	static void afterSuite() {
		System.out.println("after suite");
	}

}
```

and 

```java
public class TestClass {

	@Test
	void test() {
		System.out.println("testing : " + MySuite.x);
	}

}
```

If run `MySuite` from IntelliJ (latest version available: Build #IU-241.19072.14, built on August 8, 2024), I get such an output:

```
testing : 42
before suite
after suite
```

While logically everything is correct, the _order_ of the output is not: `before suite` should come before `testing: 42`. 

The interesting part is that if I run the _package_ where this `MySuite` resides, the output is now in the correct order.

Is this expected?

Thank you.

**Comment by sbrannen** [comment]
Hi @wind57,

Congratulations on raising your first issue for JUnit 5! 👍 

When I run your example in Eclipse IDE, I get the following output on the console.

```
before suite
testing : 42
after suite
```

And since you also see `testing : 42` instead of `testing : 0` in IntelliJ, I assume that the different console output you see is perhaps related to how IntelliJ handles/redirects `System.out`.

In light of that, I am closing this issue, but feel free to raise an issue directly in the [IntelliJ IDEA issue tracker](https://youtrack.jetbrains.com/issues?q=project:%20%7BIntelliJ%20IDEA%7D).

Cheers,

Sam
