### ISSUE TITLE
Concurrency issues when adding/registering dynamic tests

### ISSUE THREAD

**Issue by mfulton26** [junit-team/junit5#417]
Adding `TestDescriptor` children concurrently causes some children to be abandoned: `AbstractTestDescriptor.children` is a `LinkedHashSet`. `TestPlan` also has concurrency issues (e.g. `allIdentifiers` is a `LinkedHashMap`).

This causes issues with dynamic tests, etc. add/registered in parallel with calls to `TestDescriptor.addChild(TestDescriptor)` and calls to `EngineExecutionListener.dynamicTestRegistered(TestDescriptor)`.

**Comment by sbrannen** [comment]
@mfulton26, thanks for raising the issue.

I've committed some preliminary improvements regarding concurrency in 7a72e1c0a4ac268f3d7765dd8c426262d7dfb697.

So please give one of the upcoming snapshots a try and let us know if this already solves your issues.

I'll close this issue for now, but if you still encounter issues with concurrency in the `TestPlan` or `AbstractTestDescriptor`, please report those issues here so that we can reopen this ticket and address the issues properly.

Cheers,

Sam

**Comment by mfulton26** [comment]
Will do. Thank you.
