### ISSUE TITLE
Use java.nio.file.Path internally instead of java.io.File

### ISSUE THREAD

**Issue by jbduncan** [junit-team/junit5#466]
As I discussed in https://github.com/junit-team/junit5/commit/4fa01d554e14069ee0655e7fad23a9b9ea6bc8b9#commitcomment-18607421, I think it's worth considering switching from using `java.io.File` in JUnit 5 classes to `java.nio.file.Path` and `java.nio.file.Files` instead, at least by default.

I realised that it's easy for inline comments in GitHub commits to get lost, so I decided to start an issue to continue this conversation.

**Comment by sbrannen** [comment]
@jbduncan, thanks for raising the issue!

We discussed the topic amongst the team and have decided to follow your advice to use `Path` instead of `File` internally (wherever feasible).

Cheers,

Sam

**Comment by jbduncan** [comment]
Wow, this is great news!

I understand this is project is keeping you and the rest of the team very busy, so I wish to thank you very much for taking the time to consider my issue.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I've changed the `ClasspathScanner` and `ConsoleLauncher` related classes to use `Path` instead of `File`.

The only places left that use `File` instances are `FileSystemSource` and its implementing classes `FileSource` and `DirectorySource`. Right now, test engines that consume `FileSelectors` and create `Path` instances for non-default file systems can use neither `FileSource` nor `DirectorySource` because they would have to convert their `Path` instances to `File` instances but `Path.toFile()` will throw an `UnsupportedOperationException` in this case. They should be able to convert the path to a `URI`, though.

We could change `FileSource` and `DirectorySource` to store a `URI` instead of a `File` and provide a methods that return a `File`/`Path` from the `URI`. However, both methods would only work for the default filesystem.

**Comment by jbduncan** [comment]
Hi @marcphilipp.

With your current proposal, I can see why `(File|Directory)Source.toFile` would work only with the default file system, but not why a `toPath` method would have the same restriction.
 
Could you explain further why you think both `toFile` and `toPath` would only work for the default file system?

**Comment by marcphilipp** [comment]
You're right! `toPath` would work for all installed `FileSystemProviders` that support creating paths from URIs without having to previously create a corresponding `FileSystem` manually.

**Comment by jbduncan** [comment]
Ah yes, that makes sense to me.

Admittedly, it took me a while to understand what you were trying to explain, but after reading the method javadocs of:
- https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html#get-java.net.URI-
- https://docs.oracle.com/javase/8/docs/api/java/nio/file/spi/FileSystemProvider.html#installedProviders--

...the class javadoc of:
- https://docs.oracle.com/javase/8/docs/api/java/nio/file/FileSystems.html

...and the source code of:
- https://github.com/google/jimfs/blob/master/jimfs/src/main/java/com/google/common/jimfs/SystemJimfsFileSystemProvider.java

...I now understand what you mean and that you're indeed correct.

And thus implementing `(File|Directory)Source.toPath` using `Paths.get(URI)` should work not only for the default file system, but also for non-default file systems that "install" themselves into the JVM after startup via the java.util.ServiceLoader mechanism (including third-party ones like Jimfs).

**Comment by sbrannen** [comment]
@marcphilipp,

> We could change `FileSource` and `DirectorySource` to store a `URI` instead of a `File` and provide a methods that return a `File`/`Path` from the `URI`.

In light of issues such as #477, I've been thinking we will have to move in this direction for the _entire Platform_. In other words, we probably should not _store_ anything in either selectors or sources using a _biased_ format (e.g., `File` vs. `Path` _and_ `Method` vs. method name), since it is up to a specific engine to interpret the _raw_ format.

Let's discuss this general topic amongst the team!

**Comment by sbrannen** [comment]
**Team Decision**:

What to store in `FileSource` and `DirectorySource` will be addressed in #489.
