### ISSUE TITLE
Make sure BigDecimals are formatted correctly

### ISSUE THREAD

**Issue by ptahchiev** [junit-team/junit5#467]
Hello,

this is not a bug, but instead is a feature request. With latest JUnit 4.x I want to compare `BigDecimal` 
values so I do the following:

```
assertThat("1x125$ price - 1x25$ discount - 1x20$ voucher + 1x10$ delivery = 90$", new BigDecimal("90.0"),
                   comparesEqualTo(cart.getTotalPrice().getNumber().numberValue(BigDecimal.class)));
```

unfortunately this prints the following in the command line:

```
Expected: a value equal to <1.1E+2>
     but: <90.0> was less than <1.1E+2>
```

I'm not sure if it is a problem in hamcrest or junit but I will just log it here so that it doesn't get lost. Please make sure with the latest JUnit 5 that you use `toPlainString()` or some other way to correctly format `BigDecimal`.

**Comment by sbrannen** [comment]
By definition, those BigDecimals are formatted _correctly_ using scientific notation. So the title of this issue is not applicable in its current form. Formatting them using the _plain string_ format would actually be less _correct_ in terms of precision. An argument can be made for ease of readability by using plain string formatting; however, doing so would require special handling of `BigDecimal` in `org.junit.jupiter.api.Assertions.formatClassAndValue(Object, String)` which is currently not foreseen. In any case, let's leave this issue in the general backlog.

With regard to JUnit 4 and Hamcrest, the formatting you are experiencing is coming from the Hamcrest `Matcher` you are using. Thus, if you continue to use Hamcrest with JUnit Jupiter, you would still encounter the same formatting that you are experiencing now on JUnit 4. If you don't like how Hamcrest formats `BigDecimal`, you can of course raise an issue with the Hamcrest team.
