### ISSUE TITLE
Introduce default test class name pattern

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#490]
## Overview

Since classpath scanning may potentially eagerly load classes unnecessarily, the JUnit 5 Team has decided to introduce default patterns for test class names. Doing so will help to reduce the number of candidate classes loaded when scanning the classpath for test classes.

## Related Issues

- #474 

## Deliverables

- [x] Introduce the regular expression `^.*Tests?$` as the default class name pattern for test classes.
  - [x] in `ConsoleLauncher`
  - [x] in the JUnit Platform Gradle Plugin
  - [x] in the `JUnitPlatform` `Runner`, but only if the runner is used as a _suite_
- [ ] Document AND vs OR semantics for class name filters (see https://github.com/junit-team/junit5/issues/474#issuecomment-246189318)

**Comment by marcphilipp** [comment]
How about the `JUnitPlatform` runner?

**Comment by sbrannen** [comment]
Good point, @marcphilipp. 👍 

I'll update the issue accordingly.

**Comment by marcphilipp** [comment]
_in progress_

**Comment by marcphilipp** [comment]
I've introduced the default test class name pattern to `ConsoleLauncher`, Gradle plugin, and `JUnitPlatform` runner. However, I'm unsure where we wanted to "document AND vs OR semantics for class name filters" because neither of them allows to specify multiple class name filters. I think this should be addressed in a separate issue, shouldn't it?

**Comment by marcphilipp** [comment]
_in progress_
