### ISSUE TITLE
Tags annotation not documented in UserGuide

### ISSUE THREAD

**Issue by schauder** [junit-team/junit5#501]
I just noticed that while `@Tag` is document, `@Tags`  seems to be missing from the [User Guide section on tagging](http://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering)

I this an omission? Or is `@Tags` to be dropped?

**Comment by sbrannen** [comment]
It is in fact an intentional omission.

Since JUnit Jupiter requires Java 8+, users are never required to use `@Tags`. Rather, it's just there to make `@Tag` _repeatable_ (i.e., purely for technical reasons imposed on us by the JLS).

Users can of course use `@Tags` if they desire, but we don't see a need to document that.

I am therefore closing this issue as _works-as-designed_, but if you feel my answer is insufficient, please provide further input.
