### ISSUE TITLE
Reduce log level for detected test engines to DEBUG

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#513]
Starting within the IDE, the default log level of `INFO` results in `System.err` output by the `ServiceLoaderTestEngineRegistry` which lists the detected engines.

Should that really be the case, or should the log level be `DEBUG` for that information?

I can imagine this could be handy when a user writes a custom test engine. In all other cases, this information is perhaps of little interest.

**Comment by sormuras** [comment]
👍 tuning it down to `LOG.DEBUG`

First thing in an IDE launch is, I always mute it via `org.junit.level=WARNING` in a `logging.properties`.

**Comment by sbrannen** [comment]
The rationale for having it at `INFO` level is that it helps us to better assist users who are trying out the JUnit Platform for the first time.

For example, from that information alone we are immediately able to discern whether or not the user has the classpath configured correctly (e.g., hasn't forgotten to include the JUpiter or Vintage `TestEngine` as a dependency).

So I'm personally inclined to leave it as `INFO` for now, but I'm also open for switching to `DEBUG` if there is sufficient interest from the community in doing so.

**Comment by marcphilipp** [comment]
I think it might make sense to disable logging by default and provide a simple way (e.g. by setting a system property) to enable it that we could document in the user guide.

**Comment by sbrannen** [comment]
> I think it might make sense to disable logging by default and provide a simple way (e.g. by setting a system property) to enable it that we could document in the user guide.

If we go that route, I think we'd need to introduce our own custom logging façade to hide that additional level of indirection. Otherwise, everywhere we use logging will need to be modified with additional conditional checks. So I'm not really a fan of that... unless there is some feature of JUL that I'm unaware of which simplifies matters.

IMHO, I think it's a good idea to have logging enabled by default. Otherwise, users wouldn't even be informed of warnings or true errors.

So, introducing a "no INFO level logging" policy is perhaps not such a bad idea for a testing framework.

**Comment by sormuras** [comment]
Reducing logging level from `INFO` to `Level.`[CONFIG](https://docs.oracle.com/javase/8/docs/api/java/util/logging/Level.html#CONFIG) should be enough.

**Comment by marcphilipp** [comment]
We could go for one of the proposed solutions in [this StackOverflow post](http://stackoverflow.com/questions/2533227/how-can-i-disable-the-default-console-handler-while-using-the-java-logging-api) to disable logging of `org.junit` completely unless e.g. a system property is set.

**Comment by sormuras** [comment]
I'm still convinced, that `LOG.debug()` (or `LOG.config()`) is sufficient when detecting available test engines. As long as the "no engines found" case yields a `LOG.error()` or an exception to be thrown, everything's fine.

**Comment by smoyer64** [comment]
>   If we go that route, I think we'd need to introduce our own custom logging façade to hide that additional level of indirection.

I know you avoid having additional dependencies in JUnit but if you use the slf4j-api, those who want to enable logging can do so just by putting an implementation on their classpath.  Otherwise the NOP implementation will eat the output.

**Comment by sormuras** [comment]
> I know you avoid having additional dependencies

Period. ;-)

It's only a single logger usage within the entire JUnit 5 sources that is a bit ... loud.

**Comment by nicolaiparlog** [comment]
>> I know you avoid having additional dependencies

> Period. ;-)

To advertise Java 9 a little more, have a look at [redirected platform logging](https://www.sitepoint.com/ultimate-guide-to-java-9/#redirectedplatformlogging). :smiley:

**Comment by marcphilipp** [comment]
How would that help us? As far as I could see from skimming the project description, that JEP only takes care of redirecting Platform Logging, not JUL, right?

**Comment by nicolaiparlog** [comment]
(I didn't check whether JUL uses the new approach but wrote my previous and this comment under the assumption that it doesn't.)

JUnit could build on the new infrastructure and use `LoggerFinder` to get `Logger` instances, piping all messages through them. End users can then use the platform-logging-log4j2-bridge (once it exists; or whatever logging framework they prefer) to get those messages out.

Since JUnit 5 is surely going to target Java 8, more indirection is needed, though. JUnit would need its own logger interface and via multi-release JARs that could either be backed by JUL (in Java 8) or `LoggerFinder` (Java 9). Quite a lot of complexity...

**Comment by sormuras** [comment]
Before thinking of designing and implementing a logging facade in JUnit 5, I'm preferring Marcs' simple proposal:
> We could go for one of the proposed solutions in this StackOverflow post to disable logging of org.junit completely unless e.g. a system property is set.

...more and more. The commit https://github.com/junit-team/junit5/commit/ddcfb41b0f824cdbaae7cf868d3491e555ced4f6 already made me circumvent the there in muted log level change by configuring the JUL facility via a custom JVM switch **and** an extra property file. Which felt and still feels awful.

A simple `-Djunit.debug=true` (checked via [Boolean.getBoolean()](https://docs.oracle.com/javase/8/docs/api/java/lang/Boolean.html#getBoolean-java.lang.String-)) that guards all INFO level logging statements would render the properties file superfluous. If the debug switch is set to false (which it is by default) the logging statement is still emitted at CONFIG or FINE level.
