### ISSUE TITLE
Beginner needs help!

### ISSUE THREAD

**Issue by JingMa87** [junit-team/junit5#528]
Hi JUnit5 community,

Sorry for asking my question like this, I hope I'm not offending anyone. If I did offend anyone, I'll remove this message asap.

I'm an intermediate programmer who's new to open source and would love to contribute to JUnit5. However, there's no info here for people who are new to open source and no mailing list or common chat. Can anyone help me get started? Or is JUnit5 for people who are more experienced in open source?

Thanks a lot for your time!

Jing

**Comment by jbduncan** [comment]
Hi @JingMa87, no need to apologise! You haven't offended me at least, and I'm sure any other reasonable person here wouldn't be offended by your perfectly reasonable question either.

I'm not personally on the JUnit 5 team, but I could perhaps give you some pointers on contributing to the project, as I'm also relatively new to open source. (However, despite what I say next, I'd recommend you wait until someone on the team like @sbrannen or @marcphilipp replies to this thread, in case anything I suggest is actually going to be in the way for them.)

JUnit 5 isn't the easiest project to get into, but assuming you have at least some confidence in your Java, I recommend looking at the [up-for-grabs](https://github.com/junit-team/junit5/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs) Issues and, if any grab your eye, seeing if you have the skills to work on any of them.

Otherwise, I recommend doing one of more of the following.

- star and [watch](https://github.com/junit-team/junit5/subscription) the project (JUnit 5 could always use more awareness! :wink:)
- keep an eye out for new Issues/Pull Requests as they crop up (or maybe even search through some old ones)
- present your opinions on Issues, if you feel there's anything worthwhile to say
- review PRs
- and use JUnit 5 in your own projects to see where things could be improved or bugs need to be fixed

I personally started on JUnit 5 by following [this issue](https://github.com/junit-team/junit5/issues/167) submitting [this PR](https://github.com/junit-team/junit5/pull/294). If the up-for-grabs issues are too difficult for you, perhaps this could give you some inspiration? :)

**Comment by JingMa87** [comment]
Wow @jbduncan, I read your commit and there's a lot of code that I don't understand yet. For example stuff like Iterator<?>. Does that mean I shouldn't contribute code yet? I never learned this stuff in my compsci courses. Are other open source projects easier? I'm almost getting nervous since I already spend 4 days researching open source and it seems impossible for me to get started. I've been programming for 2 years now as a hobbyist. What do you think?

**Comment by jbduncan** [comment]
Hi @JingMa87, I don't know what CompSci courses you took, but I can share with you my own background, in the hope that it lets you feel more confident about approaching open source.

I'm currently in my final year of university where I'm studying Computer Science. I developed an interest in Java in my first year, and since then I discovered [Guava](https://github.com/google/guava), a library which caught my interest due to its usefulness and its clean API and underlying implementation.

For the longest time I just lurked the Guava GitHub page, but after peacefully reading through the source code and a couple of well-known Java books - 'Effective Java 2nd Edition' and 'Java 8 in Action' - I gradually learned more about the Java language and good programming practices. It was only in the last couple of months or so that I grew confident enough to contribute to JUnit 5, which I discovered and backed through the JUnit Lambda crowdfunding campaign on Indiegogo.

You asked whether you shouldn't be contributing code to JUnit 5 just yet. The way I see it, it's not really an issue of whether you _should_ contribute code yet, but rather if you've found something which interests you and which you feel you have the knowledge to help out with. And it seems you've already met the first criteria.

Regarding that commit I linked to, the initial hard work was actually done already for me in [`Assertions.assertArrayEquals(Object[], Object[]`](https://github.com/junit-team/junit5/blob/master/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java#L793), so I didn't have to think about the structure per se. But because I knew enough Java from my education, Guava and those 2 books I mentioned, I realised that the code could be adapted for `Iterable`s as well (and thus `Collection`s, `List`s, `Set`s, etc.), so I thought, "Hey, I can see how this would work, and I have some free time right now, so let's see where this goes."

I don't know how much Java you know, but if you're feeling overwhelmed by more advanced parts of the language like `Iterator<?>`, I would suggest that you look at ['Effective Java 2nd Edition'](https://www.amazon.co.uk/Effective-Java-Second-Joshua-Bloch/dp/0321356683) on Amazon, look through the "Look Inside!" section, and if it seems interesting to you, read the whole thing peacefully and at your own pace.

I also don't really know if other open source projects are easier to contribute to, but if you still find it difficult to find something to work on in JUnit 5, then how about looking through the [awesome-java](https://github.com/akullpp/awesome-java) list.

Hope this helps.

**Comment by JingMa87** [comment]
Hi @jbduncan, thanks a lot for your extensive answer. It helped me a lot and I think I'm going to browse through the Issue Tracker to see if there's something I can work on. I also subscribed to a mailing list of the NetBeans open source project.

Good luck on your studies!

**Comment by marcphilipp** [comment]
I think @jbduncan's advice is excellent and I agree that JUnit might not be the easiest open source project to start contributing. I'm closing this issue as @jbduncan has provided you with very good pointers on how to get started.
