### ISSUE TITLE
Split Engine API package into subpackages

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#54]
## Proposal

(not checked for package cycles etc., yet)

org.junit.gen5.engine.api
- TestDescriptor
- TestSource
- TestTag
- TestEngine
- ExecutionRequest
- EngineExecutionListener
- EngineAwareTestDescriptor
- discovery
  - AllTestsSpecification
  - ClassSpecification
  - ClassFilter
  - ClassFilters
  - ClassNameFilter
  - EngineFilter
  - MethodSpecification
  - PackageSpecification
  - TestPlanSpecification
  - TestPlanSpecificationElement
  - TestPlanSpecificationElementVisitor
  - UniqueIdSpecification
- support
  - descriptor
    - AbstractTestDescriptor
    - EngineDescriptor
    - FileSystemSource
    - JavaSource
  - hierarchical
    - Container
    - EngineExecutionContext
    - HierarchicalTestEngine
    - HierarchicalTestExecutor
    - Leaf

**Comment by schauder** [comment]
Not a fan of content in a package as plus subpackages, because it immediately brings up the question: What goes in the super package? If I have a class, that doesn't fit one of the existing subpackages, should I create a new subpackage, or put it in the super package.

Also `*Filter` seem to deal with detection of /search for tests, while `*Specification` sounds more like Specification of Test Execution, so these might belong in two different packages.

**Comment by jlink** [comment]
Done in master.
