### ISSUE TITLE
@Check instead of @Test

### ISSUE THREAD

**Issue by Ernesto-Maserati-CH** [junit-team/junit5#551]
In JUnit there is the @Test annotation. According to James Bach and Michael Bolton, "test" can be considered a misleading label in that context.

More appropriate would be **@Check** because testing can't be automated whereas checking can be done by a machine.

See Bolton's blog where he explains what a test is and what an automated check is: http://www.developsense.com/blog/2009/08/testing-vs-checking/ (read the **old** version first I recommend).

What about deprecating @Test annotation and replacing it with @Check in JUnit 5?

**Comment by mlevison** [comment]
James is an interesting character and the idea useful. However mainstream acceptance of the idea is poor. I wouldn’t get upset about a synonym but changing the nature of unit testing (another imperfect name) to fit his world view is not useful.

Cheers
Mark

On October 26, 2016 at 11:39:18 AM, Ernesto-Maserati-CH (notifications@github.com) wrote:

In JUnit there is the @Test annotation. According to James Bach and Michael Bolton, "test" can be considered a misleading label in that context.

More appropriate would be @Check because testing can't be automated whereas checking can be done by a machine.

See Bolton's blog where he explains what a test is and what an automated check is: http://www.developsense.com/blog/2009/08/testing-vs-checking/ (read the old version first I recommend).

What about deprecating @Test annotation and replacing it with @Check in JUnit 5?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Mark Levison
Sent with Airmail

**Comment by smoyer64** [comment]
If you want @Check, you can create an alias for @Test through the beauty of JUnit 5's meta-annotations.

**Comment by sbrannen** [comment]
I agree with @smoyer64: If you want to create a custom alias for `@Test`, you are perfectly free to do so using JUnit Jupiter's first-class support for composing annotations.

Similarly, I agree with @mlevison: the term _testing_ as used in frameworks like JUnit is beyond well established in the world of computing. As such, there is no confusion regarding the meaning of an annotation such as `@Test`. Consequently, although one may propose terms better suited in certain contexts, it does not benefit the community at large to diverge from well established terminology.

In light of the above, I am resolving this issue as "won't fix".
