### ISSUE TITLE
Provide additional context in error messages

### ISSUE THREAD

**Issue by RobLewis** [junit-team/junit5#602]
## Overview

As requested I am opening a new issue on this. See https://github.com/junit-team/junit5/issues/586#issuecomment-266522369 for background.

I'm new with JUnit, and my early attempts have been frustrated by messages such as: 
`PreconditionViolationException: Could not load class with name: DirectoryTest`

Well, WHY couldn't you load the class??

I'm left trying to guess what the problem could be.

It seems to me that a lot could be done to make error messages actually helpful. 

## Related Issues

- #1666

## Deliverables

- [ ] Where possible, provide additional context in error messages or log exceptions (e.g., in `ReflectionUtils`).

**Comment by sbrannen** [comment]
Thanks for raising the issue.

**Comment by sbrannen** [comment]
Added _Deliverables_ and reworded title.

**Comment by SoftwareInventions** [comment]
If no one else wants this one, I'd like to give a small software engineering class a shot at understanding enough of the codebase to help with this issue.  If there is more detail on what sort of detail would be of value, pls let me know.

**Comment by sbrannen** [comment]
Hi @SoftwareInventions,

Nobody is currently working on this issue, so it's still "up for grabs". 

The scope of this issue is rather broad in nature, but a specific area that your class could work on is [ReflectionUtils](https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ReflectionUtils.java). The corresponding tests can be found in [ReflectionUtilsTests](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/java/org/junit/platform/commons/util/ReflectionUtilsTests.java).

Due to an architectural decision _not_ to propagate all exceptions encountered in `ReflectionUtils`, the code sometimes returns an _empty_ `Optional` or similar. In such cases, we do not want to change the code to propagate the original exception. Rather, we would prefer to log the exception (with sufficient contextual information) at its source and keep the code functionally the same.

Let us know if you need any further tips.

**Comment by sbrannen** [comment]
Of course, if you encounter cryptic errors elsewhere in the code base, feel free to propose better exception handling and/or error messages in such cases as well.

**Comment by SoftwareInventions** [comment]
@RobLewis: Would be helpful to see just what usage case engendered the cryptic message for you.  What JUnit feature were you using that got you that message?

**Comment by RobLewis** [comment]
Hello. It was my first attempt at using JUnit and I didn't really know what I was doing. Did you see my comment on the earlier issue? It gives the best explanation I have: [https://github.com/junit-team/junit5/issues/586#issuecomment-266522369](url)
_DirectoryTest_ was the first JUnit test class I was trying to create and use. 
I'll try to answer any other questions you might have.

**Comment by RobLewis** [comment]
If you didn't see my initial report, start there: [https://github.com/junit-team/junit5/issues/586#issuecomment-266522369](url) 
Hmm, for some reason that link doesn't work. Try this: https://github.com/junit-team/junit5/issues/586#issuecomment-266522369 (appears to work). See my comments on Dec. 7 and Dec. 12. 
If you have more questions I'll try to answer them.

**Comment by nicolaiparlog** [comment]
> Due to an architectural decision not to propagate all exceptions encountered in `ReflectionUtils`, the code sometimes returns an empty `Optional` or similar.

I did not look at the code so this suggestion might not fit the bill, but have you thought about using something a little richer than `Optional` to return errors without falling back to throwing exceptions? Maybe something like [`Try`](http://www.javaslang.io/javaslang-docs/#_try) or [`Either`](http://www.javaslang.io/javaslang-docs/#_either) (these links go to the Javaslang docs - creating a slimmed down version of these classes would be quite straight-forward)?

**Comment by marcphilipp** [comment]
@nicolaiparlog Thanks for the suggestion! That might indeed be a viable alternative.

**Comment by sbrannen** [comment]
Slating for 5.0 M5 for the time being, even if only to add more context in select places within the code base in time for 5.0 GA.

**Comment by marcphilipp** [comment]
@sormuras Did you have a chance to look into this, yet?

**Comment by sormuras** [comment]
No, yet. M6 is a good goal.
