### ISSUE TITLE
InstancePostProcessor not invoked when extension is defined on test method

### ISSUE THREAD

**Issue by slu-it** [junit-team/junit5#603]
I was testing JUnit 5's lifecycle in regards to the different extension types for a blog I wrote. In doing so I found out that `TestInstancePostProcessor` extensions are not invoked when declared on a test method like this:

```java
public class SomeTest {
  @Test
  @ExtendsWith(MyTestInstancePostProcessor.class)
  void testSomething(){
    ..
  }
}
```

Was this an oversight, or a deliberate decision? On the one hand I find it hard to formulate a viable usecase for having a special post processor just for a single method. But on the other hand: Every method is invoked on its own 'personal' test class instance - so why not allow it?

The code I used to test this is available [here on GitHub](https://github.com/nt-ca-aqe/blog-junit5-test-lifecycle/tree/master/src/test/java/example), specifically the [`TestsWithExtensionsOnOneMethod`](https://github.com/nt-ca-aqe/blog-junit5-test-lifecycle/blob/master/src/test/java/example/TestsWithExtensionsOnOneMethod.java) test class.

**Comment by marcphilipp** [comment]
I was more of a forward-looking design decision because we're planning on introducing "scenario tests" (see #48) where not every test method would habe its own personal test class instance. 

However, we could still consider taking TestInstancePostProcessors registered on methods into account for regular tests. I guess we would then have to throw an exception if someone tries to do that in a scenario test.

@junit-team/junit-lambda What do you think?

**Comment by nicolaiparlog** [comment]
I think a lot speaks for including the extension point:

* unit tests will likely be the much more common case so I'd say it has prerogative
* that the extension is not included in unit tests is more surprising than that it is not included in scenario test 
* throwing an exception is much more explicit than ignoring an extension

I consider the second point to be the strongest. A user can deduce why scenario tests can have no such extensions just by understanding scenario tests and the extension model. If you just know about unit tests and the extension model, you would assume that the extension point is active. To understand why it is not, you need to know about _a third thing_, namely scenario tests, which are otherwise pretty unrelated.

**Comment by sbrannen** [comment]
> However, we could still consider taking TestInstancePostProcessors registered on methods into account for regular tests. I guess we would then have to throw an exception if someone tries to do that in a scenario test.

If we throw an exception in cases such as scenario tests, I can live with supporting `TestInstancePostProcessor` at the test method level.

Please keep in mind that the _switch_ that turns on "test instance per class" semantics will almost certainly be a generic feature that anyone can enable whenever he or she wishes (i.e., like it was in the JUnit Lambda prototype).

**Comment by marcphilipp** [comment]
I have assigned this issue to M4 since it's required to inject parameters into fields which is a common use case for parameterized tests, e.g. when providing migration support for the `Parameterized` runner.
