### ISSUE TITLE
Execution of @Ignore junit 4 tests is not possible with junit 5 launcher

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#605]
I have a project with mixed junit 4 and junit 5 tests, one of junit 4 test method is disabled with @Ignore annotation. If there is no junit 5 in the classpath, then IDEA is able to run the test when explicitly selected, e.g. to ensure that it still fails, etc. When there is junit 5, IDEA pass launcher with the method name has no influence on the org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder which creates ignoreBuilder. Would be cool if junit.conditions.deactivate would influence this or some other mechanism would be provided.

**Comment by marcphilipp** [comment]
I agree that this would be desirable! However, the `ignoredBuilder` is only used if the `@Ignore` annotation is present on the test class level, not when used to annotate methods. So, to implement this feature, JUnit 4 also needs to add support for this feature. In JUnit 4 the runner is responsible for determining which of its children should be ignored. The `@Ignore` annotation is being checked for in `BlockJUnit4ClassRunner.isIgnored`. This method would need to be changed in addition to `ignoredBuilder()`. Moreover, since people might still use `JUnit4ClassRunner` another change would be required in `org.junit.internal.runners.TestMethod`.

**Comment by marcphilipp** [comment]
@kcooney Would you support deactivating the `@Ignore` annotation via a system property like Jupiter does it?

**Comment by kcooney** [comment]
@marcphilipp while I wouldn't be opposed in theory, there are a number of placers where this would need to be done

- JUnit4TestAdapter
- TestMethod
- BlockJUnit4ClassRunner
- IgnoredBuilder

For `IgnoredBuilder` there is the question of whether you can run an individual method in a test class annotated with `@Ignore` and ignore the other methods.

**Comment by marcphilipp** [comment]
@akozlova Does IntelliJ IDEA allow to run test methods when the class is annotated with `@Ignored`?

**Comment by akozlova** [comment]
With junit 4:

1. If you run the test class and it has Ignore annotation, then all test methods of the class would be executed. 
2. If you run a method in the test class where the test class is annotated as Ignore, the test method would be executed.
3. If you have a test method, annotated as Ignore and you run this method, then the method would be executed.
4. If you run the class with some methods, annotated as Ignore, then annotated with Ignore methods won't be executed.

If you see something else, then it's a bug ;) The idea behind is: if user starts something, he means it to be executed even if it should be excluded when run in batch.

**Comment by frkline** [comment]
+1 This turned into a headache/hurdle (read: angry people) when adding JUnit5 to an existing JUnit4 ecosystem, as it broke existing workflows used by developers: @akozlova's *#*3

**Comment by marcphilipp** [comment]
@frkline Thanks for letting us know!

**Comment by marcphilipp** [comment]
@akozlova Is this still an issue?
