### ISSUE TITLE
Investigate if dependency of launcher and engine API to commons can be avoided

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit5#609]
Follow-up on #586.

Possible solutions from team brainstorming:

- Shadow commons into all artifacts that use it
- No breaking changes in commons, not even in internal code
- Isolate Launcher from rest of platform

If not possible, document [workaround](https://github.com/junit-team/junit5/issues/586#issuecomment-265012600) for IntelliJ and other IDEs.

**Comment by akozlova** [comment]
Please treat the workaround as the very last solution. Since M3 is released, I get multiple error reports though we put the warning with a workaround everywhere we could think of. I think that I can just reject to work if the versions won't match but this could break M4 if it won't contain incompatible changes to M3 so I am hesitating before such step

**Comment by sbrannen** [comment]
> - Shadow commons into all artifacts that use it

I think this is a reasonable and robust approach. Thus, I would vote for this option.

> - No breaking changes in commons, not even in internal code

We can only make that guarantee once 5.0 GA is released; otherwise, we are binding our own hands unnecessarily. Thus, I would personally veto this option.

> - Isolate Launcher from rest of platform

Can you please expound on that proposal?

**Comment by sbrannen** [comment]
Also, shouldn't this be slated for M4?

**Comment by nicolaiparlog** [comment]
> * Shadow commons into all artifacts that use it

I hope this would be a temporary measure until GA? Not only do I consider this bad practice, as the Java 9 module system is implemented at the moment that would prevent using the JUnit artifacts as modules (_ packages_).

**Comment by nicolaiparlog** [comment]
> * Shadow commons into all artifacts that use it

I hope this would be a temporary measure until GA? Not only do I consider this bad practice, as the Java 9 module system is implemented at the moment that would prevent using the JUnit artifacts as modules (_split packages_).

**Comment by sbrannen** [comment]
@nicolaiparlog,

No, that would not introduce split packages.

When we use the Shadow plugin to incorporate code from a different JAR we _move_ the code to a different _local_ package.

So there are no concerns with regard to Java 9.

**Comment by sbrannen** [comment]
The commons JAR can still be made available with its original, untarnished packages as is the case today.

**Comment by sbrannen** [comment]
Hmmmm... wait!

Now that I think about it, using the Shadow plugin to move types to different packages is a "no go" for the following reasons.

1. `JUnitException` and its subtypes (e.g., `PreconditionViolationException`) cannot live in different packages since that results in different types at runtime.
1. `@Testable` cannot be moved to a different package; otherwise, it becomes useless.
1. `@API` cannot be moved to a different package; otherwise, it becomes useless.

Although, it would be theoretically possible to repackage the utilities (except for dependencies on `JUnitException` and its subtypes), we should rethink our options here.

**Comment by nicolaiparlog** [comment]
> When we use the Shadow plugin to incorporate code from a different JAR we move the code to a different _local_ package.

Oh, that sounds like fun - what could possibly go wrong.  :innocent:

**Comment by marcphilipp** [comment]
Shadowing does not seem feasible after all, we'll have to take care not to introduce breaking changes in commons, not even in internal code.
